### ISSUE TITLE
Download Workflow Job logs from server

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#102]
As @jluethi mentioned in #98 

> On a higher level: The user would expect to get a zipped folder containing the logs for the relevant job

Currently the fractal server responds with a `StreamingResponse`

Things to be checked:

- [x] It is possible to create a zip file from the browser? Does the browser API allow this?
- [x] It is possible to write a `StreamingResponse` directly to a file? Does the browser APIs allow this?
- [ ] If none of the preceding questions are positive, is it possible that the server bundles the response as a `File` in order for the browser to be able to open a download dialog?

**Comment by jluethi** [comment]
It should certainly be possible to click a button in a browser that triggers the download of a Zip file to the download folder, without a download dialog. Many sites where you download things work that way.

**Comment by tcompa** [comment]
Tested with 7fd8e19, and I can indeed download the zipped log folder to disk - as expected.
