### ISSUE TITLE
"refresh" button on job table "info" calls API with wrong payload

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#104]
* Open job-table page
* Open a job "info" modal
* Click the refresh button

This results in the following (wrong) API call
```
INFO:     127.0.0.1:57428 - "GET /api/v1/job/undefined HTTP/1.1" 422 Unprocessable Entity
```

**Comment by tcompa** [comment]
EDIT: this is not _always_ the case, but I did observe it.
I'll see if I can narrow down the source of the error.

**Comment by rkpasia** [comment]
You click the refresh button within the modal or within the main jobs table?

**Comment by tcompa** [comment]
Within the modal. And the modal itself already showed a lot of "undefined", so it's not a problem of the API call itself but rather a problem of the job-related information retrieval.

**Comment by rkpasia** [comment]
I'm not really able to reproduce this issue. When I navigate between multiple projects and workflow jobs pages I don't experience this issue.
