### ISSUE TITLE
"run workflow" redirects to a job table that is not up to date

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#105]
* I prepare a workflow
* I submit it for execution ("run workflow"), and I confirm
* I am redirected to a job page (e.g. http://localhost:5173/projects/2/jobs?workflow=4&id=4)
* The table is empty
* I refresh the page
* The table shows one job

**Comment by tcompa** [comment]
![Screenshot from 2023-04-18 09-16-11](https://user-images.githubusercontent.com/3862206/232700947-e8979946-6660-4a48-8621-7c9e69576663.png)

**Comment by rkpasia** [comment]
Could this issue be related to required package updates? 1914e929

I've tried to reproduce the issue following the cited steps, but the client doesn't throw any error.
