### ISSUE TITLE
Project page displays wrong project when switching between projects

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#107]
I'm testing some user workflows and discovered this issue:
When I switch between projects, sometimes the wrong project is displayed. For example, I enter project 3 first. When I then open project 3, the requested web address is correct (ID 3), but the wrong project gets displayed (project 2).
This appears to be reproducible.

It can be solved by doing a page-reload when on the project page. But if I switch to back to project 2 afterwards, project 3 is displayed.

If it was just the project page, it would be unfortunate, but not that big of a problem yet. It becomes a bigger problem because the datasets for the wrong project are then displayed and if I open a dataset, I'm actually sent to the dataset of the wrong project. Thus, a user may edit a dataset of a different project than they entered by mistake.

Here's a recording of this interaction:
https://drive.google.com/file/d/1eefiVv9jl3sndALtDpS6szdXaDwYkNSp/view?usp=sharing

**Comment by jluethi** [comment]
Any reload seems to avoid this caching, e.g. also reloading on the project overview page. But we wouldn't expect our users to reload in normal workflows

**Comment by rkpasia** [comment]
Yes this is definitely a bug that has high priority.

**Comment by jluethi** [comment]
Great, I can confirm that this bug is fixed now! :) Thanks @rkpasia !
