### ISSUE TITLE
"Add-resource" dialogue pops up again if manually closed after adding a resource

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#108]
Currently, when a user adds a new resource, a confirmation is shown in the add resource pop-up. The pop-up then closes after about 2 seconds.
See intended behavior here: https://drive.google.com/file/d/1s9W-aJRlcbl9RtrElWCBYwMTZTOdnVxV/view?usp=sharing

If the user is impatient and closes the resource adding modal before it closes itself, a new & empty add resource modal pops up, which is quite confusing. See example here: https://drive.google.com/file/d/1OFV0NS785sIC5tr6KbeFWJo2U0eQxfJI/view?usp=sharing

**Comment by tcompa** [comment]
> If the user is impatient and closes the resource adding modal before it closes itself, a new & empty add resource modal pops up, which is quite confusing

Agreed: I also often hit this issue, and find it confusing.

**Comment by jluethi** [comment]
Glad to hear I'm not the only impatient user ;) 

I don't mind the behavior of the modal not closing immediately, but closing after 2s (=> gives users a chance to see the confirmation). But I should be able to close it faster without it popping back up 😅

Alternatively, another valid behavior would be to close when the user clicks Create and show the confirmation that it has been added somewhere else. Or drop that confirmation, because it does show up in the list of resources anyway, so not really necessary to have a separate confirmation.

**Comment by rkpasia** [comment]
We could go with a different kind of confirmation that displays within the page instead of within the context of the modal.

**Comment by jluethi** [comment]
> We could go with a different kind of confirmation that displays within the page instead of within the context of the modal.

That sounds preferable :)

**Comment by tcompa** [comment]
Closing as obsolete, see e.g. https://github.com/fractal-analytics-platform/fractal-web/pull/306#issuecomment-1748482812.
