### ISSUE TITLE
Projects route shall not fetch if there is no authentication context

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#11]

**Comment by rkpasia** [comment]
Technically, this issue is no longer present since the user, using the client, won't be able to go to the `/projects` route through the GUI if he is not logged in.

The issue is broadly referred as creating routing guards, as an unauthenticated user should not be able to navigate to `/projects`. Currently if a user does so through the navigation bar, the client will let him since there are no guards in place.

Moreover, even if a user navigates to the `/projects` page, or the other implemented, there will be an error handled by the client.

Probably this issue should evolve to others, more specific.

**Comment by mfranzon** [comment]
Agree, we can close this and open a new one about routing guards.
