### ISSUE TITLE
Handling importing workflows with existing names?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#110]
Currently, the workflow name for an imported workflow is already specified in the workflow.json file. That's ok for a default, but leads to tricky behavior if a user already has a workflow of that name or wants to import the same workflow a second time. In that case, we get an error for non-unique workflow names. See video here: https://drive.google.com/file/d/1Cr5o3m0qo_GLfm_XsCw-hxd1oGZkp-96/view?usp=sharing

The only workaround atm is to go into the other workflow and rename it.

I think this could be simplified and there are a few options:
1. import-workflow has an optional name field and if the user provides a name, the workflow-name is overwritten with it => we can still enforce unique names, but give the user an easy way to create a new unique name when importing the workflow
2. We make the name unique upon workflow import, e.g. append a suffix like _1, _2 etc. until it's a unique name

**Comment by tcompa** [comment]
> import-workflow has an optional name field and if the user provides a name, the workflow-name is overwritten with it => we can still enforce unique names, but give the user an easy way to create a new unique name when importing the workflow

I think this is the best option.

I wouldn't expect a user to import the same workflow more than a few times (if they have to import the same workflow into the same project more than 2-3 times, without ever removing or renaming the existing workflows, this looks like a broken use flow), and then I see no compelling reason for making up a suffix scheme.

Also: if you end up with "cardiac_wf_1", "cardiac_wf_2" and "cardiac_wf_3", I don't think it will be easy to remember their meaning..

**Comment by jluethi** [comment]
I'm in favor of this option => import workflow gets an optional workflow name field.

**Comment by tcompa** [comment]
Fixed with #269.
By now we kept the import-workflow button on the left, but we also transformed all "Create X" buttons into "Create new X".
