### ISSUE TITLE
Make Job table accessible from within a workflow

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#111]
Currently, the user gets redirected to the job table when running a workflow and they can get there from the project overview page. But when they are in the workflow again, there is no button to get them there. I'd propose we add the same option as we have in the workflow list (with the pre-applied filter for the workflow) to the workflow page.

Instead of this:
<img width="1432" alt="Screenshot 2023-04-18 at 10 26 16" src="https://user-images.githubusercontent.com/18033446/232719649-5c632bcb-12e5-4345-a0db-90f57090045b.png">

We'd have something like this:
<img width="1432" alt="Screenshot 2023-04-18 at 10 25 06" src="https://user-images.githubusercontent.com/18033446/232719667-42038da8-7e68-43f2-8e50-a061e0972d5e.png">

(though preferably having the job list next to run, second from the right)

**Comment by tcompa** [comment]
I cannot reproduce. This is what I see with current main (i.e. 170714feff8a7dcc73228c0c92890f1d6f15b7d3).

![Screenshot from 2023-05-03 08-24-49](https://user-images.githubusercontent.com/3862206/235845099-6f26955a-ee4a-46d6-bd95-7edf35fc52c3.png)

Additional details:
* Can you specify the commit you're at?
* Is there any information in the browser console or in the web-server logs?

**Comment by jluethi** [comment]
Sorry, I thought I was on current main, but was on a feature branch 🤦🏻‍♂️ All good!
