### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#114]
Since the Fractal web client is approaching its first usable version, having some documentation will soon become important. We briefly discussed with @mfranzon about it. Instead of focusing on the choice of a specific framework, here are a few high-level points that we see as a good start.

1. Target readers:
    * The Fractal dev team, in 6 months or one year: we will obviously not remember why a certain choice was made.
    * Other research groups who want to give a try to Fractal. If they go above a minimal commitment threshold, and setup a fractal-server instance, they may as well just spin up a web client to make its use simpler. Without some basic docs, this is not a real option.
2. We should not aim at autogenerated documentation for all components/functions/modules of the package (like the one on fractal-server or fractal-tasks-core). Still, we should make sure that code has a decent amount of explanatory comments (which we could, in the future, turn into standardize docstrings to be parsed with some tool).
3. As a first version, let's aim for the least possible effort in maintaining/serving the docs. If there is no ready-to-use framework, we can even start with a `docs` folder containing a few markdown files - and we'll later set up a proper documentation (compiled and served, e.g. on github pages).
4. What should be there:
    * How to install the package (possibly with common gotchas).
    * How to run the package (possibly with common gotchas).
    * Known limitations. Examples are: (A) safari not (currently) supported, (B) a certain fractal-server feature/version is not supported, ...
    * Release notes (this means that we'll start having some kind of release, even just on github, and to keep an up-to-date CHANGELOG.md file in the repository root)
    * Description of specific technical choices. Random examples: (A) the use of a svelte store for the project context, (B) the choice of `datatables` to show the jobs table, (C) how we (will) implement the use of JSON schemas for task arguments, ... This should be a more structured version of a development log, which we can look back at in the future when we need to review and possibly override a certain choice.

Given the experience with the other Fractal repositories, I'd put the stress on point 3: let's not get lost in the huge landscape of documentation frameworks. If we have time to invest, let's use it to write some clear and complete markdown files - and then we'll find a decent way to publish them..

**Comment by rkpasia** [comment]
Would it be possible to use the wikis provided by GitHub?

It could be a great solution to keep docs within MDs (for future portability) and with a nice experience for a user to explore them.

**Comment by tcompa** [comment]
The problem with GitHub wiki is that it's not versioned (or at least not in a transparent way), which for me is quite a big no.

In fact, after rethinking about this, I am in favor of an even simpler solution: let's have a nice `README.md` file (or a `docs.md` file, if we'd rather keep the README short) and it will be more than enough for the beginning.

**Comment by tcompa** [comment]
Marking this as high priority, at least in some preliminary form.

I think the key element that should be included are:

1. Basic dev howto: how to install, how to run with vite, how to build, how to run with node, how to run static code analysis, how to run vitest tests, which env variables should be set (and in which file, either `.env` or `.env.development`).
2. A brief description on how to startup fractal-server, which in principle is already self-contained in a given example repo folder (now in `lib/fractal-server/example_server_startup`, but we can move it somewhere else if it helps).
3.  Description of the basic code base structure, with a special focus on server/client separation (as in SSR) and on how it's encoded in the source code (files with `server` in their name vs other files).
4. A mention of specific dependencies and their use (ajv, datatables, others?).
5. A description of how the components that handle JSON Schemas are structured.

And then any additional info (e.g. the ones mentioned above, but also anything else) is obviously welcome.

I'd go with the most basics format ever, namely a single (decently structured) README.md file.

**Comment by tcompa** [comment]
With #237 we have a revamped docs structure, and some more contents. This issue remains open, since there's still quite a lot of work to do with re-organizing and filling the different sections.

**Comment by tcompa** [comment]
Much more work is needed, but here is a first rendered version: https://fractal-analytics-platform.github.io/fractal-web.

**Comment by jluethi** [comment]
Oh, that's awesome!

I have a new contributors section I made for the splash page we can use in a few places, like this doc start page:

> Fractal was conceived in the Liberali Lab at the Friedrich Miescher Institute for Biomedical Research and in the Pelkmans Lab at the University of Zurich by [@jluethi](https://github.com/jluethi) and [@gusqgm](https://github.com/gusqgm). The Fractal project is now developed at the [BioVisionCenter](https://www.biovisioncenter.uzh.ch/en.html) at the University of Zurich and the project lead is with [@jluethi](https://github.com/jluethi). The core development is done under contract by [eXact lab S.r.l.](https://www.exact-lab.it/).

**Comment by tcompa** [comment]
A few small improvements are underway, especially a review of the quickstart page.
I think that after #492 we can close this one, and then open issues for specific parts of the docs if they are missing or unclear.
