### ISSUE TITLE
Deploy fractal web behind a http proxy server

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#116]
We were discussing deployments at FMI with Enrico this morning. One important point that came up was the hard requirement to make the web server accessible via an http proxy service. Enrico strongly recommended the Apache httpd, while the gunicorn website shows nginx as an example for this (which Enrico discourages).

Also, Enrico mentioned that often issues with forwarding can come up when behind a HTTP proxy server. Not sure how much this would affect us.

Let's talk about this at the call today.

**Comment by tcompa** [comment]
> nginx as an example for this (which Enrico discourages).

nginx was indeed our go-to choice, but we can explore other options.

**Comment by tcompa** [comment]
V0.3 was already run behind a proxy at FMI (but still making use of SSH tunnels).
V0.4 (and upcoming v0.5) remove the need of the SSH tunnel for the fractal-server API.

What is left now is to open port 80 to connections from the local network (either at FMI or UZH), and verify that this a user who opens the correct ip from the browser can access fractal-web correctly.

**Comment by tcompa** [comment]
Closing - see multiple examples in https://github.com/fractal-analytics-platform/fractal-web/tree/main/examples
