### ISSUE TITLE
Automatic updating of the job page to fetch new status

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#119]
e.g. every x seconds

Fancy: Only refresh while any workflow is on running

**Comment by jluethi** [comment]
When one job is either pending or running, refreshing makes sense.
If everything is done or failed, updating will not do anything and can be avoided

**Comment by jluethi** [comment]
Let's go with a single call to refresh the whole table, not individual calls for each job

**Comment by tcompa** [comment]
Note: this update should only take place (at regular intervals) if the page is open.

(this may require further definition, depending on the implementation details)

**Comment by tcompa** [comment]
Also:
depending on https://github.com/fractal-analytics-platform/fractal-server/issues/920, and on how many API calls we need to do, the update will be somewhat heavier on the per-user page. If needed, we can make this kind of update less frequent, with respect to the workflow page.
