### ISSUE TITLE
Tag and release 0.3

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#124]
With https://github.com/fractal-analytics-platform/fractal-web/pull/123, milestone 0.3 is in principle over. Let's close as soon as we have some additional checks by me and @jluethi.

Then we should:
* Add a 0.3 tag
* Make a github release

For the moment the github release is not crucial, but we should start getting some experience on how we want things to be. Let's begin with the simplest option (that is, let's not include the build files), and ater on we can check what's best re:
* Should we actually attach the bundle to the release?
* Should we build it as part of a github action, so that we have a more predictable output (e.g. we always build with the same `node` version)?

**Comment by jluethi** [comment]
I checked the minor fixes in https://github.com/fractal-analytics-platform/fractal-web/pull/123 and confirm that they are working as expected.

👍🏻 for a 0.3 release and starting to explore the release process :)

**Comment by tcompa** [comment]
Release: https://github.com/fractal-analytics-platform/fractal-web/releases/tag/0.3.0
Tag: https://github.com/fractal-analytics-platform/fractal-web/tree/0.3.0
