### ISSUE TITLE
Unexpected override of key-value pair in `object` task argument

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#125]
While modifying the arguments of a WorkflowTask:

* I create an `object` argument, and I expand it
* I add a key-value pair, with name `name` and any value (say the string `"old value"`)
* I add a new key-value pair, with the same name `name` and a different value (say the string `"new value"`)
* I see no error/warning messages, and the old key-value pair is replaced by the new one.

I'm not sure about what's best, but this does not seem natural to me. I would have rather expected an error like "name already exists" (either explicitly shown, or at least preventing the override of a key-value pair).

**Comment by rkpasia** [comment]
![Screenshot 2023-04-20 alle 11 02 43](https://user-images.githubusercontent.com/5786033/233316636-5b911e9d-f455-455e-8576-e6790bdfa4e3.png)

**Comment by tcompa** [comment]
Thanks! I confirm it matches with the expected behavior.
