### ISSUE TITLE
Dataset.meta visualization

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#126]
The "Meta" section of the single-dataset page will need a (minor) update, because the attributes contained in the `meta` object can be quite verbose (for instance there may be 400 elements of `components`, or the `history` string could be quite long and not fit there).

Example:

![Screenshot from 2023-04-20 10-27-53](https://user-images.githubusercontent.com/3862206/233307198-92c5327c-594a-44bb-b656-a38f8dcba405.png)

Possible ways out:
1. We could just show the names of the `meta` entries, and hide the values;
2. We could have a "view meta" button that opens a (wide) modal with all the keys and values
3. ... other ideas?

**Comment by jluethi** [comment]
I'd be in favor of option 2 :)

**Comment by rkpasia** [comment]
![Screenshot 2023-04-20 alle 11 26 05](https://user-images.githubusercontent.com/5786033/233322648-0a7dbb16-e3f6-4e1e-9bde-b4244eaf7184.png)

**Comment by rkpasia** [comment]
Not sure about button naming, in case I'll update it.
