### ISSUE TITLE
Dataset list on project page does not always update after dataset creation

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#132]
If a user runs into an error on dataset creation (e.g. they forget to enter a name) and then correctly create a dataset afterwards (by providing a unique name), the dataset list on the project page doesn't update.

Came up during yesterday's demo. Leads to the confusing outcome of users pressing create dataset again and getting an error that the dataset already exists ;)

**Comment by rkpasia** [comment]
I could not reproduce the same issue you were experiencing @jluethi.
I think that with the refactor occurred this problem has been fixed as a (positive) side effect.
(If someone is able to reproduce the issue again, we'll reopen it)

There is a thing, tho, **is it correct that a user could create two datasets for the same project having the same name? For instance two "default" datasets?**
