### ISSUE TITLE
Project-creation does not trigger project list update

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#139]
Related to https://github.com/fractal-analytics-platform/fractal-web/issues/132

* Create a project
* The fractal-server logs display a successful API call, with 201 (CREATED) status code.
* The project is not visible in the fractal-web projects page.
* Refresh the page.
* The project is now visible in the fractal-web projects page.

**Comment by rkpasia** [comment]
Closed by 0a768cce7a645dcb9db44dfc6536b442fe1a9623
