### ISSUE TITLE
Display task list with richer structure

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#149]
- [x] Change order of tasks in the `/tasks` page. Sorting should be according to `task.owner` (first the ones with `null`, then the others), then `task.name`, then `task.version` (decreasing)
- [ ] Change menu to select task to be added to a workflow, as in https://github.com/fractal-analytics-platform/fractal-web/issues/149#issuecomment-1569616877 and https://github.com/fractal-analytics-platform/fractal-web/issues/149#issuecomment-1609161737

**Comment by tcompa** [comment]
A similar feature is being defined/implemented in the CLI client first (https://github.com/fractal-analytics-platform/fractal/issues/494).

**Comment by jluethi** [comment]
The eventual goal for the user is something like this:
1. Split common and user specific tasks. e.g. have 2 tabs, one with common tasks and one with user specific tasks.
2. In the common tasks, display the latest available version of each tasks, with an option to change the version. But not a list of all versions of e.g. the cellpose tasks that are available. Potential implementation: Have the tasks shown and a version dropdown that defaults to latest available.
3. In the user specific tasks, show the tasks of the currently logged in user first, then sort the other tasks by user, e.g. alphabetically

**Comment by jluethi** [comment]
For task list on the task page: Can be a flat list. But should also be sorted, e.g. common tasks at the top, then users

**Comment by tcompa** [comment]
To clarify the data structure:
1. A task is "common" if `task.owner` is `null`.
2. How to know if a task that has a non-`null` owner belongs to the current user? If the user has a `username` attribute, then we compare `user.username` to `task.owner`. If the user doesn't have a `username` attribute, then we fall back on the user `slurm_user` attribute.
3. A group of tasks that have the same `task.name`, the same `task.owner` and a different `task.version` are to be considered (as the name says) different versions of the same tasks, and shown as a single group (with the latest version pre-selected).
4. Point 3 is mostly relevant for _common_ tasks. I don't have a clear opinion on whether it should be also used for users' tasks.

**Comment by tcompa** [comment]
Maybe useful to compare versions:
* https://www.npmjs.com/package/semver?activeTab=readme

**Comment by jluethi** [comment]
> 4. Point 3 is mostly relevant for common tasks. I don't have a clear opinion on whether it should be also used for users' tasks.

Point 3 should also apply to user tasks if they have varying versions.

We do allow users to create tasks with the same version and name though, right? (or not)
And we enforce the source to be unique if I remember correctly.
If so, do we need a fallback to display the source somewhere, if it's the only thing we're sure that would be unique?

**Comment by tcompa** [comment]
> We do allow users to create tasks with the same version and name though, right? (or not)

We do, but version in general does not need to be unique. There can be two task with same owner, same name, same version.

(note that this could happen for common tasks as well, but it would mean that two task packages have a task with the same name.. I think we can postpone addressing this edge case)

> And we enforce the source to be unique if I remember correctly.

Exactly, the source is the only attribute that is always unique.

> If so, do we need a fallback to display the source somewhere, if it's the only thing we're sure that would be unique?

That's correct, if we expose this feature also for users' tasks then the version is not sufficient.
For sure we should always consider that only same-`owner` tasks can be grouped (otherwise there would be a huge `test` task, to which many users contribute). Still, there can be cases where the source is the only attribute that determines which task we need.

How should we proceed for users' tasks then? First options coming to mind:
1. Add a bit of pre-processing:
    * If a group of users' tasks have same name+owner and they all have different versions, proceed as for common tasks (i.e. display them as grouped).
    * If a group of users' tasks have same name+owner and the versions are not unique, display them as single tasks. NOTE: how would we include the source? Always shown?
2. For users' tasks, always show the source somehow

I'm not fully happy with either, but let's be aware that these are custom tasks and we cannot enforce a very strict structure.

**Comment by jluethi** [comment]
How about an option like this:

We group tasks by users. If a given user has multiple tasks with the same name, we show a drop-down.
There, following your logic:
> If a group of users' tasks have same name+owner and they all have different versions, proceed as for common tasks (i.e. display them as grouped).
If the versions are not unique, we could do dropdown by source. Alternatively, we just always to dropdown by source for user specific tasks with multiple tasks of the same name. Now source is not as elegant as version of course, but it will always be unique.

And for the common tasks (ignoring the edge-case you mentioned that we don't need to prioritize), version should also be unique, so there we can show version in the dropdown.

**Comment by rkpasia** [comment]
What about this interface to select tasks?

![Screenshot 2023-06-29 alle 10 10 38](https://github.com/fractal-analytics-platform/fractal-web/assets/5786033/84ec3955-b08c-4fea-a024-fed76268d495)

**Comment by jluethi** [comment]
This looks functionally fine to me, if 0.10.0a5 is the latest task (i.e. if there is no 0.10.0 task installed). Can we test how it behaves with 0.10.0 there? i.e. is 0.10.0 picked, when 0.10.0a5 is present? That would be important. 

We could certainly find a better way to display this. We are doing a modal anyway, so could show more info. Are we splitting in common & user specific? Or what's the split? It may be confusing if there are too many different options here.
Also, we could think about having 2 tabs, common & user tasks, instead of another drop-down for it. 
Finally, we could show the list of tasks in each tab, instead of having a "Select task" dropdown. Not sure if there is a standard way to do this in a modal though and we shouldn't go crazy on this selection modal.

[my local setup currently isn't working, so can't test it myself just yet]

**Comment by jluethi** [comment]
If we stick with the dropdowns, the third one should probably be named "Version" or something like that

**Comment by rkpasia** [comment]
The way I've started implementing this is:

Select the group of tasks you want to choose from: common/user.

The component filters the tasks and then displays a dropdown for unique tasks in the group (there could be duplicates by multiple versions).

Once the user has selected the task, he could specify the version (greatest selected by default).

This requires a few clicks, for sure. We could go either with tabs or select dropdown. Not sure what you (or the users) would like the most to work with.

**Comment by jluethi** [comment]
> I should double check on the point (3) the situation in which we have a task with version 0.10.0a3 and 0.10.0 because I don't think semver package handles the a3 suffix the way we could expect it to.

That has the highest priority for me, because it's functionally very relevant and would be very confusing to users if it defaults to pre-release versions of tasks.

I would say we stick with a simple implementation for the rest then and check later how to best improve the interface. I think I'd prefer a tab solution, but we'd probably need to do some iterations on what works best.

=> Let's just fix the 0.10.0a3 vs. 0.10.0 for now and improve the overall task picking interface in the fall

**Comment by tcompa** [comment]
I think the 0.10.0a3 vs 0.10.0 sorting is already handled correctly by `semver` - see the list in this comment: https://github.com/fractal-analytics-platform/fractal-web/pull/233#issuecomment-1611140054.

**Comment by tcompa** [comment]
> I think the 0.10.0a3 vs 0.10.0 sorting is already handled correctly by `semver` - see the list in this comment: [#233 (comment)](https://github.com/fractal-analytics-platform/fractal-web/pull/233#issuecomment-1611140054).

For instance (in _increasing_ order):
![Screenshot from 2023-06-30 09-44-56](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/47d1ef61-97b9-4d2f-9bd2-035745329996)

**Comment by tcompa** [comment]
Well, I now notice that the prereleases are not sorted correctly, but at least the release vs prerelease order is correct.

**Comment by tcompa** [comment]
Main issue identified, with @rkpasia: Python uses PEP 440 to define versions, which differs from SemVer. The two specs are compatible for standard releases, but not for prereleases.
We are now looking through a few options, including using https://github.com/renovatebot/pep440/tree/main or possibly writing a little bit of custom parsing. More on this soon.

**Comment by tcompa** [comment]
As mentioned https://github.com/fractal-analytics-platform/fractal-web/issues/149#issuecomment-1614329655, PEP 440 (naming convention for Python packages) and SemVer are not fully compatible, and this is very clear for prereleases.

# Working solution

A first solution is to use the `loose` option of the semver package:
> loose
> Be more forgiving about not-quite-valid semver strings. (Any resulting output will always be 100% strict compliant, of course.)
> [https://github.com/npm/node-semver]

See also https://github.com/npm/node-semver/blob/main/internal/re.js:
```js

// ## Full Version String
// A main version, followed optionally by a pre-release version and
// build metadata.

// Note that the only major, minor, patch, and pre-release sections of
// the version string are capturing groups.  The build metadata is not a
// capturing group, because it should not ever be used in version
// comparison.

createToken('FULLPLAIN', `v?${src[t.MAINVERSION]
}${src[t.PRERELEASE]}?${
  src[t.BUILD]}?`)

createToken('FULL', `^${src[t.FULLPLAIN]}$`)

// like full, but allows v1.2.3 and =1.2.3, which people do sometimes.
// also, 1.0.0alpha1 (prerelease without the hyphen) which is pretty
// common in the npm registry.
createToken('LOOSEPLAIN', `[v=\\s]*${src[t.MAINVERSIONLOOSE]
}${src[t.PRERELEASELOOSE]}?${
  src[t.BUILD]}?`)

createToken('LOOSE', `^${src[t.LOOSEPLAIN]}$`)
```

To make sure that this works, the following script
```js
var semver = require("semver")

versionStringPre = "0.9.0"
versionString0a0 = "0.10.0a0"
versionString0a1 = "0.10.0a1"
versionString0 = "0.10.0"
versionStringPost = "0.11.0"

console.log("Is", versionString0a0, "valid?",  semver.valid(versionString0a0));
console.log("Is", versionString0a1, "valid?",  semver.valid(versionString0a1));
console.log("Is", versionString0, "valid?",  semver.valid(versionString0));
console.log();

versionPre = semver.valid(versionStringPre, {"loose": true, "includePrerelease": true})
version0a0 = semver.valid(versionString0a0, {"loose": true, "includePrerelease": true})
version0a1 = semver.valid(versionString0a1, {"loose": true, "includePrerelease": true})
version0 = semver.valid(versionString0, {"loose": true, "includePrerelease": true})
versionPost = semver.valid(versionStringPost, {"loose": true, "includePrerelease": true})

console.log(versionStringPre, "validated as", versionPre);
console.log(versionString0a0, "validated as", version0a0);
console.log(versionString0a1, "validated as", version0a1);
console.log(versionString0, "validated as", version0);
console.log(versionStringPost, "validated as", versionPost);
console.log();

console.assert(semver.lt(versionPre, version0a0), "ERROR");
console.assert(semver.lt(version0a0, version0a1), "ERROR");
console.assert(semver.lt(version0a1, version0), "ERROR");
console.assert(semver.lt(version0, versionPost), "ERROR");
```
goes through correctly, and its output is
```
Is 0.10.0a0 valid? null
Is 0.10.0a1 valid? null
Is 0.10.0 valid? 0.10.0

0.9.0 validated as 0.9.0
0.10.0a0 validated as 0.10.0-a0
0.10.0a1 validated as 0.10.0-a1
0.10.0 validated as 0.10.0
0.11.0 validated as 0.11.0
```

# A caveat

There's of course a bit of risk in relying on the "loose" option, since it's not defined as part of a spec and I cannot say whether this will change in future versions of the npm semver package.
However:
1. This logic will never touch the DB, but will only be used to sort tasks in a list. If sorting fails badly, it does not constitute a severe failure;
2. We can include multiple tests for expected behaviors, based on PEP440-compliant version strings. This means that we ever update semver to the next version and they changed their "loose" definition, we should be able to catch this in the CI. I'll prepare a list of expected behaviors below.

**Comment by jluethi** [comment]
Sounds good! :)

**Comment by tcompa** [comment]
Here is a reasonable test
```js
var semver = require("semver")
var assert = require('assert');

cases = [
    ["0.10.0a0", "0.10.0-a0"],
    ["0.10.0a2", "0.10.0-a2"],
    ["0.10.0alpha0", "0.10.0-alpha0"],
    ["0.10.0alpha3", "0.10.0-alpha3"],
    ["0.10.0b4", "0.10.0-b4"],
    ["0.10.0beta5", "0.10.0-beta5"],
    ["0.10.0c0", "0.10.0-c0"],
    ["1.0.0rc4.dev7", "1.0.0-rc4.dev7"]
]

let ind = 0;
while (ind < cases.length) {

    // Assign variables
    versionRawPEP440 = cases[ind][0];
    versionRawSemVer = cases[ind][1];
    console.log("Raw version strings:", versionRawPEP440, "and", versionRawSemVer);

    // Preliminary check: versionRawSemVer is indeed SemVer-compliant (with no need for loose)
    assert.equal(semver.valid(versionRawSemVer), versionRawSemVer)

    // Loosely construct the two semver strings
    versionPEP440 = semver.valid(versionRawPEP440, {"loose": true, "includePrerelease": true});
    versionSemVer = semver.valid(versionRawSemVer, {"loose": true, "includePrerelease": true});
    console.log("Loosely-validated version strings:", versionPEP440, "and", versionSemVer);

    // Check the expected behaviors
    assert.equal(versionPEP440, versionSemVer)
    console.log("OK.");

    ind++;
}
```

**Comment by rkpasia** [comment]
Sorry, closed by error.
