### ISSUE TITLE
Evaluate other JSON-schema-form packages

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#152]
We should check at least two categories of existing tools:
1. Svelte ready-to-use form generators, like:
    * https://github.com/xpluscal/svelte-schemaform (see demo [here](https://xpluscal.github.io/svelte-schemaform/)). This is a svelte port of a (more mature) [package for react](https://github.com/rjsf-team/react-jsonschema-form).
    * https://github.com/restspace/svelte-schema-form
2. Pure-JS packages to handle at least some of the low-level operations (e.g. validation).

Maybe we won't end up using any of those, but let's at least take inspiration on how they do things.

**Comment by tcompa** [comment]
Since this came up during the discussion with @rkpasia, let's also try to properly define what JSON Schema protocol we are considering. The relevant bit of pydantic v1 docs is in [this page](https://docs.pydantic.dev/latest/usage/schema/):
> The generated schemas are compliant with the specifications: [JSON Schema Core](https://json-schema.org/latest/json-schema-core.html), [JSON Schema Validation](https://json-schema.org/latest/json-schema-validation.html) and[OpenAPI](https://github.com/OAI/OpenAPI-Specification).

**Comment by tcompa** [comment]
For the record, here are a couple of examples from the playground of react-jsonschema-form, using some of our example schemas:

![Screenshot from 2023-05-25 08-59-07](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/b1ea1c38-f155-4f58-9557-01827d83db33)

![Screenshot from 2023-05-25 08-55-28](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/9901c6b5-842d-417f-9a72-d13e870bd09f)

**Comment by rkpasia** [comment]
This library seems pretty usable to iterate through a JSON Schema, even referencing different drafts version of JSON Schema spec.

https://github.com/sagold/json-schema-library

**Comment by tcompa** [comment]
> This library seems pretty usable to iterate through a JSON Schema, even referencing different drafts version of JSON Schema spec.
> 
> https://github.com/sagold/json-schema-library

From their README:
> This library currently supports draft4, draft6 and draft7 features [@see benchmark](https://github.com/sagold/json-schema-benchmark)"

This could be a problem if we need to use JSON Schema 2020-12 (see https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/375). But maybe that is already supported (see e.g. https://github.com/sagold/json-schema-library/blob/b8b9055459393e2869116160e51117d20bd43c8f/test/getDraftTests.ts#L29)? To be clarified (or asked directly).

**Comment by tcompa** [comment]
For the record, a validation package like https://www.npmjs.com/package/ajv supports JSON Schema draft-04/06/07/2019-09/2020-12 (and it depends on https://github.com/epoberezkin/json-schema-traverse).

**Comment by tcompa** [comment]
For the record:
* https://github.com/sagold/json-schema-library/issues/37

**Comment by tcompa** [comment]
We are currently heading towards ajv. More on this soon.

**Comment by rkpasia** [comment]
I think that a decision on this matter has been taken.
Closing it, if further discussion is required, we'll reopen it.
