### ISSUE TITLE
Definition of a Svelte component structure to handle a JSON Schema

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#154]
A svelte component structure shall consider the followings:

- [x] #82
- [x] #152 

The UI shall generate a form structure that enables user interaction and value-input that is restricted to the given schema definition.

Some requirements for the HTML dom structure:
- [x] input shall reflect the argument type (number, string, boolean)
- [ ] #183
- [x] a dynamic input structure shall be generated for array arguments
- [x] a dynamic arguments structure shall be generated for object arguments
- [x] a nestable structure of argument types must be supported (eg. a list of a list, an object with multiple properties that are a list, an object that has a property which is a list of other objects, [...])

**Comment by tcompa** [comment]
Closing, with part of this issue deferred to https://github.com/fractal-analytics-platform/fractal-web/issues/183.
