### ISSUE TITLE
Also show job logs while the job is running, not only when it is over

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#179]

**Comment by jluethi** [comment]
Big fan of this! Would make some basic monitoring much easier than always checking the cluster or the actual log folder.

**Comment by tcompa** [comment]
This needs to be defined better, to decide which endpoint to use.

**Comment by jluethi** [comment]
My goal here would be that we see the subset of this log (the workflow.log) while the job is running

<img width="1264" alt="Screenshot 2023-12-20 at 15 05 31" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/aae8be9d-ddcd-4828-a948-b6721703da33">

**Comment by tcompa** [comment]
Note: this requires https://github.com/fractal-analytics-platform/fractal-server/issues/1211 (or an equivalent fractal-server update). Then the change in fractal-web will be quite simple (re-activating the button, and possibly including the required opt-in query parameter).

**Comment by tcompa** [comment]
Now available, as of fractal-server v1.4.4, with a new `show_tmp_logs` boolean query parameter for `/api/v1/project/{project_id}/job/{job_id}/` (see [PR 1216](https://github.com/fractal-analytics-platform/fractal-server/pull/1216/files)).

**Comment by zonia3000** [comment]
I think we should add this parameter also to the `GET /admin/job/` endpoint, to allow the admin to retrieve the running log of other users.

**Comment by tcompa** [comment]
> I think we should add this parameter also to the `GET /admin/job/` endpoint, to allow the admin to retrieve the running log of other users.

Agreed.
cc @ychiucco

**Comment by zonia3000** [comment]
Maybe it is better to have a new endpoint `GET /admin/job/{job.id}`, to avoid implementing the reading of multiple files when we need that only to load a single job log.

**Comment by zonia3000** [comment]
Another question. Is the log download supported only for `done` or `failed` jobs?

I'm talking about these 2 endpoint:

* `/api/v1/project/${project.id}/job/${job.id}/download`
* `/api/admin/job/${job.id}/download`

**Comment by zonia3000** [comment]
No, it looks ok. I just wanted to be sure that I have to enable the download button also for running jobs. Thanks.
