### ISSUE TITLE
Integrate additional JSON Schema constraints (e.g. min, max, max length)

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#183]
Be aware that some values defined by the schema could have restrictions as specified by the properties in the title.

It is currently not required by the client to highlight those restrictions/requirements as a mean of UI state validations or complex UI interactions that could happen with the user.

The client as a whole is already compliant with those restrictions thanks to the AJV validations.

**Comment by tcompa** [comment]
There are a bunch of JSON Schema options that we are not including in the prompts (e.g. the number of items in a list, or the min/max values of a scalar), but we'll always catch during validation - see also #177.

Later on, we can include the relevant ones (e.g. enum, and probably also max length) directly in the prompts, to help the user.
