### ISSUE TITLE
Trigger a task collection from tasks page

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#20]
An user, from the tasks page, shall be able to trigger a task collection.

The client shall keep track of the collection process that is happening server-side.

The objective is to notify the user if the collection of the task has completed or there has been an error. If such error exists, show its details.

Issue references: #7

**Comment by rkpasia** [comment]
The status of the ongoing collection task can be retrieved from the response within the `data` property in the nested `status` property.

**Comment by tcompa** [comment]
Relevant values for `status`:
* `"installing"`
* `"collecting"`
* `"OK"`
* `"fail"` -> in this case we should offer the option to view logs, which are available in the `log` property (which is nested in `data` - like `status`). Logs are a multi-line string, which could also be a bit long (several tens of lines).

**Comment by tcompa** [comment]
A minor comment concerning the task page structure:
Let's make it look a bit more structured, with titles/headers for the three sections. Provisional (very verbose) names could be something like:
1. "Collect tasks from a package"
2. "Add a single task by hand"
3. "Task list"
