### ISSUE TITLE
Make "Import workflow" look like a button

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#200]

**Comment by tcompa** [comment]
See
![Screenshot from 2023-06-22 08-42-51](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/863e8e77-904c-4a53-be8f-914dc8fd45ce)

**Comment by jluethi** [comment]
+1 on that. Also, can we move it to the right then? And "Create workflow" could then become "Create new workflow"
