### ISSUE TITLE
Handle empty-input for number arguments

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#203]
Given
```json
{
  "additionalProperties": false,
  "properties": {
    "sleep_time": {
      "description": "Interval to sleep, in seconds.",
      "title": "Sleep Time",
      "type": "integer"
    }
  },
  "required": [],
  "title": "DummyParallel",
  "type": "object"
}
```

1. An optional number parameter `sleep_time` (with no default).
2. No explicit setting of `sleep_time` via `args.
3. Upon the first GET, fractal-web receives `args` with no `sleep_time` in there.
4. Input field in the form is empty, and user can write in there.
5. User sets `sleep_time=123`, and saves.
6. PATCH sends `args={"sleep_time":123}`
7. New GET will give back `args={"sleep_time":123}`
8. Input field in the form shows `123`, and user can modify it
9. User deletes `123` (**EXPECTED BEHAVIOR: this sets `sleep_time=null`**)
10. User saves, and fractal-web (A) remove null values (including sleep_time), (B) successfully validates with AJV, (c) make PATCH call.

To-do:
- [x] Verify the expected behavior described in point 9.

**Comment by rkpasia** [comment]
Already checked and tested.

Closing
