### ISSUE TITLE
Maybe give feedback when args "save" goes through

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#207]
Especially when one tries the new args-schema component for the first time, a user will for sure fail to save for several possible reasons. After each attempt, one goes back to modify the values. At some point, after N failed attempts, one goes through. I think it'd be useful to display something like a "Arguments updated correctly" green message on top of the component, at least for a small time interval.

Low priority, and open to different suggestions.

**Comment by jluethi** [comment]
I'll have to play with the interface myself to get a feeling for this. One feedback that should already be there is that the save button becomes unclickable after successful save. Maybe that's enough?

**Comment by tcompa** [comment]
> One feedback that should already be there

It is already there, indeed.

In the current style the save-button style change is not very visible, hence this issue. But I agree: a clear style change for the "save" button will be enough.
