### ISSUE TITLE
Trying development branch: `sh: vite: command not found`

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#21]
@tcompa I've tried to follow your instructions on how to run fractal-web locally.

When calling `npm run dev -- --open`, I get:
```
> fractal-app@0.0.1 dev
> vite dev --open

sh: vite: command not found
```

I added a `npm install vite`, then I could launch the fractal-web successfully :)

**Comment by tcompa** [comment]
Thanks. This (and another small bug) should be fixed by https://github.com/fractal-analytics-platform/fractal-web/commit/9df3cf64f0787d8e3f36b5e34701abe87bd99f49. Let us know whether the current instructions do work.
