### ISSUE TITLE
Fix "discard changes"  behavior

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#212]
(tested with 216d4ce77538c58f9e6ac68d095f12d468f0f354)

* Add argument to list
* Save (successfully)
* The item is correctly shown
* Click "reset arguments"
* The item is not shown any more

This differs from my expectation. I think that "reset" should mean "reset to whatever is available in the server, or to whatever was there before my latest post-save changes".
What I guess is happening is that we are resetting to what was there "when we started interacting", and it does not take into account that some changes were already saved.

---

EDIT: the other part of the issue is now in #215

**Comment by jluethi** [comment]
👍🏻

We want "discard changes" to be part of the current scope
"Reset parameters" (i.e. go back to the defaults of the schema) can be a nice feature at some later time :)
