### ISSUE TITLE
At FMI deployment, can't get `node build` approach to work

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#217]
Just so we have some record on these issues, let's track things here. Not blocking for 1.3.0 support.

When running ec95a36081a9c86b292f33d9b260818476b5e517, I can get Fractal web to work correctly if I launch it as `npm run dev`.

If instead, I run `npm run build` and then `PORT=5174 ORIGIN=localhost node build`, going to the Fractal-web page shows `Invalid request body` and trying to load the main page just via wget results in `ERROR 400: Bad Request.`

**Comment by tcompa** [comment]
Closed with 5942a2b200bb675b952cd00095b71d2d9d0d15b7.
