### ISSUE TITLE
On Macs, fractal-web only works when fractal-server is started with `fractalctl start --host '::'`

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#222]
See Slack conversation.

When I start the server with the usual `server_config_and_start.sh` script (see below) and the start fractal-web normally (see .env.development below) by calling `npm run dev -- --open`, I get the following error:
```
Error loading server info
TypeError: fetch failed
    at fetch (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/node_modules/undici/index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.eval [as fetch] (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:32:10)
    at async load (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/src/routes/+layout.server.js:12:21)
    at async Module.load_server_data (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:49:17)
    at async eval (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13) {
  cause: Error: connect ECONNREFUSED ::1:8010
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 8010
  }
}
Error loading user info
TypeError: fetch failed
    at fetch (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/node_modules/undici/index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.eval [as fetch] (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:32:10)
    at async Module.whoami (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/src/lib/server/api/v1/auth_api.js:34:19)
    at async load (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/src/routes/+layout.server.js:36:19)
    at async Module.load_server_data (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:49:17)
    at async eval (/Users/joel/Dropbox/Joel/FMI/Code/130_fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13) {
  cause: Error: connect ECONNREFUSED ::1:8010
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 8010
  }
}
```
Also, no fractal-server version is shown in fractal-web.

If I start fractal server with `fractalctl start --host '::'`, then the server is running on port 8000 and everything is working for Fractal-web. This didn't use to be the case in the 1.2.5 branches and also in the fractal web main version ~ 1 week ago.

If I set the port to 8000 in the script, it still fails the same way, so that's not simply a port question.

-------

server_config_and_start.sh script:
```
#!/bin/bash

PORT=8010

# Create an empty db
rm -fr db
mkdir db
export SQLITE_PATH=db/fractal_server.db
fractalctl set-db

# Remove old stuff
rm -fr FRACTAL_TASKS_DIR
rm -r artifacts

# Set environment variables
FRACTAL_TASKS_DIR=`pwd`/FRACTAL_TASKS_DIR
echo -e "\
DEPLOYMENT_TYPE=testing
JWT_SECRET_KEY=secret
SQLITE_PATH=db/fractal_server.db
FRACTAL_TASKS_DIR=${FRACTAL_TASKS_DIR}
FRACTAL_LOGGING_LEVEL=20
FRACTAL_RUNNER_BACKEND=local
FRACTAL_RUNNER_WORKING_BASE_DIR=artifacts
FRACTAL_SLURM_CONFIG_FILE=config_uzh.json
FRACTAL_ADMIN_DEFAULT_EMAIL=admin@fractal.xy
FRACTAL_ADMIN_DEFAULT_PASSWORD=1234
" > .fractal_server.env


# Start the server
fractalctl start --port $PORT
```

.env.development: (changed port between 8010 for the script above and 8000 when started with `fractalctl start --host '::'`)
```
FRACTAL_SERVER_HOST=http://localhost:8010

# AUTH COOKIE
AUTH_COOKIE_NAME=fastapiusersauth
AUTH_COOKIE_SECURE=false
AUTH_COOKIE_DOMAIN=localhost
AUTH_COOKIE_PATH=/
AUTH_COOKIE_MAX_AGE=1800
AUTH_COOKIE_SAME_SITE=lax
AUTH_COOKIE_HTTP_ONLY=true
```

**Comment by jluethi** [comment]
One suspicious (but potentially unrelated) thing was that I got this pop-up when I first ran the server via `fractalctl start --host '::'`. Not sure if it's related though. As said, everything used to run fine on this same machine last week with fractal-web.

![Screenshot 2023-06-26 at 12 16 51](https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/3a73a9fd-20dd-4e06-88af-70830b227257)

**Comment by jluethi** [comment]
Another big different is that the server says this when run as `fractalctl start --host '::'` :
```
Uvicorn running on http://[::]:8000 (Press CTRL+C to quit)
```
instead of 
```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

When run with the normal script

**Comment by rkpasia** [comment]
So there is a thing to understand in this `::` / `127.0.0.1` configuration, and more info could be taken from [this](https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost) source.

> `127.0.0.1` is normally the IP address assigned to the "loopback" or *local-only interface*. This is a "fake" network adapter that can only communicate within the same host. It's often used when you want a network-capable application to only serve clients on the same host. A process that is listening on `127.0.0.1` for connections will only receive local connections on that socket.

> `0.0.0.0` has a couple of different meanings, but in this context, when a server is told to listen on `0.0.0.0` that means "listen on every available network interface". The loopback adapter with IP address `127.0.0.1` from the perspective of the server process looks just like any other network adapter on the machine, so a server told to listen on `0.0.0.0` will accept connections on that interface too.

Since the nodejs server that is handling the SSR (server-side-rendering) of svelte is basically a proxy server (we send HTTP requests to the fractal server through the node server) we need to match hostnames in order for the cookies to be valid through the whole network routing.

That is, we need the browser to accept cookies from the `localhost` hostname, because it's the same hostname in which the nodejs server is running (`localhost:5173` by default). On the other hand, we need the fractal server to accept cookies from incoming requests that have *the same* hostname of the server (the fractal server).
If we run the process of fractal server with, say, hostname `127.0.0.1` (that is not equal to `localhost`) the incoming requests with the cookie payload that has a `domain` property equal to `localhost` would be ignored. This means that the server would not accept the request and threat it as `401 Unauthorized`.

In order for the nodejs server, the browser, the fractal server to be "in-sync" with domain names, each of them should have a common hostname, which is `localhost`.
As stated previously, starting the fractalserver with `::` would allow to reach this situation, because would solve correctly the DNS at `localhost:XXXX` to route requests to the server, plus sharing the localhost domain as accepted domain to get the cookies from.

**Comment by rkpasia** [comment]
This situation does not apply to production because the dame domain it's already shared by the servers (as far as I know of the network configuration of the lab).
The previous allows the cookies to be accepted in each three contexts: the browser, the nodejs server and the fractal server.

**Comment by rkpasia** [comment]
For the same reason as explained before, you could also start the fractal process with this configuration:

```fractalctl start --host 'localhost'```

The previous would solve this issue anyway.

**Comment by rkpasia** [comment]
It is possibile to update the startup script as follows:

```
# [server_config_and_start.sh]
#!/bin/bash

PORT=8010
HOST=localhost

# Create an empty db
rm -fr db
mkdir db
export SQLITE_PATH=db/fractal_server.db
fractalctl set-db

# Remove old stuff
rm -fr FRACTAL_TASKS_DIR
rm -r artifacts

# Set environment variables
FRACTAL_TASKS_DIR=`pwd`/FRACTAL_TASKS_DIR
echo -e "\
DEPLOYMENT_TYPE=testing
JWT_SECRET_KEY=secret
SQLITE_PATH=db/fractal_server.db
FRACTAL_TASKS_DIR=${FRACTAL_TASKS_DIR}
FRACTAL_LOGGING_LEVEL=20
FRACTAL_RUNNER_BACKEND=local
FRACTAL_RUNNER_WORKING_BASE_DIR=artifacts
FRACTAL_SLURM_CONFIG_FILE=config_uzh.json
FRACTAL_ADMIN_DEFAULT_EMAIL=admin@fractal.xy
FRACTAL_ADMIN_DEFAULT_PASSWORD=1234
" > .fractal_server.env


# Start the server
fractalctl start --port $PORT --host $HOST
```

**Comment by jluethi** [comment]
Thanks a lot @rkpasia for those explanations. I understand some of it, not sure I fully understand which part here I had wrong before (I felt we tried all those options, but must have missed something). But good to know that we should be setting everything to localhost as the correct way of going about this, not setting it as e.g. `127.0.0.1`.

Now using the example script above and then setting .env.development to this:

```
FRACTAL_SERVER_HOST=http://localhost:8010

# AUTH COOKIE
AUTH_COOKIE_NAME=fastapiusersauth
AUTH_COOKIE_SECURE=false
AUTH_COOKIE_DOMAIN=localhost
AUTH_COOKIE_PATH=/
AUTH_COOKIE_MAX_AGE=1800
AUTH_COOKIE_SAME_SITE=lax
AUTH_COOKIE_HTTP_ONLY=true
```

I can successfully start the fractal server running `npm run dev -- --open`.

@tcompa Do we want to adapt our `server_config_and_start.sh` script to this or do you see downsides? Besides adding back the `JWT_EXPIRE_SECONDS=84600`. It looks to be working robustly for me now and the configuration above is what is already in the fractal-web repo (except for the port)

**Comment by tcompa** [comment]
> @tcompa Do we want to adapt our server_config_and_start.sh script to this or do you see downsides? Besides adding back the JWT_EXPIRE_SECONDS=84600. It looks to be working robustly for me now and the configuration above is what is already in the fractal-web repo (except for the port)

Do you refer to including `--host` in the fractal-demos scripts?
I see no downside at all.

I've now fixed it with https://github.com/fractal-analytics-platform/fractal-demos/commit/ac689d5ba76253c050c99f3900f5ee03b4f4a701, please let me know if it matches with the one that works for you.
For the record, it does work for me locally on Ubuntu 22: I can startup fractal-server, I can interact via CLI client, I can login and interact via web client.

**Comment by tcompa** [comment]
> I can successfully start the fractal server running npm run dev -- --open.

Great, then we can close this one.

Feel free to also test the `node` startup, if/when you have time, although it doesn't have special benefits if the goal is to test new features locally.

**Comment by jluethi** [comment]
> please let me know if it matches with the one that works for you.

Looks good!

> Feel free to also test the node startup

What's the recommended node startup command regarding ORIGIN and such?

With `PROTOCOL_HEADER=x-forwarded-proto HOST_HEADER=x-forwarded-host ORIGIN=http://localhost PORT=5173 node build`, I run into a `Cross-site POST form submissions are forbidden`

**Comment by tcompa** [comment]
> With `PROTOCOL_HEADER=x-forwarded-proto HOST_HEADER=x-forwarded-host ORIGIN=http://localhost PORT=5173 node build`, I run into a `Cross-site POST form submissions are forbidden`

This should be fixed by using
```
PROTOCOL_HEADER=x-forwarded-proto HOST_HEADER=x-forwarded-host ORIGIN=http://localhost:5173 PORT=5173 node build
```
(note that the port is both in the PORT and ORIGIN variables)

**Comment by tcompa** [comment]
> This should be fixed by using ...

Now fixed in fractal-demos as well: https://github.com/fractal-analytics-platform/fractal-demos/commit/4bdb817f92b1104c8f13859f170b914805024523. Let me know if it does work for you.

**Comment by jluethi** [comment]
Thanks, can confirm that this works!
