### ISSUE TITLE
Convert timestamps from UTC?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#229]
We are showing timestamp as computed by fractal-server, that is, in UTC.
I'd say we should convert them to the browser local timezone, to avoid confusion for the user.

**Comment by tcompa** [comment]
I actually noticed that this is in principle already covered in `src/lib/components/jobs/TimestampBadge.svelte`:
```svelte
<script>
	export let timestamp;
</script>

<span>
	{timestamp ? new Date(timestamp).toLocaleString() : 'No timestamp'}
</span>
```

Maybe the glitch is due to a wrong configuration of my browser/OS timezone. I'll check further.

**Comment by jluethi** [comment]
@tcompa I just tested this on my end and the timestamps in the project page are showing the correct local time :) Are there other time stamps that should be checked?

**Comment by tcompa** [comment]
> @tcompa I just tested this on my end and the timestamps in the project page are showing the correct local time :) Are there other time stamps that should be checked?

Thanks, then it should be a glitch on my side.

There are timestamps associated to:
* Jobs (in any job-list page)
* Task-collection (in the main tasks page)

**Comment by jluethi** [comment]
Hmm, it's different for me depending on the deployment. On the FMI deployment, the correct time is shown on the job pages. For a local deployment, I get UTC time shown (both on the job page and the task collection), even though my computer is running on UTC + 2h.

**Comment by zonia3000** [comment]
`toLocaleString()` is not working as expected because the date returned by fractal-sever doesn't follow [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard, which requires to put a `Z` at the end of the string to represent a date in UTC. I think we should fix this on fractal-server side.

On my browser:

```javascript
new Date('2023-12-20T09:49:27.914030').toLocaleString() // "12/20/2023, 9:49:27 AM"
new Date('2023-12-20T09:49:27.914030Z').toLocaleString() // "12/20/2023, 10:49:27 AM"
```

**Comment by zonia3000** [comment]
> Does the snippet above correspond to the time strings that you are actually getting from `fractal-server`?

Yes, the first string included in the snippet is the actual fractal-server response.

> we would expect e.g. that a GET-job endpoint response includes this sort of property:
> 
> ```json
>             'start_timestamp': '2023-12-20T15:13:16.457723+00:00',
> ```
> 
> (this still has `+00:00` rather than `Z`, but at least it is time-zone-aware)

Also this version seems to work fine:

```javascript
new Date('2023-12-20T15:13:16.457723+00:00').toLocaleString() // 12/20/2023, 4:13:16 PM
```

**Comment by tcompa** [comment]
Closing this issue, as it's addressed in
* #400 
* https://github.com/fractal-analytics-platform/fractal-server/pull/1186

**Comment by tcompa** [comment]
For the record,

> Hmm, it's different for me depending on the deployment. On the FMI deployment, the correct time is shown on the job pages. For a local deployment, I get UTC time shown (both on the job page and the task collection), even though my computer is running on UTC + 2h.

The likely reason for this behavior was that the local deployment was based on sqlite (I guess). In that case, even without fully reproducing the issue, it is definitely expected that fractal-server < 1.4.3 was not providing a correct handling of timezones.

**Comment by jluethi** [comment]
That makes sense, thanks!
