### ISSUE TITLE
Don't allow users to leave a workflow task page with unsaved changes

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#230]
See here for discussion and suggested behavior: https://github.com/fractal-analytics-platform/fractal-web/pull/228#issuecomment-1609196399

> I just noticed that we let users leave the page after they made un-saved edits and, if they return, their changes are discarded.
> 
> If we enforce a save or discard decision (as sketched in the figma board here: https://www.figma.com/file/RAivaBmlX8yzu7aEAwrxaX/Fractal-UI-Board?type=whiteboard&node-id=258-488&t=OKUQpf7TvG5XlVhh-0)
> <img width="762" alt="Screenshot 2023-06-27 at 12 05 58" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/efbe1497-044a-49aa-81f5-ac268508a498">
> 

I think this is a priority issue. Will avoid a lot of user confusion + allow to place the save buttons at the bottom, thus making some space (see https://github.com/fractal-analytics-platform/fractal-web/pull/228)

**Comment by tcompa** [comment]
I think the same logic should apply to "run workflow": it should not be possible to do it before saving/discarding updates.

**Comment by jluethi** [comment]
Agreed, just ran into this today and wanted to open an issue for it 😅
