### ISSUE TITLE
`crypto.randomUUID` not available outside secure context

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#231]
## Description of the issue

We do use `randomUUID()` in https://github.com/fractal-analytics-platform/fractal-web/blob/0870210a7b166fd7adbf731cf14b4a5bd9893f46/src/lib/components/common/jschema/PropertyDiscriminator.svelte#L10
but this function is only available in a secure context:
> ### Crypto: randomUUID() method
> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID#browser_compatibility).
> (https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)

For this reason, when we do not use an https protocol, we hit an error like "crypto.randomUUID is not a function" in the browser console.

Side note: running on localhost is typically treated as a secure context, which should explain why our usual tests did not flag this error.

## Expected behavior
fractal-web should also work outside a secure context, meaning that we should use a different function to create that key.

**Comment by jluethi** [comment]
Can confirm that this is solved with #232 , looks like UZH deployment is also working well now! 🎉
