### ISSUE TITLE
Review dependencies

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#236]
```json
    "dependencies": {
        "@vincjo/datatables": "^1.6.0",
        "ajv": "^8.12.0",
        "jose": "^4.14.4",
        "json-schema-traverse": "^1.0.0",
        "sweetalert2": "^11.4.8"
    }
```

@rkpasia did we end up using `json-schema-traverse`, or is it not needed?
Also: do we use `sweetalert2`?

**Comment by rkpasia** [comment]
This unfortunately is a leftover of previous changes that were not applied to the project in the end.
Don't know how it manage to get committed unfortunately.
I'll remove it now.
We are not dependent on these packages by any mean.

**Comment by rkpasia** [comment]
We're also not dependent on `sweetalert2`.

**Comment by rkpasia** [comment]
Sweetalert has been introduced here 5c01dbd289aebfeebeb81e239c0366085e6446f0
