### ISSUE TITLE
Add search box to "insert task" modal

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#238]
This bug has been identified while working on #149.
Slim-Select search box feature is conflicting with `focusin` event of bootstrap `event-handler.js`

Unfortunately the search box within the dropdown select menu of `slim-select` has `focusin` event prevented because it seems to be intercepted by the modal component of bootstrap.

I can't figure out a solution on this matter right now.

**Comment by jluethi** [comment]
Ok, too bad. Then will add a search feature later on :)

**Comment by rkpasia** [comment]
More on this:

Removing the `.modal-dialog` div element from within the `.modal` div container seem to enable the editing of `input` element of search box managed by _slim-select_. 

Unfortunately, removing the `.modal-dialog` element prevents the closing feature of the dialog itself. This results in a dialog which is not possibile to be dismissed.
Dismissing the modal is not even possible through a programmatic event via javascript's bootstrap apis.

**Comment by jluethi** [comment]
With the new task modal of common vs. user-specific tasks: It would be best if the search can find task in either.
One idea: A third tab for task search that searches all of them?

**Comment by zonia3000** [comment]
As reported in https://github.com/brianvoe/slim-select/issues/475#issuecomment-1736440245, the incompatibility with bootstrap modal can be fixed adding `data-bs-focus="false"` to the modal, so we are currently using the slim-select search inside task selection:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/534f9adc-c696-4f1a-b744-8a1463a61142)

**Comment by jluethi** [comment]
Oh, looks very promising, will have to test this! :)
