### ISSUE TITLE
Release v0.2

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#24]
- [x] #38
- [x] #53 
- [x] #59

**Comment by tcompa** [comment]
Single-project page (..../<project_id>/... ) with two tables:
* Dataset list (showing name and type attributes), with "open/delete" options ["open" either in the same component or in a new page]
* Workflow list (id, name), with "open/delete" options
* Feature to create new (empty) workflow
* Import workflow from file [low priority]

Single-dataset page (..../project/<project_id>/dataset/<dataset_id>/...):
* Edit dataset attributes (only `name`, `type` or `read_only`)
* View table with list of resources of that dataset (with "remove" button for each resource)
* Form for adding a new resource to the dataset (NOTE: starting from fractal-server>=1.1.0a0, the "resource" table only has a single "path" column)

Single-workflow page (..../project/<project_id>/workflow/<workflow_id>/... ):
* Feature to add new WorkflowTasks to the list
* List of WorkflowTasks, with "open/edit/delete" options
* "edit" option for a given WorkflowTask should include the association to one of the existing Tasks.
* Button to export workflow to file [low priority]

**Comment by rkpasia** [comment]
I think that this could be closed?
