### ISSUE TITLE
Revamp Home page and remove Info page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#243]
The current Homepage may be dropped as part of https://github.com/fractal-analytics-platform/fractal-web/issues/242.
I'd be in favor of keeping an "Info" page, with a small (one-paragraph) description of what the user may want to do, or where to get support. Or, otherwise, we can simply drop the "info" page.

**Comment by jluethi** [comment]
Good idea, I'd be in favor of that.

Contents for the page:
- Links to all relevant documentation
- Links to the splash page (like the one in bottom left)
- Some extra explanation text that can be set per deployment (i.e. giving a different text on billing, a different support link or email depending on institution)

**Comment by tcompa** [comment]
Recap (also merging #242 into this issue):

1. As soon as a user is logged-in, there should be a redirect towards the Projects page.
2. The Home and Info pages should be merged into a single page (I suggest to name it Home).
3. The Home page should be visible to anybody, not only logged users.
4. Remove Fractal organization page link and Fractal splash page link from the footer; I guess there is no reason to always show them, and it's enough to show them in the home page.
5. Should we also remove the fractal-server version from the footer, and only show it in the home page? For now, I'd be in favor of keeping it (maybe with a more explicit phrasing, like "fractal-server X.Y.Z").

Contents of the home page:
* A small (one-paragraph) description of typical actions the user may want to do. This includes a link to the login page, which should be made extremely visible.
* A sentence about where to get support (this has to be an env variable, since it may change for each Fractal instance).
* Links to relevant documentation pages, and to the Fractal splash page.
* Abything else?

**Comment by jluethi** [comment]
Sounds good!

> Should we also remove the fractal-server version from the footer, and only show it in the home page? For now, I'd be in favor of keeping it (maybe with a more explicit phrasing, like "fractal-server X.Y.Z").

Let's keep this at least for the time being, it's quite useful to see what version things run when we run into issues :)

> A sentence about where to get support (this has to be an env variable, since it may change for each Fractal instance).

Very nice!

> Anything else?

I think that should cover it for the moment :) We can eventually add the Fractal logo there, once we have one.
