### ISSUE TITLE
Enable importing/exporting single-WorkflowTask arguments as JSON

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#245]
### Feature
On top of having two alternative ways of setting task parameters (either via a JSON Schema form, or via a free form in case there is no available schema), we should expose the option to directly set all parameters from an existing JSON file (or otherwise from an existing JSON string to be copy-pasted into a text box - TBD which one is more useful).
Also the reverse should be possible ("view task parameters as a JSON string", or "export task parameters to a JSON file").

### Perspective
These two features, together, would enable a first straightforward way to transfer the task parameters from an "experimental" workflow to a "production" one. Note that, depending on how we will structure this kind of use flow, we may combine the export-and-then-import feature into a single "copy-these-parameters-to-a-task-of-another-workflow" feature/button. But we the straightforward implementation is useful to play around, and it could also always keep a relevant use case ("can you please send me by email the full JSON of those very cumbersome-to-set create-ome-zarr parameters?").

**Comment by zonia3000** [comment]
Should the export button allow to export arguments having pending changes? In that case, should we validate the arguments and deny the download if some fields are not valid?
Otherwise we can just let exporting the last saved arguments.

**Comment by zonia3000** [comment]
Ok, thanks. Discussing with @tcompa we are considering following approach:

* The export button is disabled if there are pending changes, so that the user is forced to save or discard before exporting
* The import button is always enabled but opens a modal dialog where the user can upload the JSON file and press a confirm button. The modal also contains a proper warning message saying that the operation will override all the arguments ignoring any pending changes.

**Comment by jluethi** [comment]
Sounds good!

**Comment by zonia3000** [comment]
Import and Export buttons are visible at the bottom of the arguments tab:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/7107a1e0-27cc-48fe-9d01-7b369c5d7b0b)

The export button simply downloads the file. The import button opens a modal:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/fb656977-17e8-4807-88a6-5c2d5b5d9ffe)

If the imported file is not valid the error appears directly inside the modal:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/2e665324-bebd-427b-b663-b9ff182eef9f)

**Comment by zonia3000** [comment]
Additional note. I've replaced the download icon on the top of the page.

This is the old one:

![vecchia-icona-upload](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/7ce15f48-b8cc-42de-9359-5b8fae9227d3)

This is the new one:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/e8571f66-eaa5-4e21-88be-43f7ff463573)

The download is usually represented by an arrow going down and the upload by an arrow going up. This convention is also used in the names of the Bootstrap icons.

**Comment by jluethi** [comment]
That's great! Good to have the download button have the right icon & looks great on the task import/export options! 🎉
