### ISSUE TITLE
Changing meta parameters of a parallel task leads to hidden 500 error

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#249]
When a user tries to update any meta parameter of a parallel task (=> not Create OME-Zarr structure, but e.g. Cellpose) in Fractal web or save a newly added meta parameter, we get a 500 internal server error showing up in the web console, but nothing shows up in Fractal web itself.
This error is quite confusing, because it's displayed as changed in the web interface and the error is not raised. Only when one reloads the workflow page does it realize that it wasn't updated. But switching back and forth between tasks shows the updated values.

We'd want:
1. Such errors to show up to the user.
2. Editing metadata for parallel tasks to actually be possible in Fractal web

The console error is the following:
```
start.d697be3d.js:1     PATCH https://fractal.mls.uzh.ch/projects/10/workflows/10/tasks/60 500 (Internal Server Error)
window.fetch @ start.d697be3d.js:1
Ll @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
u @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
n @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
(anonymous) @ index.1900b5a3.js:1
(anonymous) @ index.1900b5a3.js:1
b @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
(anonymous) @ index.1900b5a3.js:1
(anonymous) @ index.1900b5a3.js:1
b @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
(anonymous) @ index.1900b5a3.js:1
(anonymous) @ index.1900b5a3.js:1
v @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1 Update form entry response not ok
Ll @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
await in Ll (async)
u @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
n @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
(anonymous) @ index.1900b5a3.js:1
(anonymous) @ index.1900b5a3.js:1
b @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
(anonymous) @ index.1900b5a3.js:1
(anonymous) @ index.1900b5a3.js:1
b @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
(anonymous) @ index.1900b5a3.js:1
(anonymous) @ index.1900b5a3.js:1
v @ projects-_projectId_-workflows-_workflowId_-page.svelte.245d4f7f.js:1
```

On the web server side, we see the following:
```
Error: Invalid response from route /projects/10/workflows/10/tasks/59: handler should return a Response object
    at render_endpoint (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/server/index.js:1397:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/server/index.js:3789:22)
    at async Object.handle (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/server/chunks/hooks.server-b86ab63e.js:16:12)
    at async respond (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/server/index.js:3682:22)
    at async Array.ssr (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/handler.js:1207:3)
```

This does not happen for non-parallel tasks, e.g. for Create OME-Zarr structure. But when trying it for the Cellpose task or any other task that contains a parallelization_level that's set to something, it happens for all edits of any of the parameters.

No error shows up in the Fractal server logs

----

I also once saw this, not sure it's related and can't reproduce this error again:
```
Error: Not found: /slimselect.css.map
    at resolve (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/server/index.js:3809:18)
    at resolve (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/server/index.js:3684:34)
    at Object.handle (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/server/chunks/hooks.server-b86ab63e.js:16:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/server/index.js:3682:22)
    at async Array.ssr (file:///net/nfs4/pelkmanslab-fileserver-fractal/data/homes/fractal/20230627_joel_fractal/fractal-web/build/handler.js:1207:3)
```

cc @al-mcintyre for spotting this bug

**Comment by tcompa** [comment]
Here is one explanation:
* The current WorkflowTask's `meta` has `parallelization_level` set to something (e.g. `image`), together with `cpus_per_task` and `mem`.
* We modify some _other_ attribute of `meta`, e.g. we set `mem=99999`.
* The request body that is prepared for the fractal-server API includes a `meta` key with a value which is an object with all `meta` attributes: `cpus_per_task` (unchanged), `mem` (changed) and `parallelization_level` (unchanged).
* Since `parallelization_level` is part of the payload, the `WorkflowTaskUpdate` validator fails (see https://github.com/fractal-analytics-platform/fractal-common/blob/main/schemas/workflow.py).
* For some reason, this error is not shown correctly in fractal-web.

To-do:
- [ ] Fix the request body (only including attributes that actually changed) or its validation (we could also simply remove this constraint).
- [ ] Correctly propagate the error, which is currently not visible anywhere in fractal-web (it should say something like "Overriding task parallelization level currently not allowed").

**Comment by tcompa** [comment]
Fixed with #261 (additional tests are welcome).

**Comment by jluethi** [comment]
I can confirm that it now works as expected! :)

I was looking through the logs to see that everything was ok and saw this warning every time I switch between tasks:
was created with unknown prop 'saveChanges'`

Also, when loading the web interface, I see:
DevTools failed to load source map: Could not load content for http://localhost:5173/slimselect.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I don't remember seeing this before, but don't know whether it's related. I don't see anything failing and they are just warnings, just thought I'd report them.

**Comment by tcompa** [comment]
Thanks for these tests!
We just opened #266 for the `was created with unknown prop 'saveChanges'`, while the other error message (unrelated to recent commits) was already tracked in #258.
