### ISSUE TITLE
Correctly propagate fractal-server error (upon deleting a dataset that has been run in a job)

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#250]
When a user tries to delete a dataset which has already been used in a job, this fails server-side. See here for discussion of it: https://github.com/fractal-analytics-platform/fractal-server/issues/667

This is not displayed nicely in the web interface though. The actual interface just doesn't do anything, but also doesn't show the error. In the console, the following error shows up:
```
start.d697be3d.js:1     DELETE https://fractal.mls.uzh.ch/projects/1/datasets/2 500 (Internal Server Error)
window.fetch @ start.d697be3d.js:1
h @ projects-_projectId_-page.svelte.73b41b8d.js:1
y @ ConfirmActionButton.8aeb571e.js:1
projects-_projectId_-page.svelte.73b41b8d.js:1 Error while deleting dataset: The dataset was not deleted by the server
```

We'd want the user to see this error (or a nicer form of it) in the interface until it's actually possible to delete those datasets.

**Comment by jluethi** [comment]
cc @al-mcintyre for spotting this

**Comment by tcompa** [comment]
Thanks for reporting!

This could likelybe another case of https://github.com/fractal-analytics-platform/fractal-web/issues/249#issuecomment-1689865962. To check.

**Comment by tcompa** [comment]
> This could likely be another case of https://github.com/fractal-analytics-platform/fractal-web/issues/249#issuecomment-1689865962. To check.

I take it back.

It turns out this is "simpy" an instance of the broader issue #260, and in fact it works as expected in the in-progress PR #288.
