### ISSUE TITLE
Enable WorkflowTask Info tab and fill it in

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#252]
Each WorkflowTask has three tabs (on the right): Arguments, Meta, Info.

![Screenshot from 2023-08-22 13-47-34](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/2edc5ec6-4dff-4b7f-9b5b-5719b3ebaa17)

We should activate the Info tab, and fill it with some contents based on the attributes of `WorkflowTask.task`:
1. Task attributes `name`, `version`, `owner`, `source`,`input_type`, `output_type`;
2. `docs_info`: a string that contains a description of a task, often in markdown format (*);
3. `docs_link`: a link to an external web page with documentation.

(*) Let's start by including this string as a code block, and then we can make a step further and render it as markdown through some external dependency.

**Comment by tcompa** [comment]
This can be developed using
```
fractal-server 1.3.5a0
fractal-tasks-core 0.10.1
```

**Comment by tcompa** [comment]
> docs_info: a string that contains a description of a task, often in markdown format (*);

**Comment by zonia3000** [comment]
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/a94c4dee-2fec-44bb-b545-d0d10ed5cf74)

**Comment by jluethi** [comment]
This is awesome! 👏🏻🎉
