### ISSUE TITLE
Include a "refresh task list" feature

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#26]
After a task collection is complete, some new tasks will exist in the task list in the DB, but they will not show up in the list until we refresh the page.
Could we also include a button to make another API call and refresh the list?

**Comment by rkpasia** [comment]
As referenced, this feature has been included

**Comment by tcompa** [comment]
After a collection procedure is over (see "OK" message), the task list is still empty.

![Screenshot from 2023-03-03 09-36-21](https://user-images.githubusercontent.com/3862206/222672085-2ed527b7-78b1-4696-9228-6bbf42015b33.png)

**Comment by rkpasia** [comment]
This issue is closed with reference to 350740e1
