### ISSUE TITLE
Implement a custom event for modal dismiss

### ISSUE THREAD

**Issue by zonia3000** [fractal-analytics-platform/fractal-web#264]
Sometimes it is necessary to execute custom logic on modal close (see #262). Currently we have associated this custom logic to the close button, but a modal can be closed also clicking on the X button on the top right corner or clicking outside the modal, so at the moment a [static backdrop](https://getbootstrap.com/docs/5.3/components/modal/#static-backdrop) has been set to force the user to close the modal only by clicking on the button. Since this can be annoying it should be better to define a custom Svelte event to execute this custom logic for each closing method.

**Comment by tcompa** [comment]
Note that another way of closing the modal is via the _esc_ key (which is not prevented by the static backdrop).

**Comment by jluethi** [comment]
Interesting! But the esc key is not working to close all things I'd be expecting. For example, I often press esc to close a log window on the job page and that isn't working. Not sure whether the log display is a different model, but would be great to have that match the same closing functionality (and for example also work with esc)

**Comment by tcompa** [comment]
> But the esc key is not working to close all things I'd be expecting.

Yes, I confirm.

This current issue concerns the specific case of the task-edit modal, where we are looking for the best way to perform an action upon closing the modal (typically a reset of some changes that were eventually discarded by closing the modal). Once we manage to fully clean up this specific example, we'll replicate all around the repo - aiming for as much homogeneity as possible.
