### ISSUE TITLE
Switch from using `formData` to binding variables

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#265]
This was added e.g. in the task-edit as part of #262. This is the preferred approach, and it should be used more homogeneously in all forms.

**Comment by tcompa** [comment]
Is think this was mostly covered with #288 (@zonia3000 let me know if I'm wrong), as I can only see `formData` in
```console
$ git grep formData src/

src/routes/auth/login/+page.server.js:          const formData = await request.formData();
src/routes/auth/login/+page.server.js:                  authData = await userAuthentication(fetch, formData);
```

We may want to also update that file, but perhaps as part of a broader user/login review (see e.g #246, #4 and #277).

**Comment by zonia3000** [comment]
Yes, `formData` is now used only in the login calls. I would refactor them when we will introduce OAuth2.

**Comment by tcompa** [comment]
Great. Then I'm closing this one in favor of #246.
