### ISSUE TITLE
Clear task collection status if OK

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#27]
At the moment, if we restart the app we could end up with multiple "OK" statuses, which in fact are just leftovers from previous sessions.

![Screenshot from 2023-03-03 09-39-21](https://user-images.githubusercontent.com/3862206/222672613-9ee92743-1ae1-442c-963e-aee45199ba01.png)

**Comment by rkpasia** [comment]
This should be closed by 350740e1.

There are two new buttons in the GUI. One to clear completely the list, one to clear a single task collection.
