### ISSUE TITLE
Review instructions on how to run fractal-web through `node build`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#273]
Are we hitting CORS issues when running on port 3000? Is it because of fractal-server allowed-cors defaults? To check.

**Comment by jluethi** [comment]
> You'll hit an error page with message "Cross-site POST form submissions are forbidden"

Ah yeah, that was the error I hit as well! Thanks for the update of the docs!

Does it need to be port 3000 or would e.g. `ORIGIN=http://localhost:5173 node build` also work? Is it just that one needs to set ORIGIN, not PORT?

**Comment by tcompa** [comment]
`ORIGIN=http://localhost:5173 node build` won't work, since `node` defaults to port 3000.

`ORIGIN=http://localhost:5173 PORT=5173 node build` does work (see https://github.com/fractal-analytics-platform/fractal-web/blob/main/docs/contribute.md#web-client-startup).
