### ISSUE TITLE
Task argument can be updated once, but not twice

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#278]
@jluethi reported an error with fractal-server 1.3.5a1 and fractal-web 0.5.4. Updating a task parameter the first time goes through, but the second time it does not work (the change is saved successfully, but it does not actually take place in the DB).

fractal-web 0.5.1 seems unaffected.

I'll now try to reproduce this.

**Comment by tcompa** [comment]
I can reproduce the error, with 0.5.4.
First debugging info: the `PATCH` function in `src/routes/projects/\[projectId\]/workflows/\[workflowId\]/tasks/\[taskId\]/+server.js` receives the wrong `request`. That is, this code (in `PATCH`)
```js
	const data = await request.json();
	const updateArgs = data.args;
	const updateMeta = data.meta;
	console.log(`updateArgs: ${JSON.stringify(updateArgs)}`)
```
does not print the correct `updateArgs` object.

**Comment by tcompa** [comment]
First debugging info: the `PATCH` function in `src/routes/projects/[projectId]/workflows/[workflowId]/tasks/[taskId
]/+server.js` receives the wrong `request`. That is, this code (in `PATCH`)
```js
	const data = await request.json();
	const updateArgs = data.args;
	const updateMeta = data.meta;
	console.log(`updateArgs: ${JSON.stringify(updateArgs)}`)
```
does not print the correct `updateArgs` object.

**Comment by tcompa** [comment]
Second debugging info (checked with https://github.com/fractal-analytics-platform/fractal-web/commit/39e395b0d06d900c7d520c850f587824caad5ebe): `updateFormEntry` sometimes (typically the second time) receives the wrong `updatingWorkflowTaskProperties` argument.

**Comment by tcompa** [comment]
0.5.2 does work, but it prints a warning to the browser console: "<JSchema> was created with unknown prop 'saveChanges'"

**Comment by tcompa** [comment]
The bug was most likely introduced in https://github.com/fractal-analytics-platform/fractal-web/pull/268.

**Comment by jluethi** [comment]
Can confirm that it's working as expected again :)
