### ISSUE TITLE
Show task-collection API error in the right place

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#28]
(note: this is not related to a failure in the background process, but to a failure of the API call)

When we have an API response like:
```
INFO:     127.0.0.1:39374 - "POST /api/v1/task/collect/pip/ HTTP/1.1" 422 Unprocessable Entity
```
the error message should appear in the first block of the page (that is, under "task collection"), while it now shows up at a lower position (as if it were an error of the second section, i.e. the one where you add tasks by hand)

![Screenshot from 2023-03-03 10-04-11](https://user-images.githubusercontent.com/3862206/222678282-1267e312-1545-4b28-96d4-942dc8b5610b.png)

**Comment by tcompa** [comment]
This was made obsolete by other updates

**Comment by rkpasia** [comment]
This is fixed with layout updates
