### ISSUE TITLE
Task version sorting: New edge cases

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#286]
I'll open this issue to collect some new edge cases that aren't sorted optimally in the task list display.

See https://github.com/fractal-analytics-platform/fractal-web/issues/149#issuecomment-1614398869 for the original discussion and the test cases.

The new edge-case I just hit:
Sorting v0.1.2 vs. v0.1.dev27+g1458b59

v0.1.dev27+g1458b59 gets sorted above v0.1.2. I think this is because we didn't set the version well for the v0.1.0 task (apparently, it was set as v0.1., not v0.1.0?)

<img width="620" alt="Screenshot 2023-09-19 at 11 16 53" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/d6f59409-4a37-4e37-9bbe-180f874bb0c3">

No action required on this, but let's collect additional sorting edge cases here.
The solution for that one for the moment will be to release a v0.2.0 task version soon. And avoid having versions without the patch number (not sure how that happened, would report here if we see this in other instances again)

**Comment by jluethi** [comment]
Hmm, actually also `v0.2.0a0` does not sort above the `v0.1.dev27+g1458b59` entry. Is that expected behavior? Any good way to get around this (e.g. by editing the task, but can I edit the task version without breaking existing workflows?)

**Comment by jluethi** [comment]
Quick update after today's call:
We have a good workaround: Change the version of the task in Fractal web => sorts correctly

Let's still have this on our radar of edge-cases for task version sorting, but not urgent at all!

The way to reproduce this is to install tasks from fractal-faim-hcs (https://github.com/jluethi/fractal-faim-hcs) or scmultiplex (https://github.com/fmi-basel/gliberal-scMultipleX/tree/main/src/scmultiplex/fractal) via `python -m build` of the package, then `fractal task collect /path/to/scmultiplex-version-details.whl --package-extras fractal-tasks` (without specifying a version during task collection)

**Comment by zonia3000** [comment]
In 2248eeec50c5c60ad89a10025a2dbcaab50433a4 I made the version checking more flexible using `semver.coerce()`.

By default semver is not able to sort `v0.1.dev27+g1458b59` because it doesn't consider it a valid version (it requires 3 numbers separated by dots). The same happens for versions represented as integers (i.e. `2`), as seen also by @tcompa 
in a different scenario - https://github.com/fractal-analytics-platform/fractal-web/issues/314#issuecomment-1853994901.

Coerce function attempts to detect the partial numbers and returns a valid version:

```
semver.coerce('v2') // '2.0.0'
```

I'm using this only when I receive an invalid version.

**Comment by tcompa** [comment]
Quick question 1:
I think at some point we were using the `loose` option in some semver function. Are we still using it (together with `coerce`)?
My first guess is that the best would be to use either one or the other, to avoid unclear behavior - but I did not double-check their definition right now.

If we fully switched from including the `loose` option to using the `coerce` function when an invalid version string is found, then I'm perfectly fine with it.

**Comment by tcompa** [comment]
Quick question 2:

We had a unit test that is used to display what is the expected behavior of the sorting functions. @zonia3000 could you report here the sorted list, including also the new (invalid) version strings like "v0.1.dev27+g1458b59" or "1"? Thanks!

**Comment by zonia3000** [comment]
> Quick question 2:
> 
> We had a unit test that is used to display what is the expected behavior of the sorting functions. @zonia3000 could you report here the sorted list, including also the new (invalid) version strings like "v0.1.dev27+g1458b59" or "1"? Thanks!

Already added in 2248eeec50c5c60ad89a10025a2dbcaab50433a4

**Comment by tcompa** [comment]
> Already added in [2248eee](https://github.com/fractal-analytics-platform/fractal-web/commit/2248eeec50c5c60ad89a10025a2dbcaab50433a4)

Great.

I'm reporting it here for the record:
```js
	const expectedSortedVersions = [
		{ version: '0.1.dev27+g1458b59' },
		{ version: '0.1.2' },
		{ version: '0.2.0a0' },
		{ version: '0.10.0a0' },
		{ version: '0.10.0a2' },
		{ version: '0.10.0alpha0' },
		{ version: '0.10.0alpha3' },
		{ version: '0.10.0b4' },
		{ version: '0.10.0beta5' },
		{ version: '0.10.0c0' },
		{ version: '0.10.0' },
		{ version: '1.0.0rc4.dev7' },
		{ version: '1.0.0' },
		{ version: '2' }
	];
```

(cc @jluethi - does this fix your original issue? is there any other version we should include in this expected-behavior list?)

**Comment by tcompa** [comment]
> We are still using loose, but it is not the same as coerce.

OK, thanks for the clarification.

**Comment by jluethi** [comment]
> (cc @jluethi - does this fix your original issue? is there any other version we should include in this expected-behavior list?)

This looks good to me!

I finally figured out why this occurred: Older version of scmultiplex were only versioned as 0.2, 0.3 etc. (only major, minor, no patch).

I haven't seen any other edge-cases yet. But we'll let users surprise us with them next year ;)
