### ISSUE TITLE
Revamp dataset create/update feature

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#299]
Preliminary check checked: will this proposal become obsolete once we move with https://github.com/fractal-analytics-platform/fractal-web/issues/244? IMO it will still be relevant, since we don't want a user to always create a new project for any update to a dataset.

---

The current UX is suboptimal, since it requires a user to:
* Create a dataset, with a given name
* Open the dataset
* Ask themself what does "type" mean and what are the options.
* Set the type and save
* Click "add resource"
* Type the path, and save
* Go back to the project page

(and similarly to update an existing dataset)

Here is a first proposal on how to improve this flow.

On the projects page, we already have the list of datasets in the top, which looks like

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/6d5574fd-534c-483f-b826-e113918e6b63)

## New create-dataset modal
We remove the create-dataset feature, and replace it with a single "Create new dataset" button.
Clicking that button now opens a modal, where we can set:
* Set dataset name
* Set dataset type (see below)
* Set dataset read_only attribute
* Edit a list of resources (see below). This should offer the typical array interaction: add item, remove item. _Non-goal:_ user can edit the order of resources.

Note that this modal would then call multiple API endpoints:
* one POST-dataset call
* one or many POST-resource calls

## New edit-dataset modal
Next to the "Open" and "Delete" button, there should be an "Edit" one (currently this is mixed up with "Open" button, which should probably become a read-only "Info" button). This should open a modal which looks like the create-dataset modal, but obviously with all fields already set to the current values.

The modal would offer the same kinds of interactions: you can edit the dataset attributes, and add or remove resources (_non-goal_: user can edit the order of resources).

Note that this modal would then call multiple API endpoints:
* one PATCH-dataset call
* one or many DELETE-resource calls
* one or many POST-resource calls

(in my view, this really calls for the transformation of the `resource` table into a `dataset` column.. see https://github.com/fractal-analytics-platform/fractal-server/issues/541)

## Checks on the resource list

When creating/editing a dataset, there must always be at least one resource. Fail otherwise.

## Dataset type

We could offer a drop-down menu to choose `dataset.type`. Options would be:

- Any of the `task.input_type` or `task.output_type` of any of the currently available tasks. This will typically result in `["image", "zarr"]`, but if a user adds a custom task with type `nice_images` then we will also have it in the menu. Should we restrict this check to common tasks (i.e. the ones with `task.owner=null`?).
- A free field for a custom string.

**Comment by tcompa** [comment]
Additional details:

1. A Resource object simply consists in an ID and a `path` attribute, so that there's no need to display its internal structure. For the user, a resource _is_ a path.
2. Resource paths may be quite long, thus we should be careful in how to set up their text prompts or how to display them.
3. The relevant validation models for the dataset POST/PATCH endpoints are `DatasetCreate` and `DatasetUpdate` in https://github.com/fractal-analytics-platform/fractal-server/blob/main/fractal_server/app/schemas/dataset.py, with the additional  `valstr` validator defined [here](https://github.com/fractal-analytics-platform/fractal-server/blob/main/fractal_server/app/schemas/_validators.py#L4). Or one can start up a fractal-server instance, and look e.g. at http://localhost:8000/openapi.json

**Comment by jluethi** [comment]
> Preliminary check checked: will this proposal become obsolete once we move with https://github.com/fractal-analytics-platform/fractal-web/issues/244? IMO it will still be relevant, since we don't want a user to always create a new project for any update to a dataset.

Agreed!

I like the proposal, having one modal where users put in all the information they currently put into multiple different places :)


> Next to the "Open" and "Delete" button, there should be an "Edit" one (currently this is mixed up with "Open" button, which should probably become a read-only "Info" button). 

Interesting thought, I think I agree. Let's keep the functionality that a user could then see e.g. meta in the dataset. And let's discuss briefly how history & components will be handled. I think showing them under info/open would make sense, but we were discussing whether a user can modify components => where would that go?

> Any of the task.input_type or task.output_type of any of the currently available tasks. This will typically result in ["image", "zarr"], but if a user adds a custom task with type nice_imagesthen we will also have it in the menu. Should we restrict this check to common tasks (i.e. the ones withtask.owner=null`?).

I like this approach. But it would only work if new types are added automatically when users add tasks (=> also tasks with an owner influence this). That has the potential of becoming messy at some point. We could counteract this by having the "common" types always show up top, and the types that only show up in user-specific tasks be sorted to the bottom.

**Comment by tcompa** [comment]
Four options:
* "new" -> opens a new modal, which only shows attributes that can be set
* "edit" -> opens a new modal, which only shows editable info
* "open" -> opens a new page, possibly showing a lot of info
* "delete" -> only shows a confirmation dialog

**Comment by tcompa** [comment]
> We could offer a drop-down menu to choose dataset.type. Options would be:

Quick comment: if `"Any"` is part of the inferred list, it should be removed and not included in the pre-filled options. If a user wants `dataset.type="Any"`, they'll have to fill the free-field input field.
