### ISSUE TITLE
Implement login page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#3]
1. For the moment, we assume that the user already exists (that is, the server admin already registered them through the command-line client).
2. The login page should mention the version of fractal-server it is communicating with.  The `/api/alive/` endpoint response looks like
```JSON
{
"alive": true,
"deployment_type": "something",
"version": "version_number"
}
```

Note: we did not encode this response in a specific model, given its simplicity, but we can do it if it is useful.

**Comment by rkpasia** [comment]
- [ ]

**Comment by rkpasia** [comment]
Now the client shows an error if the login fails.

Since it is also related to this issue, the client always shows the server version and deployment in footer
