### ISSUE TITLE
Page layout improvements

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#302]
@jluethi

**Comment by jluethi** [comment]
Collecting some here: 
The project list layout is part of this issue: https://github.com/fractal-analytics-platform/fractal-web/issues/382
The project page layout for a given project is discussed here: https://github.com/fractal-analytics-platform/fractal-web/issues/383

**Comment by jluethi** [comment]
For renaming: Replace gear icon (->configuration) with pencil icon (->edit) 

One on the project page
<img width="1121" alt="Screenshot 2023-12-20 at 15 46 31" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/dc01346c-ba24-4842-a037-80eda08610d7">

One on the workflow page: 
<img width="1111" alt="Screenshot 2023-12-20 at 15 46 20" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/f20df53f-f52d-498e-9c12-5dad3d074279">

For reordering workflows: Replace gear icon with an up/down arrow or something
<img width="351" alt="Screenshot 2023-12-20 at 15 46 44" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/c6a9effb-ff63-4dc0-87ab-d1bc06ea1ff4">

**Comment by zonia3000** [comment]
New buttons

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/78b7357b-a6a3-4220-af6d-359de1c9449e)

---

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/229da21e-7505-4f81-a180-85c020c80b28)

---

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/da00b2f9-45c2-4fe2-ad7b-32e9f2a9c150)

**Comment by jluethi** [comment]
Great!
