### ISSUE TITLE
Add version to project, and display it in the footer

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#303]
The footer could read like
> fractal-server 1.3.9, fractal-web 0.5.6

Note that the version should be hardcoded somewhere in fractal-web repo, and then we should either update it by hand for each release or add a bit of GitHub-actions automation for bumping it any time a new tag is pushed.

**Comment by tcompa** [comment]
For the record, the right place for this info is `package.json`

**Comment by zonia3000** [comment]
The standard way to handle version update is using the following npm command:

```
npm version 0.6.0
```

This will do the following:

* set version as 0.6.0 to the package.json
* set version as 0.6.0 to the package-lock.json
* create a git commit having "0.6.0" as commit message
* create a git tag named **v**0.6.0

It works only on a clean git folder (no pending changes).
