### ISSUE TITLE
Improve formatting of 422 Pydantic validation errors

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#311]
They are very nested by default, but the relevant information can be displayed in a simpler way - see https://github.com/fractal-analytics-platform/fractal-web/pull/310#issuecomment-1754739886 and https://github.com/fractal-analytics-platform/fractal-client/issues/548#issuecomment-1733382438.

https://github.com/fractal-analytics-platform/fractal-web/pull/310/commits/af390602f1cbd894cdf3f6a768a6d59a02f205a4 introduces `getSimpleValidationMessage`, where we check by hand that the error structure matches with a known one. For any deviation from this given structure (e.g. because there are multiple validation errors, or because future fastapi/pydantic versions change this structure) we should always return the original message, but when there is a matching structure we can make it more readable.

**Comment by tcompa** [comment]
An example of what could be improved:
![image](https://github.com/user-attachments/assets/3fbdf75f-294e-4d94-bba0-c9cc032df776)

An example where this is already handled:
![image](https://github.com/user-attachments/assets/471559ed-7085-49e8-a232-ff2f12276167)

**Comment by zonia3000** [comment]
Some explanation about error handling @ 0c473b29be6d0b86d3429e6c35c290f52bec2b7f

Errors that have been improved by the refactoring:

![image](https://github.com/user-attachments/assets/b73ad003-f026-4221-b270-03457a31aec7)

![image](https://github.com/user-attachments/assets/3086bb9f-c504-4e70-8bbc-0ea473168f49)

![image](https://github.com/user-attachments/assets/af9456a0-3422-4994-8c3c-26953b845146)

![image](https://github.com/user-attachments/assets/5f7594f0-eb36-4e33-8f98-e6b410c0d564)

**Comment by jluethi** [comment]
That looks great! If we can move all our errors to such a display, that's a great win! :)

**Comment by tcompa** [comment]
This will be closed with #542. Let's open other issues in case error messages for payload fields are not clear or not well formatted.
