### ISSUE TITLE
Make tasks page more compact when many versions of a task are available

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#314]
Currently, the task page gets quite long and it's hard to keep an overview when many versions of the same task are available. See example here:

<img width="1401" alt="Screenshot 2023-10-11 at 16 38 56" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/62591ca2-5ae4-437c-be48-c59955474705">

It is useful to be able to get the info & edit each task in each version. But the more different versions of tasks we get, the less the simple list view is working to provide an overview.
Can we think of ways to improve this?

One idea: a nested list by task name
I'm also open to other ideas for it :)

**Comment by zonia3000** [comment]
What about something like this? Maybe with a thicker line to separate each block.
Or would you prefer something like a collapsible accordion?

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/c101ec9e-583a-4d84-8a21-5102da9535a0)

**Comment by jluethi** [comment]
This would already help with clarity!

The nicest case I can currently think of: It shows the most recent version of the task, with info, edit, delete button. And an unobtrusive way to expand to show more versions.

In that way, the primary focus is on which tasks are available, for each task there is then a way to check different versions.


If that gets too complex, showing all the versions inside the collapsible accordion is also fine. As long as the accordion is nicely labeled with the name of the task.
Our current accordion usage in the workflow task pages is not very space optimal (e.g. title, then an accordion section that has its own title to click on below).

**Comment by zonia3000** [comment]
I've just pushed on #364 an improved version of the table.

By default all the old versions are collapsed:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/34ad6ae1-1ef0-4f97-81e3-83d2fbb1a085)

The user can expand the hided rows clicking on the plus button (displayed only if there are multiple versions available):

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/12d89468-1de8-4394-8b38-9a81a2d80845)

**Comment by jluethi** [comment]
Oh, this looks awesome!

What are they grouped by? Task name?

**Comment by zonia3000** [comment]
> What are they grouped by? Task name?

Task name and owner, so that if 2 users create 2 tasks having the same name they are 2 different groups

**Comment by tcompa** [comment]
As I already mentioned, I find this new version great.

Minor detail: adding a task with version "1" and then a task with version "2" (without refreshing the page) leads to a wrong sorting:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/dbbeb851-c682-4f6d-a65f-841f073e55b0)

**Comment by zonia3000** [comment]
> Minor detail: adding a task with version "1" and then a task with version "2" (without refreshing the page) leads to a wrong sorting

This is another semver issue. Indeed "1", it's not considered a valid version: "1.0.0" format is required
