### ISSUE TITLE
New per-user and per-workflow job pages

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#318]
Let's move to two different "jobs" pages: one at the workflow level, and one with all jobs of a user

## Per-workflow jobs
1. This fetches all jobs related to a workflow, by fetching all jobs related to the corresponding project and then filtering on fractal-web side. Maybe we can improve this based on https://github.com/fractal-analytics-platform/fractal-server/issues/920
2. Data are filtered _before_ filling the table, so that the table at first appears as clean (with all filters unset) and the URL does not include any query parameter
3. The header of the page correctly says something like `Jobs of workflow "My Workflow Name"`
4. The url&breadcrumbs of the page are appropriate (something like `project/1/workflow/2/jobs` in the URL, and the same structure in the breadcrumbs)
5. A (top-right?) button brings you back to the workflow page
6. The table does not include project and workflow columns

## Per-user jobs

1. It is always visible in the top menu, under the "Jobs" name
2. It fetches all user's jobs, by first fetching all user's projects and then fetching all jobs of each project. Maybe we can have a single endpoint for this? (https://github.com/fractal-analytics-platform/fractal-server/issues/920)
3. It does not apply any filter on the job list
4. It does show project.name and workflow.name columns
5. The header of the page correctly says something like `Jobs of user "admin@something.xxx"`

## Side effects

Other simplifications that are now possible
1. The workflow-apply modal, upon success, redirects to the workflow page (without adding the job-id query parameter to the URL)
2. We can probably fully disable the feature of URL query parameters being turned into table filters
3. We automatically get rid of the "Job ID filters don’t show up in the interface" issue
4. We most likely get rid of the "Transient display of other jobs during refresh: " issue

## Related

* #119 
* #294

**Comment by zonia3000** [comment]
> 5. A (top-right?) button brings you back to the workflow page

Is this needed? There is already the breadcrumb that goes back to the workflow page.

**Comment by tcompa** [comment]
> It fetches all user's jobs, by first fetching all user's projects and then fetching all jobs of each project. Maybe we can have a single endpoint for this? (https://github.com/fractal-analytics-platform/fractal-server/issues/920)

This is now available, as of fractal-server 1.4.0a1.
The relevant endpoints (see also https://fractal-analytics-platform.github.io/fractal-server/openapi/) are:
* `/api/v1/project/job/`
* `/api/v1/project/{project_id}/workflow/{workflow_id}/job/`

**Comment by zonia3000** [comment]
I see that using the new version the job status is now stored as an uppercase string. This has an impact on the visualization that I can quickly fix:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/5ea6384a-bd7c-4774-95f6-0f4a3c68b076)

However I was wondering if this has been considered as a breaking change and if the statuses of the old jobs should be updated by the database migration procedure. One could be in a mixed situation after upgrading the server.

**Comment by zonia3000** [comment]
> This is now available, as of fractal-server 1.4.0a1. The relevant endpoints (see also https://fractal-analytics-platform.github.io/fractal-server/openapi/) are:
>  * `/api/v1/project/job/`
> * `/api/v1/project/{project_id}/workflow/{workflow_id}/job/`

I see that the project type also has the fields `workflow_list` and `job_list` on it, so it seems that retrieving the list of projects should be enough to obtain all the information I need. Do you agree?

**Comment by tcompa** [comment]
> However I was wondering if this has been considered as a breaking change and if the statuses of the old jobs should be updated by the database migration procedure. One could be in a mixed situation after upgrading the server.

This is something I also noticed, and I don't think it should be like this. We are looking into it.

**Comment by tcompa** [comment]
To clarify: let's fully remove the per-project jobs page.

**Comment by jluethi** [comment]
+1 on we don't need per-project job pages anymore if we have workflow job pages and all jobs (of a user) :)

**Comment by tcompa** [comment]
> I see that using the new version the job status is now stored as an uppercase string. This has an impact on the visualization that I can quickly fix:
> 
> ![image](https://user-images.githubusercontent.com/5459334/283738075-5ea6384a-bd7c-4774-95f6-0f4a3c68b076.png)
> 
> However I was wondering if this has been considered as a breaking change and if the statuses of the old jobs should be updated by the database migration procedure. One could be in a mixed situation after upgrading the server.

Could you provide some more details?
I think I saw something similar in the past, but I'm now failing to reproduce it.

**Comment by zonia3000** [comment]
> Could you provide some more details? I think I saw something similar in the past, but I'm now failing to reproduce it.

Weirdly I'm not able to reproduce the same behavior, however I think that something was broken with version `1.3.14`. Indeed, creating a job with `1.3.13` and then upgrading to `1.3.14` I receive the following error at server startup:

```
LookupError: 'failed' is not among the defined enum values.
Enum name: jobstatustype. Possible values: SUBMITTED, RUNNING, DONE, FAILED
```

Version `1.3.14` writes in db uppercase values.

However, upgrading to `1.4.0a2` values are lowercase again.

**Comment by tcompa** [comment]
Thanks for debugging!

> Version 1.3.14 writes in db uppercase values.

Then I think I know what happened.
* While passing from 1.3.13 to 1.3.14, we updated sqlmodel from 0.0.8 to 0.0.11
* As of 0.0.9, they fixed a sqlmodel bug that meant they were incorrectly detecting some `Enum`s as strings - ref https://github.com/tiangolo/sqlmodel/pull/669
* As of our own 1.4.0, we are switching back to strings on purpose - ref https://github.com/fractal-analytics-platform/fractal-server/pull/974/files

I'll need to mark it somewhere in the CHANGELOG.
