### ISSUE TITLE
Minor updates to project page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#33]
1. Implement the "delete" button for each project in list, with an additional confirmation dialog.
2. Remove the "edit" button, since these operations will be taken care of in the specific project page.
3. ~~Add the "X" button to close the error message.~~

**Comment by rkpasia** [comment]
I don't see a PATCH endpoint to edit project properties.

Until then, I'll close this issue.

**Comment by tcompa** [comment]
This issue also had these points:

> 1. Implement the "delete" button for each project in list, with an additional confirmation dialog.
> 2. Remove the "edit" button, ...

Are they already taken care of?

**Comment by rkpasia** [comment]
Yes by 044cee9e1250ad8a75d5e972c5b000b86810c35f
