### ISSUE TITLE
Expose SLURM-account selection for user-editing and for job execution

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#334]
This is a placeholder, that depends on the corresponding fractal-server feature:
* https://github.com/fractal-analytics-platform/fractal-server/issues/956

**Comment by tcompa** [comment]
As of `1.4.1a0`, the API is now up-to-date (even if this doesn't have any actual effect on job execution yet, waiting for https://github.com/fractal-analytics-platform/fractal-server/issues/1076).

## Changes that already make sense with 1.4.1a0

1. In the admin-area, `GET /auth/users/{id}` and `PATCH /auth/users/{id}` now also include the `slurm_accounts` property (in the request and/or response bodies). This is a non-nullable property, which is made by an array of strings. In case it's not relevant, it should be set to an empty array, and not to `null`.
In the "edit" modal, it would be useful to specify that  the first account in the list will be used as a default for job execution.

## Changes that will make sense after another fractal-server update

2. The same as point 1, but for `GET /auth/current-user` and `PATCH /auth/current-user`. It's not yet relevant to have this in-place, since the user could try to use it but it has no effect.

3. The job-execution prompt should include an optional choice of the `slurm_account` to use, which would then be included as a new (optional string) property in the request body. The UI could be e.g. as follows:
    * If `user.slurm_accounts` is an empty array, then this feature is not relevant and we could either hide it or keep it there but in a shadowed area
    * If `user.slurm_accounts` has some values, then we should show them as a dropdown menu. Should this menu also include the possibility of not setting any account? I think so. Should this menu come with a pre-selected option? I think so (the first one in the list).

**Comment by tcompa** [comment]
This issue is now ready to be tackled. I updated the previous comment with the required changes.

**Comment by zonia3000** [comment]
I see that the server allows to add an empty string inside the slurm accounts list (e.g. `[ "account1", "" ]`). Should this be allowed?

**Comment by tcompa** [comment]
> I see that the server allows to add an empty string inside the slurm accounts list (e.g. `[ "account1", "" ]`). Should this be allowed?

No, it should not (cc @ychiucco)

**Comment by zonia3000** [comment]
Is it useful to have the slurm account inside the workflow job modal?

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/b6712465-3675-4fd6-8728-9fdc3eb73a9a)

**Comment by zonia3000** [comment]
Some screenshot from #391 

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/a76de155-c8d2-42bb-b7d2-74092080d5cf)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/ae024fd2-0e34-42a1-953f-ea69b2bf21e6)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/3b7f59c4-fc79-4921-b5ba-668ae45486cd)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/a1c168c4-7fb6-491d-8b7f-20c4b536fea3)

**Comment by tcompa** [comment]
> Some screenshot from https://github.com/fractal-analytics-platform/fractal-web/pull/391

I've not tested it myself, but the screenshots look very reasonable to me. Thanks!

### Note on backend updates
There may be some updates in the backend (ref https://github.com/fractal-analytics-platform/fractal-server/issues/1146), but I think this first PR should be part of a fractal-web 0.8.1 that co-exists with fractal-server 1.4.2 (the current version). If/when the backend gets relevant updates, we'll target them in future fractal-web PRs/versions.
