### ISSUE TITLE
Add page-loading spinner

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#337]
(as discussed with @zonia3000)

We do need to better profile the current loading times, and discuss mitigation strategies (pagination, slim response models, ..), but in terms of usability it's nevertheless important to add a spinner for when loading a page takes "long".

**Comment by tcompa** [comment]
I'm testing the new spinner as part of #328, and it looks great.

@zonia3000 Here is a minor suggestion, in case you think it makes sense: could we make the spinner only start after a minimum amount of time? When the page loads very fast (e.g. the login page), I think it'd be even better if we just don't see it.

**Comment by zonia3000** [comment]
I've added a 250ms delay to the spinner visibility in https://github.com/fractal-analytics-platform/fractal-web/pull/328/commits/cc4e13b2bbd035fbe9c1b3a4e933e5a90521ccca.
