### ISSUE TITLE
Colors of job.status badges are not updated correctly when sorting jobs table

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#344]
Starting from http://localhost:5173/jobs

Upon loading the page the first time:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/38af2dec-6362-49eb-ad71-4d94209890ce)

After sorting by Status:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/556b20e3-b5e9-43b4-a49c-56b892cc5058)

**Comment by jluethi** [comment]
Same issue when one is on the job page while jobs are running and it auto-refreshes, then jobs finish. They are still in Blue, not in green, even though they are done.
<img width="1422" alt="Screenshot 2023-11-24 at 16 50 49" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/cd1c8d5e-de68-4779-b899-331d3135d2ef">
