### ISSUE TITLE
Confirmation dialogs for "delete" features

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#35]
Placeholder issue

Ref:
* https://getbootstrap.com/docs/5.0/components/popovers/

**Comment by rkpasia** [comment]
The following f33b8bc2d6bffe7157beb1f124ceec7143f28b6f closes this issue

**Comment by tcompa** [comment]
Great, thanks!
Let's include this feature any time we activate a new "delete" button.
