### ISSUE TITLE
Order of datasets in dropdowns

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#351]
Currently, datasets get an unpredictable (and sometimes messy) order in the selection dropdown. We should define a clear criteria for dataset ordering.

The core options I'd consider:
1) Sort alphabetically
2) Sort by creation date
3) Sort by last updated

Why is this needed? See screenshot from @nrepina 

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/6ff04f6f-ed65-4217-ba32-e3619058e89e)

@nrepina What would your preferences be on the ordering system? Most recently modified at the top may be a good default, but would change the ordering over time.
I'd probably default to option 2 (last created at the top of the list), but could be convinced of any of the options. Alphabetically may look the nicest :)

**Comment by jluethi** [comment]
Is there one sorting that would be much easier to provide from the server than the others? If not, having thought about this a bit more: Let's start with alphabetical sorting. We can always implement a different sorting approach later.

**Comment by tcompa** [comment]
> Is there one sorting that would be much easier to provide from the server than the others? If not, having thought about this a bit more: Let's start with alphabetical sorting. We can always implement a different sorting approach later.

The current dataset list in the server has no predictable order. Sorting by ID or by name would be easy to achieve (either in fractal-server or in fractal-web), while sorting by "last edited" or "time created" requires adding new Dataset attributes that we currently don't have (namely something like `dataset.time_created` and `dataset.time_modified`).

**Comment by jluethi** [comment]
Ok, then let's start with alphabetical sorting for datasets
