### ISSUE TITLE
Handle empty job list for a workflow

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#353]
Starting from a project page
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/b2e38ba5-3fab-4ece-b9bd-05a2fca22964)
I click on "List jobs", in the workflow list.
This leads to an empty page:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/ec6cc86f-d08b-450a-933c-d79d5b652a2e)

I think it'd be better to show one of:
1. An empty table
2. A message saying something like "There is no job associated to the current project".

**Comment by zonia3000** [comment]
The empty page was a bug. It should display an empty table. Fixed with d44d681036edaa800c22f3e8532e112dee813060.

**Comment by tcompa** [comment]
I confirm (from the `admin-jobs` branch):
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/7c2a15d9-0478-4f38-a894-ab13c7d5df42)
