### ISSUE TITLE
Review use for `project/{project_id}` API call in single-workflow and single-dataset pages

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#359]
Upon loading the [single-workflow page](https://github.com/fractal-analytics-platform/fractal-web/blob/main/src/routes/projects/%5BprojectId%5D/workflows/%5BworkflowId%5D/%2Bpage.server.js), we make three calls to the fractal-server API:
```js
import { getWorkflow } from '$lib/server/api/v1/workflow_api';
import { getProject, getProjectDatasets } from '$lib/server/api/v1/project_api';

export async function load({ fetch, params }) {
	console.log('Load workflow page');
	const { projectId, workflowId } = params;
	// Get the project
	const project = await getProject(fetch, projectId);
	// Get the workflow
	const workflow = await getWorkflow(fetch, projectId, workflowId);
	// Get the datasets
	const datasets = await getProjectDatasets(fetch, projectId);
	return { project, workflow, datasets};
}
```

I cannot immediately see the need for `getProject` (and the corresponding API call). Could we avoid this call? To be checked.

**Comment by tcompa** [comment]
Would we also need to do the same with datasets? That is, do you think we also need `dataset.project`?

**Comment by zonia3000** [comment]
Yes it could be useful also for datasets, even if the dataset page performs only 2 http calls (one to the project, always for rendering the breadcrumb, and one for the dataset), so it is lighter compared to the workflow page.

**Comment by tcompa** [comment]
As of fractal-server `1.4.1a1`, the `DatasetRead` and `WorkflowRead` response schemas also include a `project` property, which is of type `ProjectRead` and thus includes its `name` property.

This should make it possible to fully remove the additional API call on the single-dataset and single-workflow pages, that are currently just to fetch the project and learn the name that goes in the breadcrumbs.
