### ISSUE TITLE
When does job page status refreshing happen? Not just on job page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#362]
I've been observing the Fractal web log at FMI a bit. It appears the update call to refresh the job status for a job page happens even after I leave the workflow job / all jobs page. I see a lot of this in the logs:

```
[GET] - /api/v1/project/41/workflow/68/job
```

Once I close my browser tab, it stops. But it persists when I'm on the workflow edit page, on the Fractal start page etc.

**Comment by zonia3000** [comment]
I'm not able to reproduce this with v2 pages.

**Comment by jluethi** [comment]
Let's close it then. I'll reopen it if I observe something like this again :)
