### ISSUE TITLE
Highlight relevant part of the error message

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#373]
Currently, when a user checks the traceback of a failed job, they are hit with a wall of text of the full traceback, e.g.:

<img width="1391" alt="Screenshot 2023-12-13 at 18 41 10" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/d888d02a-e4ca-47a4-985c-b58aa120567b">

In this case, the most relevant part of the error is the bottom, the actual error:
```
ValueError: ERROR in create_ome_zarr
actual_wavelength_ids: ['A01_C01']
allowed_wavelength_ids: ['A01_C01a', 'A01_C02', 'A02_C03']
```

Can we highlight the actual error message in the errors and make it more prominent?
It's not always the last line, it can be multi-line. But in Python traceback, it's the non-indented lines at the end.

Any syntax highlighting like this should have a failure mode of highlighting nothing if it can't identify this relevant error part.

Also, extracting such text from an error message could be relevant in other parts as well, see https://github.com/fractal-analytics-platform/fractal-web/issues/374

**Comment by zonia3000** [comment]
Example of the highlighting:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/9c3c71c0-db23-4875-a258-9dacf7098b58)

**Comment by jluethi** [comment]
Same, what PR is this? Would like to test this on some failed workflows to see how it looks on different errors :)

E.g. how it handles a Job Execution Error, instead of a Task Error

-----

What I like about this round:
1. It highlights which task failed
2. It contains the relevant summary of why it failed

Depending on how robust this highlighting is, we could then hide the full trace-back by default. But let's start with this and find the cases where it doesn't work / highlights the wrong thing

**Comment by tcompa** [comment]
> Same, what PR is this? Would like to test this on some failed workflows to see how it looks on different errors :)

I think it's https://github.com/fractal-analytics-platform/fractal-web/tree/highlight-error-message, but I'll let @zonia3000 confirm (and then maybe open the PR?).

**Comment by zonia3000** [comment]
Yes it's that branch. I've just opened the PR: #402

**Comment by tcompa** [comment]
Some comments (with @zonia3000):
1. We always highlight the first line (e.g. TASK ERROR..)
2. We probably only want to set-up Python-traceback parsing for TASK ERRORS, although it's not hard to attempt it also on Job/Unknown errors.

We'll follow up with more real-life examples.

**Comment by zonia3000** [comment]
Some new screenshots with real errors:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/1aad6337-8589-4425-b2c5-fe58ae88c7f8)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/1d62c411-5722-42ea-b0b6-e5589aa3733c)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/2922361d-dab7-4026-976a-985aff0de616)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/aeb094ba-7cec-459a-a318-72959597dc34)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/71dcde72-6974-4136-a4f6-4e6a189c94a7)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/0a3e9bc4-b27c-48de-b048-8ce0aabdbaed)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/bfbc8247-9678-4e3c-808d-4dd07cd3b657)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/84f8da5c-b3e0-48b5-af48-43012b3cb79f)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/e2ff2c83-9fb3-45da-880a-d26bbfc4397f)

**Comment by jluethi** [comment]
This looks very promising in being able to get the relevant parts of the error message!

To improve the user experience: Can we default the error window to just show that highlighted text and have the full traceback hidden under a "Show details" menu/clickable expansion? 
While the traceback is very valuable and most programmers can handle them fine, to many of our user the "wall of text" is confusing and somewhat daunting.

**Comment by zonia3000** [comment]
Is this good?

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/307292ec-c0d0-444f-83ef-fc466eb98399)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/bcf79872-d6fd-4d88-a1f4-b3cbd73c9e1d)

**Comment by jluethi** [comment]
Yes, this is great! :)
