### ISSUE TITLE
Make error message directly accessible from the workflow page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#374]
Given that we can now show errors on the workflow page in the new experimental setup: What should a user do when they see that a task failed? They'd want to know why => there should be a good flow to get to the actual error.

I see 2 options here:
1: Can we link to the workflow Job logs page for that error / pop this modal up when a user clicks on the error or somewhere relevant?
2. Can we extract relevant information from the error and show it more easily already on the page?

For 2, I could imagine something like finding the actual error that was raised (see separate issue here: https://github.com/fractal-analytics-platform/fractal-web/issues/373) and only displaying this, e.g. in a small hover pop-up (similar to the warnings when validation fails during task collection). And then offer some button to load the full traceback.

**Comment by jluethi** [comment]
Why is this valuable? If a user can just see the following message:
```
ValueError: ERROR in create_ome_zarr
actual_wavelength_ids: ['A01_C01']
allowed_wavelength_ids: ['A01_C01a', 'A01_C02', 'A02_C03']
```

They don't need to look at the full traceback and can directly correct the inputs on the workflow page => a user could often just stay on the workflow page, make a submission, see an error, fix a parameter, try again etc.

**Comment by zonia3000** [comment]
Should something like this would be ok?

It appears when the most recent job associated with the selected input and output datasets has a failed status. 

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/40f78714-dfc1-402a-a6a9-3fa41d07e256)

**Comment by jluethi** [comment]
Yes, that's great! :) 
What does the Show complete log button open in this case? The log with the full stacktrace?

**Comment by zonia3000** [comment]
Yes, it opens the same modal that you see in the jobs page when you click on the "Logs" button. I've just pushed also these changes on PR #402, so you can try also this.
