### ISSUE TITLE
Align with fractal-server (re: verified users)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#381]
[EDIT: I updated this issue description]

Starting with fractal-server 1.4.2, non-verified users will not have full access to `/api/v1` backend endpoints any more.

This is meant to prevent self-authenticated users (who log in through OAuth but are not yet in the database) from actually performing some critical operations (task collection, task definition, job execution) - both because a manual setup is anyway needed (setting some Fractal-specific user attributes) and to have control on who can actually access this service.

A couple of changes in the client are needed (and the two new server/client versions should be deployed at the same time):
1. When the admin registers a user, the user should be automatically "verified". Since the register-user endpoint does not accept `is_verified=True`, I think we have to make two API calls: we first register the user and then make a PATCH call to set `is_verified` to true.
2. A non-verified user can still login (because verification is not required for `/auth/current-user/`), but they have limited access to `/api/v1/`. For sure there should be a very visible warning that tells them "As a non-verified user, you have limited access; please contact an admin".

**Comment by tcompa** [comment]
We merged this PR in fractal-server, where we prevent access to task-collection and workflow-execution to non-verified users:
* https://github.com/fractal-analytics-platform/fractal-server/pull/1099

As soon as we want to rely on a new fractal-server release, this issue becomes high-priority.

**Comment by tcompa** [comment]
fractal-server 1.4.2a0 is now available, and can be used when working on this issue

**Comment by zonia3000** [comment]
[Ref 4cdca93860931b5943d093738b0f7979ae1e1e08] Users registered by the admin are automatically verified (a `PATCH` API call is performed after the creation).

[Ref 299df1194b79c230b3495af2874fdf51f6628855] Users having `is_verified` set to false see the following warning on the top of each page:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/6500b2b6-9f58-4810-8da2-4b40215f0bc7)

---

If an unverified user tries to perform task collection the following error appears under the warning:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/caeff2fc-2d6e-4da7-a38e-9fd29a00a6ee)

---

If an unverified user tries to start a job the following error appears in the "Run workflow" modal:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/186037dd-19b6-4a2e-a56e-0ef29510584a)

**Comment by tcompa** [comment]
All looks as expected. Thanks!
