### ISSUE TITLE
Add Project search box on Project page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#382]
Instead of entering the project name in a box before, Create new project should trigger a modal to create a new project with a given name.

And there should then be a search box on top where the current "Project name" field is that allows users to filter projects by name (to more easily find a specific project)

Old:
<img width="1391" alt="Screenshot 2023-12-20 at 15 13 09" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/98987f60-02b8-4f47-89c4-14e3759fbb7c">

New:
<img width="909" alt="Screenshot 2023-12-20 at 15 30 38" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/3112f3bd-5588-4662-9094-44d81f9c408c">

**Comment by jluethi** [comment]
Update the initial post. Some details:

- Create new project is not deactivated anymore until something is entered into the text field
- Remove Project Ids from list page

Some additional mock-ups:
Behavior during search
<img width="905" alt="Screenshot 2023-12-20 at 15 31 00" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/9b9e4fc0-67d8-4f5b-a8bb-0e6b0b5f77b5">

Project modal box:
<img width="511" alt="Screenshot 2023-12-20 at 15 31 18" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/17f4f197-fb72-48be-8873-2767423e91b6">

**Comment by tcompa** [comment]
Here is the current behavior in #379:

![Screenshot from 2023-12-21 14-44-49](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/a04e7e05-5e07-4e73-9e06-242ea5985f08)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/9476a74f-c80e-4219-8f44-984a9eb22f7b)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/b130d156-ef2e-4048-a844-68ea70e04b3b)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/a47aa976-f864-4be9-adb7-9533bb2b307f)


---

With respect to the comments above, what is missing is to remove the ID column from the table.

Side comment, this second title seems redundant, I would remove it:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/0a0245a4-c636-4cb0-ab9d-76a8ef266005)
