### ISSUE TITLE
Create new workflow should be a modal, not a text field + button

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#383]
Let's make "Create new workflow" similar to "Create new dataset" (& the new "Create new project") as a modal (instead of text field & button)

We should also combine it with the Import workflow button => both options behind the Create new Workflow button.

Some ideas:
Always show name field.
Below, show import workflow
If no workflow was imported with the json picker, button says "Create empty workflow" or "Create"
If a json file was selected, button says Import
If a json file was selected, name is optional (Import can be pressed).
If no json file has been selected, the "Create" is dimmed until either a name is specified or a workflow was selected.

Also happy to explore other ideas of combining those 2 functionalities in the same modal

**Comment by zonia3000** [comment]
Ref cd45a7806ef20205e8af2acf060f08a3c3a20d3a

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/e2e76ffa-1fef-4718-97a9-3114ae152ad4)

---

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/69ef9757-fae1-4d90-92f7-2fe179d5f361)

**Comment by jluethi** [comment]
Looks great! :)
