### ISSUE TITLE
Search boxes for datasets & workflows on the project page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#384]
Depending on how useful the search boxes are on the project list page (see https://github.com/fractal-analytics-platform/fractal-web/issues/382), we could also add search boxes for datasets & workflows on the project page (after unifying the "create button" approach, see https://github.com/fractal-analytics-platform/fractal-web/issues/383)

For this page (no mockup made so far)
<img width="1391" alt="Screenshot 2023-12-20 at 15 41 42" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/bdcdf215-fb7d-4fa1-8e90-5942c16df887">

**Comment by zonia3000** [comment]
New search boxes (f677e284c8acae44896fcc05e1eeb4d35d8e955e):

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/fd563fab-8583-4a19-8a67-e0cbfe7c39c7)
