### ISSUE TITLE
Job Cancellation: Show confirmation that request was received

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#388]
Currently, cancelling a job (which only works in the slurm setup, not the local runner) takes typically a few seconds (can be ~10s sometimes). This can be a confusing interaction, as users click Cancel an "nothing happens".

Given the discussion here: https://github.com/fractal-analytics-platform/fractal-server/issues/1150
Could Fractal web show a confirmation that a cancellation request was sent out if it gets the 202 response (only coming with Fractal server 1.4.2)? With a note that it can take a bit until the job is actually cancelled.

**Comment by zonia3000** [comment]
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/661a564f-9485-4467-bcaa-97e24f1dddba)


![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/a591fa5e-c4b3-4f15-98f9-1845dff587bf)

**Comment by jluethi** [comment]
Great, very useful to have this feedback included!
