### ISSUE TITLE
View all datasets related to the project in context

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#39]
The client shall display a list of all datasets available in a project.

The list shall be presented as a table and include the following attributes in columns:
- Name
- Type
- (to be discussed @tcompa, @jluethi)

From the list the user shall be able to preform actions upon the dataset resource, such as:
- [x] Delete the dataset (suppose that this can be interpreted as remove the association of this dataset with the context project)
- [x] Show more information related to the dataset resource.

We have two options related to showing more informations about a dataset, either a collapsable UI component or a specific client page. This really depends on how many informations are included within a dataset resource.

_What is important, tho, is that if there are many properties related to a dataset, these get fetched upon user request and are not triggered by project page context._

**Comment by rkpasia** [comment]
- The user can delete a dataset from a project f173907fbbe65ce0f0ac0fae26953fcb4ee4d541 through the datasets list within a project page 863492c8dcf7e2b8b7978bdef6d956472141a43f

In the client has also been introduced a specific page for the dataset a8f5fea37a9d18ff806751ac9f40ac2b8d26dd83 where we can see specific details of the dataset, but should be discussed together @tcompa @jluethi.

**Comment by tcompa** [comment]
Thanks @rkpasia.

1. Showing name+type in the dataset list is good for now. A possibly useful addition is a third column like "number of resources", but it's not urgent (nor I'm sure it's necessary).
2. Concerning your "_Delete the dataset (suppose that this can be interpreted as remove the association of this dataset with the context project)_", the delete-dataset endpoint removes a specific row from the dataset table, and removes all the resources in its `resource_list` attribute from the resource table (on top of removing the association with the context project, of course). Something that perhaps we did not stress is that our dataset DB entries only contain metadata, while fractal-server does not manage the actual scientific data (i.e. the microscope images).
3. The current way of deleting the dataset from the dataset list in the project page (see screenshot below) matches with what I expected. Only missing the confirmation dialog ;) - ref #35 


![Screenshot from 2023-03-09 08-35-03](https://user-images.githubusercontent.com/3862206/223952298-497a09d9-7a17-4826-9281-d17a2e7bb97d.png)

**Comment by rkpasia** [comment]
As by recent comments, and since the closing of #35
