### ISSUE TITLE
Is the message about where to get support still visible?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#390]
We have the following `.env.local`, and no other `.env*` file.
```
FRACTAL_SERVER_HOST=http:// something

# AUTH COOKIE
AUTH_COOKIE_NAME=fastapiusersauth
AUTH_COOKIE_SECURE=false
# remember to set this in production
AUTH_COOKIE_DOMAIN=...
AUTH_COOKIE_PATH=/
AUTH_COOKIE_MAX_AGE=1800
AUTH_COOKIE_SAME_SITE=lax
AUTH_COOKIE_HTTP_ONLY=true

# PUBLIC VARIABLES (accessible from client side)
PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL= a correct email address
PUBLIC_UPDATE_JOBS_INTERVAL=3000
PUBLIC_OAUTH_CLIENT_NAME=
```
and we get the following home page:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/f1a86648-f819-413d-a170-09bda5d9506a)

I was expecting that setting `PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL` leads to an additional paragraph, saying something like "contact x@y.z for support". Is it something we removed at some point? (cc @zonia3000)

**Comment by zonia3000** [comment]
I'm seeing it:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/cbf41d7a-149c-4e04-b1ad-d12a104420fe)

Notice that it's not set at build time. I have to start the server specifying the variable, i.e.:

```
PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL=help@localhost node build/index.js
```

**Comment by tcompa** [comment]
OK, thanks!

> Notice that it's not set at build time. I have to start the server specifying the variable, i.e.:

If there is a way to include it through env files, that would be for sure convenient.

**Comment by zonia3000** [comment]
Svelte has 2 ways to import the environment variables: static and dynamic. Static variables are loaded at build time, dynamic variable are loaded at runtime. Currently our `PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL` is imported dynamically. We can decide to import it statically, so it will be loaded at build time from the `.env` files, but this means that it will not be possible to override it at runtime.

Here is the dynamic import:
https://github.com/fractal-analytics-platform/fractal-web/blob/f91d3839824b60906d147b08041f99ca249e332c/src/routes/%2Bpage.svelte#L2

**Comment by tcompa** [comment]
> We can decide to import it statically, so it will be loaded at build time from the .env files, but this means that it will not be possible to override it at runtime.

This makes sense to me, also because stopping and restarting fractal-web (if we _really_ need to modify the support email) is not such a complex operation at the moment.
