### ISSUE TITLE
Document which Fractal web version works with which server version

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#392]
So far, it's just us installing Fractal and typically always the most up-to-date version of both server & web. But we should document which fractal server versions a Fractal web version works in. Maybe as part of the changelog? 

Goal: If someone has a given Fractal server, which Fractal web version should they install and can they reasonably upgrade to a newer version of fractal web without updating Fractal server?

e.g. 0.8.1
Requires at least fractal-server 1.4.3

And later, when there is a fractal server 1.5.0 that wouldn't work with 0.8.1 fractal web anymore (because some server APIs changed), we'd update that.

Or we make a table of it in the README or documentation?

**Comment by jluethi** [comment]
=> let's go with a simple doc page for the moment

**Comment by jluethi** [comment]
See also https://github.com/fractal-analytics-platform/fractal-client/issues/210

**Comment by zonia3000** [comment]
I added a draft of the version compatibility doc page starting from 0.8.1

https://fractal-analytics-platform.github.io/fractal-web/version-compatibility/

**Comment by tcompa** [comment]
This is already part of the release procedure
