### ISSUE TITLE
Show user's detail

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#4]
At any point while interacting with fractal-web, a logged-in user should be able to view their details (note that editing their details is not something that a user can do, but it is restricted to a superuser - i.e. the server admin).

The relevant endpoint is `/auth/whoami`, which responds with this kind of schema:
```JSON
{
  "id": "string",
  "email": "user@example.com",
  "is_active": true,
  "is_superuser": false,
  "is_verified": false,
  "slurm_user": "string"
}
```

The relevant fields that the user should see are only `email` and `slurm_user`.

**Comment by tcompa** [comment]
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/b6cab811-6b3f-4e04-a49f-c33d22457cda)
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/2512b4f3-d135-4315-8267-b9b2ae0a1a4c)


Minor suggestion (based on code in #336): it is not fully obvious that clicking on the email will show my user profile. Would it make sense to include a small "profile" icon instead? Something similar to https://icons.getbootstrap.com/icons/person-circle/, for instance.

Second idea: in the top right corner we offer a single clickable element (be it the email, the email with an icon, or a descriptive string), which then opens a drop-down menu with "my profile" and "logout".

I don't have strong opinions here, and I'm 100% open to better ideas ;)

**Comment by zonia3000** [comment]
I implemented the second idea in 6256065c340b60080e8248da48a53fd9755931a2.

**Comment by tcompa** [comment]
Looks good to me:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/548f4c67-fbe7-4ce1-ba50-ed0ffeb2a5a8)
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/6218549b-bc2c-4640-8b64-33fd2dad450c)

**Comment by jluethi** [comment]
Is there work remaining to be done here? Looks very nice to me!

Do we include the ability for users to edit some of their properties? At the moment, the server release candidate allow for editing the cache dir of a non-superuser by that user themselves. In the future, additional fields like "slurm account" (but not slurm user!) will be added and be user editable, see https://github.com/fractal-analytics-platform/fractal-server/issues/956

**Comment by zonia3000** [comment]
In the profile page we should add the possibility to edit some fields of the user, including the password. I think we can open a different issue for that.

**Comment by tcompa** [comment]
> In the profile page we should add the possibility to edit some fields of the user, including the password. I think we can open a different issue for that.

I'm opening a new right now (but password will not be included)
