### ISSUE TITLE
Align timestamp definitions with fractal-server 1.4.3

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#400]
As of `fractal-server` 1.4.3, @ychiucco implemented some more robust&standardized way of handling timestamps (which is meant to work independently on the underlying DB and on the sqlite/postgresql version).

In terms of API, this means that:
1. All timestamps in fractal-server are internally represented in UTC (this is a side comment, not relevant for the client).
2. All timestamps included in the (JSON) response bodies are of this form: `'2024-01-29T09:21:42.940431+00:00'`. That is, they are:
    * timezone aware
    * in UTC
    * following ISO 8601, as implemented in https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat
3. A few endpoints also accept timestamps as query parameters (namely the ones in the `/admin` routes). The requirement is that the query parameter MUST be timezone-aware. Note that we also accept the Z timezone marker. Examples of valid query parameters are:
    * `1999-01-01T00:00:01+00:00` (note that this string must be quoted correctly, because of the `+` character)
    * `1999-01-01T00:00:01Z`

We should verify that `fractal-web` makes the correct assumptions about:
* How to read timestamps from response bodies;
* How to format timestamps in query parameters (currently only used in the admin-area jobs page).

The up-to-date fractal-server version, for testing, is `1.4.3a2`.

**Comment by zonia3000** [comment]
A note, just to confirm the current behavior.

On the UI the user will always see everything in the browser time zone, while the calls to the backend will always use UTC.

For example, suppose that the admin timezone is Europe/Rome and he searches for jobs after 10:00 AM.\
The API call will use `09:00:00Z`  query parameter to do that search and replies with a record having i.e. `09:52:30Z`.\
That row will be displayed as `10:52:30 AM` to the user:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/a46dc2f2-51a6-4fe7-900b-9a82957d3bed)
