### ISSUE TITLE
As admin, can't remove `username` once set

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#403]
Steps to reproduce:
Create a user with `slurm user`& `user name`
Realize that `user name` would not be necessary to set
Remove `user name` from Fractal web & save the user

But the username does not disappear.

I assume the same may happen for other fields, like `slurm user` or `Cache dir`. Probably related to Fractal server handling of an update payload with `user name`=None

**Comment by tcompa** [comment]
Duplicate of https://github.com/fractal-analytics-platform/fractal-web/issues/368?

**Comment by jluethi** [comment]
Ah right, closing this as duplicate then :)

Not urgent, just wanted to record the observation of the unexpected behavior
