### ISSUE TITLE
Include job ID in the admin-area jobs page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#404]
It looks like the job ID attribute is not included anywhere in the data shown in the admin-area jobs page.
Relevant use case: the admin find out that job 1234 may have some issues, and wants to access it directly.

We could include this information in different places:
- We can expose the `id` query parameter, so that I can immediately search for a specific job via its ID
- We can show the `id` column in the table
- We can hide the `id` column from the table, but then let's at least include it in the csv file that one can download.

Higher-level: it's clear that we may prefer not to expose users to IDs, but it's a useful info for the admin.

**Comment by zonia3000** [comment]
Form with the Job Id field:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/25e15bf6-2c0c-4efc-a34d-26fe4339de3c)
