### ISSUE TITLE
Is the "Open" button the most natural required action?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#405]
In most pages or sections where we have a list of resources (projects, datasets, workflows, tasks), the required action to open the resource-specific view is to click the "Open" button in the "Options" column.

While testing fractal-web with @marcodeltufo, we realized that another possibility would be to make the resource name a link, so that the "Open" button would be replaced by clicking the link (or maybe the two could co-exist). The downside of this option, however, is that it is less homogeneous with the fact that multiple options ("Open", "Edit", "Delete", ...) are grouped together.

I don't have a strong opinion here, but I do think that clicking the resource name looks like a natural action to do in order to get to the resource page.

**Comment by zonia3000** [comment]
I agree that a link in the name looks more natural, as many web UIs use that approach.

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/73b9def4-28e7-4efb-805d-1f838ddf958b)

![image](https://github.com/user-attachments/assets/d0b7b91d-b900-4a4e-9b2e-717e13483573)

**Comment by jluethi** [comment]
I'm fine with the change overall. Let's also drop the Id column for workflows though to make it a bit more uniform
