### ISSUE TITLE
Possible bug: using user's endpoint in admin-area jobs page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#406]
How to reproduce:
- log in as an admin
- go to the admin area
- search for all jobs of a given user (not myself)
- find one job which is marked as "done", click on "logs" -> this works
- find one job which is marked as "failed" click on "logs" -> this fails

Fractal-web error:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/87f6e07b-92c1-409c-8067-ef2ddfd222ac)
Fractal-server corresponding error
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/2770a605-a520-4599-a33f-c903798cab2a)

Question: is there a call to some `/api/v1` endpoint (notably `/api/v1/project/93/job/551`) from the admin-area jobs page, triggered by the "logs" button for failed jobs? I think there shouldn't be any, in principle.

Let's review this.

---

### Side comment
When this error takes place, we also have something weird in the modals. There are two "X" button, and clicking the first one only closes the inner modal. Then I have to also click on the most external one:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/9a878db1-50f0-4be2-9df5-a5986dd038b3)
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/f9be4b03-ac63-4e7e-b03c-1b38825e7933)

**Comment by tcompa** [comment]
Important addendum: this error does not take place for all failed jobs, but only for some of them. I am not yet able to see what is the relevant difference.

**Comment by zonia3000** [comment]
The cause was the empty log. There was a check inside the logs modal that attempted to fetch the job when the log field wasn't set and it used the default API. I think that this check is not needed anymore, since we are opening the modal passing the log field of an already fetched job, so I removed the check and the call in a6c477d6da5173e03f399e24c406370fa2699698
