### ISSUE TITLE
Task-addition modal shows empty list, the first time it's opened

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#408]
### Observed behavior

When adding a task to an empty workflow for the first time, the list appears as empty and only showing "search".

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/ed524e35-0559-4c21-9e66-81e40e6734ff)

After a few clicks to expand/compress the list, it appears as pre-filled with available tasks

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/5fdb5448-6100-47a1-90c9-d921fa1e1686)

### Expected behavior (IMO)

The list should appear as pre-populated every time, including the very first time.

**Comment by zonia3000** [comment]
Can you provide some more details on this? I'm not able to reproduce and this case is also covered by playwright tests.

**Comment by tcompa** [comment]
After reviewing this together with @zonia3000

1. The reason for the observed behavior is just that the API call is taking very long in my (VPN-based) setup.
2. The response body in this case was 1.2 M, but we only need a few attributes per task. We can improve on this on the backend side: https://github.com/fractal-analytics-platform/fractal-server/issues/1217.
3. Client-side, let's add a spinner when the call takes long - to make it clear that something is still happening.
4. Client-side, we noticed that there seem to be _two_ calls triggered by the add-task modal. To be verified.

**Comment by zonia3000** [comment]
>     4. Client-side, we noticed that there seem to be _two_ calls triggered by the add-task modal. To be verified.

I've checked this and opening the modal triggers only one calls. The other call that we have seen was created at the loading of the page to check for new versions. So it's working as expected.

**Comment by zonia3000** [comment]
A small spinner will appear next to "Select task" when tasks are loading:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/6f13fa4a-63da-47bf-83d6-4471685cf47d)
