### ISSUE TITLE
Make it clear that logs can be expanded

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#409]
This is how the "shortened" logs are displayed, as of #402:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/f8a3bf1a-f5ff-4bf3-8fb7-bf6c6a2c0db5)

And then if one clicks on "Show details" the whole error message is shown, with the relevant parts highlighted.

---

I think that in the screenshot above we are not clearly showing that the logs _can_ be expanded. It's true that there is the button on the top-right, but it's not extremely visible (and it's far from the part that one is looking at).

Possible suggestions:
- We replace the non-critical part of the logs with a button like "... (details hidden, click here to expand)"
- We add a warning kind of message on top of the log, which says "This is a shortened log, click XXX to view full logs"
- Something else.

(to be clear: the feature is clearly working fine, this is nothing urgent)

**Comment by jluethi** [comment]
> We replace the non-critical part of the logs with a button like "... (details hidden, click here to expand)"

I like this option. In that way, it's part of the message that can be read.

**Comment by zonia3000** [comment]
Is this ok?

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/84a11921-f9a9-4b2f-9ebd-59279f04ffa4)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/20bf5ab3-0adb-4807-b7c3-dac3fd2cd71e)

Do you also need to collapse it again? That happens in any case if you close the modal and open it again, but I'm not sure that leaving a "hide details" link inside the expanded text is a good idea.

**Comment by tcompa** [comment]
> Is this ok?

This is what I was expecting, indeed. No strong opinion on the specific wording..

> Do you also need to collapse it again?

In my view, it's not that important and we can keep it as you showed.

**Comment by jluethi** [comment]
Looks good to me! :)
