### ISSUE TITLE
Workflow Task selection color + submitted animation color clash

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#411]
In the new experimental workflow page, the color for highlighting the currently selected workflow task means that one can not see the "submitted" animation for that task anymore

Example: napari workflow task also shows the submitted spinner, but only visible if one selects another task.

![Screenshot 2024-02-09 at 11 44 48](https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/2d0b9cb1-228c-4a65-9dc0-9f7b1a4a8ef4)

Suggestion: Let's change the color of the submitted animation: Maybe to grey?

**Comment by zonia3000** [comment]
The color is now inverted when the item is selected:

![Screenshot from 2024-02-12 11-34-50](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/8a5c60c8-2921-4ddb-b86c-3fdb7a3b48a1)

![Screenshot from 2024-02-12 11-35-03](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/d140fd5c-0289-413d-a136-52f3885540a9)

**Comment by jluethi** [comment]
Hmm, I like the idea. If the whole workflow is submitted (e.g. Convert Yokogawa to OME-Zarr is also part of the submitted workflow), do we see the spinner in blue on it then?

**Comment by zonia3000** [comment]
Yes, you will see the correct spinner in all the submitted tasks. Sorry, the image is a bit misleading because I was just playing with the CSS in order to display it.

**Comment by tcompa** [comment]
It works as expected within #415:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/b38c0c36-d23f-4443-8dd7-24c0841ad9f4)
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/f40899ab-804e-4260-a5d2-bf1bd3967bed)
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/81148064-e3b6-44ee-a426-6192dcd2b33d)
