### ISSUE TITLE
Could we support `allOf` in JSON-Schema-based form-generator?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#413]
Given this JSON Schema
```json
{
  "title": "TaskFunction3",
  "type": "object",
  "properties": {
    "normalizer": {
      "title": "Normalizer",
      "default": {
        "type": "A"
      },
      "allOf": [
        {
          "$ref": "#/definitions/Normalizer"
        }
      ]
    }
  },
  "additionalProperties": false,
  "definitions": {
    "Normalizer": {
      "title": "Normalizer",
      "type": "object",
      "properties": {
        "type": {
          "title": "Type",
          "default": "A",
          "enum": [
            "A",
            "B"
          ],
          "type": "string"
        }
      }
    }
  }
}
```
our current UI shows nothing
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/7ada6f00-d69b-4915-8f9a-71d6b236728f)

If we use a slightly different schema (with no `allOf`)
```json
{
  "title": "TaskFunction2",
  "type": "object",
  "properties": {
    "normalizer": {
      "$ref": "#/definitions/Normalizer"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "Normalizer": {
      "title": "Normalizer",
      "type": "object",
      "properties": {
        "type": {
          "title": "Type",
          "default": "A",
          "enum": [
            "A",
            "B"
          ],
          "type": "string"
        }
      }
    }
  }
}

```
the UI is as expected:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/4de9b439-f08c-42b2-98bf-a6c3a6062790)

TBD: would it be possible to support both cases? (and how complex a change would it be?)

Ref https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/650

**Comment by zonia3000** [comment]
PR #417 supports all these cases:

`allOf` with single `$ref` (our edge case):

```json
{
  "title":"TaskFunction3",
  "type":"object",
  "properties":{
    "normalizer":{
      "title":"Normalizer",
      "default":{
        "type":"B"
      },
      "allOf":[
        {
          "$ref":"#/definitions/Normalizer"
        }
      ]
    }
  },
  "additionalProperties":false,
  "definitions":{
    "Normalizer":{
      "title":"Normalizer",
      "type":"object",
      "properties":{
        "type":{
          "title":"Type",
          "enum":[
            "A",
            "B"
          ],
          "type":"string"
        }
      }
    }
  }
}
```

`allOf` with multiple `$ref` (the form will contain the properties of both schemas):

```json
{
  "title":"TaskFunction3",
  "type":"object",
  "properties":{
    "normalizer":{
      "title":"Normalizer",
      "default":{
        "type1":"A"
      },
      "allOf":[
        {
          "$ref":"#/definitions/Normalizer1"
        },
        {
          "$ref":"#/definitions/Normalizer2"
        }
      ]
    }
  },
  "additionalProperties":false,
  "definitions":{
    "Normalizer1":{
      "title":"Normalizer1",
      "type":"object",
      "properties":{
        "type1":{
          "title":"Type1",
          "default":"A",
          "enum":[
            "A",
            "B"
          ],
          "type":"string"
        }
      }
    },
    "Normalizer2":{
      "title":"Normalizer2",
      "type":"object",
      "properties":{
        "type2":{
          "title":"Type2",
          "default":"D",
          "enum":[
            "C",
            "D"
          ],
          "type":"string"
        }
      }
    }
  }
}
```

`allOf` with inline schemas (schemas are merged):

```json
{
  "title":"allOf test",
  "type":"object",
  "properties":{
    "myNumber":{
      "title":"My Number",
      "allOf":[
        {
          "type":"number",
          "minimum":5
        },
        {
          "type":"number",
          "maximum":10
        }
      ]
    }
  }
}
``` 

Note that is up to the user to use this feature in a meaningful way. For example you can specify both `"type": "number"` and `"type": "string"`, but that doesn't make any sense. In that case the current implementation will consider the type of the last schema in the array.

Also notice that `allOf` only required to handle the merging of multiple schemas to one schema, but if we need in the future to implement also `anyOf` that will be more complex and will need some refactoring to keep multiple schemas attached to the same key in the form.

**Comment by tcompa** [comment]
> For example you can specify both "type": "number" and "type": "string", but that doesn't make any sense. In that case the current implementation will consider the type of the last schema in the array.

The user typically does not generate schema manually, then this hopefully should not happen.

In any case, before #417 the corresponding property would not appear in the UI at all. Thus I think there is no doubt that the new version is an improvement, even if it still may lead to edge cases.
