### ISSUE TITLE
Improve JSON-schema sandbox

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#418]
This is very low priority, but it will be useful the next time we need to play with argument JSON schemas.

1. Could we access the sandbox page without authentication? We can decide to hide it unless a specific env variable is set (are we already doing it?)
2. Right now I think there is a glitch in what is considered as the "data" field value. As a first fix: can we always set the data field to `{}` or to empty, at page refresh? In the current version, a page refresh seems to reset the schema prompt but not the data one.
3. Let's increase the height of the JSON-Schema prompt, because it obviously never fits in a single line. Maybe some 10-20 lines, with a scrollbar? Or, even better, let's place the schema and data prompts on the left an the form UI on the right.
4. (a bit more testing will probably raise more of these minor issues)

The overall idea is that most activities in the https://github.com/fractal-analytics-platform/fractal-web/issues?q=is%3Aissue+is%3Aopen+label%3A%22JSON+Schemas%22 area should be easy to test within this sandbox.

**Comment by zonia3000** [comment]
>     1. Could we access the sandbox page without authentication? We can decide to hide it unless a specific env variable is set (are we already doing it?)

We are currently redirecting to the home page if the mode is not development:

```
if (import.meta.env.MODE !== 'development') {
  throw redirect(307, '/');
}
```

Is this ok or do you prefer a specific environment variable to enable the sandbox?

**Comment by tcompa** [comment]
> Is this ok or do you prefer a specific environment variable to enable the sandbox?

Perfectly fine - in terms of hiding the page when the mode is not development.

Can we access the page if no backend is active?

**Comment by zonia3000** [comment]
> Can we access the page if no backend is active?

Yes

**Comment by zonia3000** [comment]
This is the new page:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/9e7dc9c8-6f19-4d20-9068-22c857952031)

I've included the v2 component (we were still using the v1 in this page) and I've added a "legacy" switch that changes the set of ignore properties ('input_paths', 'output_path', 'metadata', 'component' for v1 and 'zarr_url', 'zarr_urls', 'init_args', 'zarr_dir' for v2), as happens for the component loaded in the v2 workflow page.

I've also added a "Validate" button that triggers the validation on the form.
