### ISSUE TITLE
Log download for very large jobs fails weirdly

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#419]
I've been testing the log download for very large jobs. Specifically, job 1006 on the Pelkmans lab deployment.

When I try to download the full log on the jobs page (admin or user), the behavior is suboptimal:
1. At first, nothing happens after clicking download (I guess it takes a while to aggregate the files in the background) => often leads to users clicking the button multiple times
2. Afterwards, on my machine, a download starts, but then runs into a "Sit wasn't available" error
3. For some users, they get a zip downloaded, but it can't be unzipped (=> corrupted zip)?

Point 1 can be optimized on the Fractal web side. Point 2 I'm not sure about. Point 3 could also be a server issue with big log files

<img width="321" alt="Screenshot 2024-02-15 at 14 59 15" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/92403c63-9215-4100-ab58-6641d83949f5">

**Comment by tcompa** [comment]
The job-folder size is 18G, then I think it's not surprising that _something_ goes wrong.
The main issue here is on the backend side: https://github.com/fractal-analytics-platform/fractal-server/issues/474#issuecomment-1946185532.

**Comment by jluethi** [comment]
Ok, I would not expect that to work on the web frontend in any way then! Let's address the backend side first!

**Comment by tcompa** [comment]
I could download a 500M folder zipped to ~50M file.
The unexpected behavior when something fails is already discussed in https://github.com/fractal-analytics-platform/fractal-web/issues/493
