### ISSUE TITLE
On job page, add search functionality for Project, workflow, input & output dataset dropdowns

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#423]
I just saw a user navigating these dropdowns with some 30 entries or so and a search box would really have helped. Are there downsides to adding a search box to these dropdowns? I guess we're already loading the list of all datasets etc. to generate the dropdown, right?

**Comment by zonia3000** [comment]
No, I don't see any problem in adding search boxes on that dropdowns.
