### ISSUE TITLE
Expose both v1 (legacy) and v2 fractal-web

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#425]

**Comment by tcompa** [comment]
This is currently in-place, with a switcher that can be modified only in the top-level pages: projects, tasks, jobs, admin. This switch corresponds to switching between e.g. http://localhost:5173/v1/admin and http://localhost:5173/v2/admin.

To do:
1. The home page should not include any switch, since it does not depend on the version.
2. What about replacing the legacy/current dropdown menu with a link that says something like "Switch to legacy version" or "Switch to current version"? I'm not sure what's best.
3. The home page text should explicitly describe the current situation, and there should be buttons pointing to both legacy and current top-level pages. The additional paragraph (TBD) could read something like
> This is version 2 of Fractal. Your legacy projects and tasks are still available, and you can still use the legacy Fractal version. To do so, select the ... (depending on point 2). 
4. To decide: should the "legacy" mode be marked visually in a more prominent way? It could be a visual decorations (similar to the one in the admin page), or a warning message, or something else, or nothing.

(cc @jluethi: feedback here is welcome)

**Comment by jluethi** [comment]
I like that we have a top-level switch like this and just show what was selected on the project pages.

> What about replacing the legacy/current dropdown menu with a link that says something like "Switch to legacy version" or "Switch to current version"? I'm not sure what's best.

I am in favor of that for top level, then showing what was selected as now on the sub-pages.
"Switch to legacy Fractal"
"Switch to Fractal V2"

> The home page text should explicitly describe the current situation, and there should be buttons pointing to both legacy and current top-level pages. The additional paragraph (TBD) could read something like

Agreed. It's important that the going to the Fractal url always gets you to Fractal V2 by default. And the home-page could then have this explanation:

> "This is the new version 2 of Fractal. Your older projects and workflows are still available in the legacy version that you can access here (links to legacy project page). We encourage you to switch to Fractal V2 for all new projects and report any issues you find.
> We strictly separate projects, datasets and workflows into Fractal V2 and legacy. You can use many of your existing tasks in the Fractal V2 version without any changes required. If you don't find the task you require in Fractal V2, please reach out to the support." 


> To decide: should the "legacy" mode be marked visually in a more prominent way? It could be a visual decorations (similar to the one in the admin page), or a warning message, or something else, or nothing.

Agreed. I'd be in favor of:
For legacy, switch to having things e.g. grey (e.g. the top-level Home, Projects, Tasks, Jobs, Admin) with a clearly visible blue "Switch to Fractal V2". And maybe a grey bar similar to the red admin bar we have? To make it very clear that you are currently on the legacy part.
And on the V2 pages: Color scheme as is, and a grey "Switch to legacy Fractal" button. Eventually, we may hide the switch to legacy part more, but always keep encouraging people in legacy to switch to V2.

**Comment by zonia3000** [comment]
Home page, with the new message and without legacy version switcher:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/5a00083f-c31b-405d-b860-4666009bcf95)

Top level V2 page, with grey button that switches to legacy:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/57cc3e61-9b29-44ae-b852-2992293452e1)

Child V2 page, nothing special is shown:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/b653e378-8d71-4f02-b8bb-929b9b12facf)

Top level legacy page, with greyer navbar background and blue button that switches to legacy:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/5a2ab581-220b-4f63-8b1c-0e039aa6244a)

Child legacy page, no switcher is shown:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/0a9a6310-2988-4136-9876-c5fa49769fb3)

**Comment by zonia3000** [comment]
> Minor nitpick: The `links to legacy project page` part of the new description should be replaced with an actual link to the legacy project page (e.g. the words "access here" being the link)

I had missed that!

I'll use the link without "access here", since using "here" in links is considered [bad practice from UX perspective](https://uxmovement.com/content/why-your-links-should-never-say-click-here/).

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/89a4dba0-7bd7-484c-86a2-86b8640e69be)

**Comment by jluethi** [comment]
That's even better! :)
