### ISSUE TITLE
Dataset create/view/edit (first version)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#427]
V1 attributes that are not present in v2:
* `input_type` and `output_type`
* `resource_list`
* `meta`

Create dataset (POST /api/v2/project/1/dataset/)
* `zarr_dir` (required, string, absolute path)
* `filters`: dict[str, Union[str, float, int, bool], with arbitrary keys. Example of dataset.filters: `{"key": 1, "another_key": true, ..}`. User should be able to add new keys. Property values are scalar, i.e., they are not arrays/objects.

View dataset (GET /api/v2/project/1/dataset/1/)
* `name` - same as V1
* `zarr_dir`
* `read_only` - same as V1
* `filters`:
* `history` - same as V1

Edit dataset (PATCH /api/v2/project/1/dataset/1/)
* `name` - same as v1
* `zarr_dir`
* `read_only` - same as V1
* `filters`: if request body has `filters` property, this fully replaces existing value. Therefore it's possible to remove a given property.

cc @ychiucco - let's also clean up the schemas

**Comment by tcompa** [comment]
Addendum:
* The "show dataset meta" button will not exist any more, in the V2 dataset page.
* A new "images" button or link will be relevant, pointing to the image page described in https://github.com/fractal-analytics-platform/fractal-web/issues/426

**Comment by jluethi** [comment]
Cool to see this coming along!

On what will be shown how prominently: I'd prefer to have the image list be the center-piece of the dataset page afterwards, not the filters.
Datasets do have some default filters. But users will rarely want to edit them on creation. And parts of the filters may also be set during submission (=> more relevant that we highlight it there).
=> Filters could go into a modal like dataset history from my perspective.

**Comment by zonia3000** [comment]
I thought we have to create a separate page for images (#426). Would you like that we add all the information in the same dataset page?

**Comment by jluethi** [comment]
I can mock something up a bit later on how that could look :)

**Comment by jluethi** [comment]
After a quick discussion with Tommaso: Let's iterate on potential page layouts later. Working on a separate image-list page may proof useful.

High-level, I would imaging that most of what's currently in the dataset page will end up in the image-list page (e.g. as buttons on the top: Info, history, filters => expand to modals like history atm) => image-list page becomes the new dataset page.

=> let's not invest into layout questions for the dataset page for the time being, but focus on how we can make the image-list page work first :)

**Comment by tcompa** [comment]
## Clarification about filters

Some filters belong to the dataset DB object, they are persistent and can be modified with a PATCH API call
* Dataset.flag_filters
* Dataset.attribute_filters

Those are *not* included by default when querying the image list, but can be activated with the new additional use_dataset_filters=true query parameter.

Other filters are non-persistent, and only defined as the request body of `POST /api/v2/project/111/dataset/222/images/query/`. In the UI, they can be selected from pre-populated drop-down menus (either in a separate form, or below the column names - TBD)

* body.flag_filters
* body.attribute_filters
