### ISSUE TITLE
Image list user stories

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#428]
To continue the discussions in https://github.com/fractal-analytics-platform/fractal-web/issues/426 and https://github.com/fractal-analytics-platform/fractal-web/issues/427, I started creating image list user stories. Let's focus first on integrating the new API & image list into Fractal web at all (see issues above). 

To describe the eventual design goals, I made 8 user requirements & some mock-ups of how this could look in Fractal web. I am not tied to a specific layout choice, color choice etc., it's more a quick mock-up of a potential user-interface :)

@zonia3000 The first version of that page in #426 came after I drafted this, so this is not meant as feedback on any layout choice there. I'll need to have a look to compare first :)

# Image List Page

### Image list description:

- The image list is a core new property of a dataset in Fractal
- It consists of entries with unique “paths”, a set of (arbitrary) boolean flags & a set of (arbitrary) scalar attributes (int, bool, str, float).
- The list is initially empty and gets populated when a user runs a conversion or import task. This creates an initial image list. Some of the later task will modify the image list (e.g. add new items or edit existing items by adding new flags or attributes.
- The filters are applied to that image list before each task.

### Core requirements for the image list page

- [x] IL1: As a user, I can easily browse the image list of my dataset and see all the attributes & flags per entry. We want to show the image list of a dataset to the user, as it’s a central concept of Fractal V2
- [ ] #461
- [x] IL3: As a user, I want to be able to apply filters on the image list page to see only subsets of the image list. By applying filters locally to the image list (e.g. show me only images with the attribute “well”=B03, only those with illumination_correction flag = True etc.): 
- [x] IL4: As a user, I want to be able to add or remove image list entries. Not a regular user flow, but allows to handle some edge cases.

### Additional requirements (if we can cover some of those, nice. But not a hard requirement for 2.0 launch):

- [x] IL5: As a user, I want to be able to edit the flags and attributes of items in the image list. We will want to expose editing of flags & attributes (not needed in regular flow, but to handle some edge cases). 
- [ ] #462
- [x] IL7: As a user, I want to be able to see the currently applied filters in the dataset. Reason: I want to know which images would be processed with the currently applied dataset filters.
- [ ] #463

### Much further down the road (out of scope for current work):
As a user, I want to be able to launch my viewer from an entry in the image list

See mockups in figma: https://www.figma.com/file/n5CzmEcOadzSlMkUkA9Lut/Fractal-Web-Workflow-Monitoring?type=design&node-id=0-1&mode=design&t=jdMa0xsbA4BYGId5-0

Most relevant parts here as screenshots:

<img width="819" alt="Screenshot 2024-03-19 at 17 07 19" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/4ebf4331-ec10-4d5f-9290-443e43207e74">

<img width="1216" alt="Screenshot 2024-03-19 at 17 07 44" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/8af838bd-74e6-42ca-8117-8956d3a5eae9">

<img width="1168" alt="Screenshot 2024-03-19 at 17 07 59" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/324288a2-5ebb-431a-9758-b772d2fdefcd">

<img width="864" alt="Screenshot 2024-03-19 at 17 08 07" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/97b9e9aa-93d7-43d2-ad56-e736f21ee517">

<img width="1193" alt="Screenshot 2024-03-19 at 17 12 27" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/6dc3982f-d13f-415e-a439-ccae47a7f4a3">

<img width="1565" alt="Screenshot 2024-03-19 at 17 08 31" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/da2ce29d-2c0a-4bb5-a2ba-b76f2dcd2767">

<img width="552" alt="Screenshot 2024-03-19 at 17 08 41" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/8ed75b36-cc7a-431e-bbb9-1b8c4517abd9">

**Comment by tcompa** [comment]
cc @zonia3000 @ychiucco 

Switching from "show all images" to "apply dataset filters" means that the API responds with a subset of the whole dataset.images list. Querying is still possible, through the request body.

More in detail, the switch corresponds to using an additional `use_dataset_filters=true` query parameter.

POST /api/v2/project/111/dataset/222/images/query/?use_dataset_filters=true (false by default)

if use_dataset_filters=true and dataset.flag_filters is incompatible with query request body, then return empty list
-> implies that the two filters are applied one by one

**Comment by zonia3000** [comment]
Some screenshots of the new features:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/8292edda-8f76-4fe5-ba32-f0ce037bd219)

If the table is too big (or the window is small) the "All images / Dataset filters" switch has a CSS class that keeps it always visible on the bottom of the window:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/2a3460da-731e-401e-9700-7d09dace6bec)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/4534b509-216f-4769-8c56-206584171d92)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/76623350-e5cc-40d7-b7d7-993dc55f08e1)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/5d250aad-6d2f-413f-84a9-bec4c5baf31b)

---

@tcompa @ychiucco 

I've noticed that the flag filter works correctly for the `True` value but in case of `False` it detects both false and null values. Is that correct?

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/c621fede-e466-47ba-aa46-98ea4e5c7ae7)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/edd32d15-f52e-4b50-81aa-83b68fe67527)

Some other considerations:

* there are some cases when I think the current page should be updated from the backend. I'm doing it on the frontend now, but it implies an extra call in the second example:
    * example 1: current_page is `n>1` and I'm deleting the last element of that page; the current page should go back to `n-1`
    * example 2: current_page is `n>1` and I'm adding some filters that restrict the numbers of results so that the number of pages decreases; the current page should go back to the last page.
* When adding a new image should the user specify the zarr_dir prefix? Currently the endpoint accepts any path.

**Comment by jluethi** [comment]
> If the table is too big (or the window is small) the "All images / Dataset filters" switch has a CSS class that keeps it always visible on the bottom of the window:

🎉

> I've noticed that the flag filter works correctly for the True value but in case of False it detects both false and null values. Is that correct?

That's an interesting question (and likely a backend one). Generally, None is being treated as defaulting to False, so that seems fine.

I'm not sure whether we've discussed the scenario a lot where we have the flag set as True for some entries, False for some and None for others. We were mostly focused on the scenarios where we'd have True/False or True/None.
I'll have to think whether there are scenarios where this would need to be handled in a special way. I could imagine it being useful to filter separately in the web interface especially when manually correcting some mistakes or making entries. But I'm not sure whether it's needed in other scenarios.


> When adding a new image should the user specify the zarr_dir prefix? Currently the endpoint accepts any path.

That's a good larger question. The broader question: Do we allow images in the image list of a dataset with different zarr_dirs? My initial thought is no. If a user has Zarrs in different base directories, they should use different datasets.
The zarr_dir is typically set by the user during dataset creation and could be a base folder with multiple Zarrs.

From a user perspective, given that the other paths are shown in the interface relative to the zarr_dir => it would be nice to be able to just enter the relative path, but it being treated as the full path afterwards.
(e.g. I enter img5, but the object then has path "/tmp/img5")

> there are some cases when I think the current page should be updated from the backend

Not sure I follow along on this, so no comment from my side.

**Comment by jluethi** [comment]
Layout-wise: zarr_dir is in the info pane, so may not need to be on the main image list page

**Comment by jluethi** [comment]
We're already covering some of those wishes in current main, I think IL1, 3, 4 & 7 are covered.
I haven't tested IL2 (scaling to many images), the pagination looks very promising for this! Has anyone tested with e.g. 1000 entries?

-----

I have some new wishes on layout changes coming though, all starting from this current layout:

<img width="1241" alt="Screenshot 2024-04-11 at 17 43 12" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/d438295c-4070-46ff-843e-5b14124fd2f5">

P1: I don't think the Zarr URL box currently does anything. If one clicks "Add an image list entry", a new modal opens that asks for all the parts. I think that's a better interface => let's just drop the "Zarr URL" box
P2: Let's move the "Add an image list entry" to the bottom (e.g. bottom right). I like that it's grey like this, as we don't really encourage users using it too much :)
P3: I would like the filters to be more associated with the table if possible
P4: Do we need the "Search Images" button or could we trigger a search whenever a selection is updated? [Performance question, I don't know the answer]. Also, can we make the reset button non-colored when no selection is made? Finally, can we move those buttons (depending on where dropdowns go, e.g. also to the bottom of the image list)?
P5: Can we move the pagination & page selector to the same height as All images, Dataset filters to make the chrome more compact and us being able to show more images at once (at least when the page is wide enough)?
IL5: We should eventually add an edit button to the options. I'm fine with those buttons then just being red bin, blue arrow for edit without text to keep the table compact.

I sketched a (rough) potential new layout of the page. The main idea is that the image list would fill more of the page (and thus not just be surrounded by empty white space, but more image list entries in a regular setting). See Image List Round 2 Figma board: https://www.figma.com/file/n5CzmEcOadzSlMkUkA9Lut/Fractal-Web-Workflow-Monitoring?type=design&node-id=0-1&mode=design&t=oonK8eTq4OGA6mcj-0

Step 1:
No selection has been made:
<img width="929" alt="Screenshot 2024-04-11 at 17 56 39" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/73c18ae2-554e-49d8-a3ca-617f8584ecb9">

Step 2:
A user selects some dropdowns (but hasn't applied the search yet, because maybe the search is quite slow)
<img width="913" alt="Screenshot 2024-04-11 at 17 57 08" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/c412b914-7892-4287-b168-a0761a67a9de">

Step 3:
The user has applied the search. Some images aren't shown anymore & the reset button becomes active
<img width="912" alt="Screenshot 2024-04-11 at 17 58 37" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/687f8f82-b15b-4185-96c8-8a95373b22f2">

**Comment by jluethi** [comment]
While I'm adding wishes here:
For the search dropdowns per attribute, the design from the job page would be nice:
![Screenshot 2024-04-12 at 16 03 27](https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/001ed91e-98fa-4d2d-8200-43a7cd28e8d1)

Compact dropdown with search box when expanded. The search box would be great as a user could e.g. have 384 wells.
Also, would be great to have those dropdowns sorted alphabetically

For types, a search-box would be overkill, as it's only ever True, False or no filter applied

**Comment by jluethi** [comment]
For the image list table view, the zarr_url takes in a lot of space, even when the window gets narrower.

<img width="1023" alt="Screenshot 2024-04-15 at 15 16 10" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/faa3016d-f160-4e30-98ed-cb921d735490">

Can we make it go to multiple lines like e.g. the plate attribute?

**Comment by zonia3000** [comment]
Some screenshot of the new layout (#452):

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/6471d378-c9b2-4f0c-811e-ddebf9c9fb92)

Filter is applied:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/1ec9141e-03ab-4971-9aa8-7a2910e87667)

Zarr URL goes multiline:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/81d1bdb8-e6c9-437f-a76f-6888a384638e)

Attributes can be searched:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/0d6c66e8-59da-48da-8e65-3ed488b11006)

**Comment by jluethi** [comment]
This looks great, thanks @zonia3000 ! Love the vertical compactness!

One minor point:
Can the apply button only be active when there is a new change to apply? e.g. a user selected something from the dropdown, but hasn't clicked apply yet?

**Comment by tcompa** [comment]
https://github.com/fractal-analytics-platform/fractal-web/issues/428#issuecomment-2058513614 is now fixed (I think as part of https://github.com/fractal-analytics-platform/fractal-web/pull/452).

I marked a few more tasks in the first comment as "done", and moved the remaining ones to new issues.

Closing.
