### ISSUE TITLE
Exclude V1/V2 reserved arguments from JSON-schema-based form

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#429]
(just a quick note, since it came up during testing)

In V1 we have a block like
```js
export function stripSchemaProperties(schema) {
	const ignoreProperties = ['input_paths', 'output_path', 'metadata', 'component'];
	Object.keys(schema.properties).forEach((k) => {
		if (ignoreProperties.includes(k)) {
			delete schema.properties[k];
		}
	});
	if (schema.required) {
		schema.required = schema.required.filter((k) => !ignoreProperties.includes(k));
	}
}
```

For a V2 WorkflowTask this changes depending on the `workflowtask.is_legacy_task` boolean flag.
When we are using a legacy task (`workflowtask.is_legacy_task=true`), then the `ignoreProperties` array is the same as in V1.
When we are using a current task (`workflowtask.is_legacy_task=false`), then the `ignoreProperties` array is `['path', 'paths', 'init_args', 'zarr_dir']`.

(there may be minor changes in the actual values in the list, but for sure it will differ from what we have in V1)

**Comment by zonia3000** [comment]
Done in dc7e2dacc7b297e00284f1bcde25cfc384b4789b.
