### ISSUE TITLE
Create a new dataset associated to the current project in context

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#43]

**Comment by rkpasia** [comment]
Which version of the fractal server are you experiencing this with? I'm currently in `1.1.0a0` and no error shows up in the server validation if the request sent to the server has the following body:

```
{
  "name":"test",
  "project_id":"1",
  "type":"",
  "meta":{},
  "read_only":false
}
```

**Comment by tcompa** [comment]
You're right, this is a very recent update to fractal-server - available starting from `1.1.0a2`.

**Comment by tcompa** [comment]
Ref: https://github.com/fractal-analytics-platform/fractal-web/issues/51

**Comment by tcompa** [comment]
For the moment, we do not set (nor send) the `type` attribute.
To be fixed later, so that the user has the possibility of setting it
