### ISSUE TITLE
In task-view modal, always place args_schema attributes last

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#435]
The "Args Schema Version", "Args Schema non parallel" and "Args Schema parallel" should be listed last. The reason is that they are often very verbose, and it is not very frequent that one wants to go and read them in detail (while e.g. the docs_info property may be more relevant).

Changing the order of properties would help. Another (concurrent?) solution is to make the args-schema blocks collapsible (and collapsed by default).

**Comment by zonia3000** [comment]
Is this ok?

Compound task with args schemas collapsed:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/ba11b628-fecd-44e1-9902-11a19b1c3f09)

Compound task with args schema expanded:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/5192e0fc-004e-43e8-b9f5-a5ac91520406)

Compound task without optional fields:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/605394c1-2df7-4219-aed0-e6bf2972319b)

**Comment by tcompa** [comment]
Looks good to me!

**Comment by jluethi** [comment]
Looks great!

**Comment by zonia3000** [comment]
Done in #434
