### ISSUE TITLE
Support adding `input_filters` to a V2 WorkflowTask

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#437]
## Context

In V2, a WorkflowTask also has an attribute `input_filters`, which may look like
```json
{
  "types": {"is_3D": true},
  "attributes": {"well": "B03"}
}
```

This attribute is relevant for an advanced use case, where the user wants to override the default running flow of a workflow. By default, the runner selects which images will be processed based on the `task.input_types` and `dataset.filters` values, but if `workflowtask.input_types` is set then it takes highest priority.
Some use cases we have in mind:
1. The 3rd task of a workflow produces 2D images from 3D ones, thus setting `dataset.filters = {"type": {"is_3D": false}}`, but we want the 4th task to run on the original 3D images.
2. The user has converted a large multi-well plate to zarr, but they want to run a task on a single well. Caveat: this running modality is supported, but we did not review how it would look like e.g. in the workflow-task status.

## Feature

As a first version, we could do as follows:
1. We do not include `input_filters` in the task-insertion modal (that is, in the request body of the `POST /api/v2/project/{project_id}/workflow/{workflow_id}/wftask/` endpoint). This is mostly to avoid making the modal too complex (also in view of #1328), but if we find a nice way to include this option as a "hidden" advanced option I have nothing against it.
3. We treat the `workflowtask.input_filters` property in a dedicated tab (as we do for the "meta" properties):
    * The tab includes a form where `input_filters` can be modified, which then triggers a call to `PATCH /api/v2/project/{project_id}/workflow/{workflow_id}/wftask/{workflow_task_id}/`. Note that the structure of `input_filters` is the same as for `dataset.filters`: the `types` property is an object with boolean values, while the `attributes` property is an object with scalar non-null values.
    * Above the form, we include a brief explanation of when this attribute may be useful.

**Comment by tcompa** [comment]
As a reminder: in the PATCH call, the value of `input_filters` in the request body will _replace_ the original value in the db. Therefore it should include the whole new object, and not just the parts that were modified.

**Comment by jluethi** [comment]
> 2. We treat the workflowtask.input_filters property in a dedicated tab 

I'd go with this option 2 for the beginning

**Comment by tcompa** [comment]
> I'd go with this option 2 for the beginning

Points 1 and 2 are both part of the same option ;)

That is, I propose that the `input_filters` is only available in a dedicated tab (as described in point 2), and not in the insert-task modal (as described in point 1).

**Comment by jluethi** [comment]
Thanks for clarifying. Fully agree with this design choice, it doesn't need to be part of adding a task :)

**Comment by zonia3000** [comment]
Input filters tab:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/12725640-e0de-468d-a5ec-2bc955e8c532)

**Comment by tcompa** [comment]
(with @zonia3000)

We can add a feature that offers existing options (via dropdown menus) for adding one or many new attributes based on the image list. Once a new attribute is added in this way, it will be of the same "kind" as one that the user added manually (by setting an arbitrary key-value pair).

For the moment, let's start by slightly separating the new feature (i.e. adding an existing attribute), with a button like "Add an attribute from the image list" (wording TBD) that triggers the opening of a modal where this feature is implemented.

The reason for separating this feature from the main one is that it seems complex to mix the two kinds of interactions.

Note: This feature is only available when a given dataset was selected (ref #445).

 
(the same holds for types)

**Comment by jluethi** [comment]
Sounds good, approach approved! :)

**Comment by tcompa** [comment]
> The buttons open a modal that allow to select the key and the value of the attribute/type to insert:
> 
> ![image](https://private-user-images.githubusercontent.com/5459334/322871784-a738519c-67ce-4048-ab94-d0f03d889b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzg3NDcsIm5iZiI6MTcxMzMzODQ0NywicGF0aCI6Ii81NDU5MzM0LzMyMjg3MTc4NC1hNzM4NTE5Yy02N2NlLTQwNDgtYWI5NC1kMGYwM2Q4ODliOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMDcyMDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNjNjI0MTQxNzZkMDMzMTdmZTYzNDNlYTdhZWZhNDNhYjJkZjQ4ZmIxMzZhYTg5OTMzYzFmNWI4ZmYxMGYwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rrLUw4UdqmGJJEMitaukdkk-LrttKSo53pCxItU6wz4)

Minor typo: "Attribute key" -> "Attribute value"

**Comment by zonia3000** [comment]
> Is there some warning if they leave without saving? If so, then this is fine by me.

I've added a modal similar to the one that warns the user about arg unsaved changes. This is for the input filters tab:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/5000f06a-1edd-4bc1-aa38-1b5edfba00df)

**Comment by jluethi** [comment]
Looks good to me!
