### ISSUE TITLE
Changing how we display booleans

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#439]
Currently, we display booleans as:

<img width="88" alt="Screenshot 2024-04-11 at 13 40 57" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/fe5e0716-dd23-4642-ba72-9de438c1dac3">

This often leads to user confusion because they can reasonably think: "I need to check this box to make the variable false".

Can we come up with a better way of showing them? The v2 transition would be good for such a change.

e.g. just show the checkbox without text? Or does anyone have a better idea for displaying this?

**Comment by zonia3000** [comment]
In the new Task V1/V2 compatibility page I've used these switches:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/4331beb0-c406-40e2-92cf-dba3871fc3b9)

Do you think they could be a good alternative to the checkbox?

**Comment by jluethi** [comment]
Ah yes, I like them much more!

**Comment by jluethi** [comment]
> An example of the switch inside the arguments form modal:

Great, let's go with that!

> This is a version with the switch

I think the switch is simpler than the dropdown when setting this. I would keep the dropdown e.g. in the search boxes, but would be nice to also switch to the switches for types.
