### ISSUE TITLE
Make dataset filters editable

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#441]
As a user, I should be able to edit the current dataset filters.
For example, if there is a filter for is_3D = False, I should be able to remove this filter or set it for is_3D=True

**Comment by jluethi** [comment]
Just discovered that I can edit the filters on the project page by clicking edit
<img width="1519" alt="Screenshot 2024-04-11 at 17 13 37" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/40c38913-afed-4b34-a28a-402c5ec84619">

but cannot modify them from the dataset page filter modal itself:
<img width="1519" alt="Screenshot 2024-04-11 at 17 14 01" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/56ae5d3d-b2fa-4113-bd7a-f2c8574a235a">

Could we make the dataset filters modal more like the edit modal above?

**Comment by tcompa** [comment]
Let's include the edit feature in the single-dataset page modal.

---
Broader question: is it still relevant to have the dataset-related features split/duplicated in two places? TBD

**Comment by jluethi** [comment]
> Broader question: is it still relevant to have the dataset-related features split/duplicated in two places? TBD

Very good question! I think we could drop the existing edit panel and just have it in the dataset itself. I would imagine we'd have basically the current edit panel as the instead of the info panel on the dataset page. The only complexity:
When is the zarr_dir something the user can modify?
My first-level take-away: Before there are any entries in the image list, it can be modified. Afterwards, it's not something the user can change anymore

**Comment by tcompa** [comment]
The zarr-dir-edit part is a backend issue: https://github.com/fractal-analytics-platform/fractal-server/issues/1385

**Comment by tcompa** [comment]
> I think we could drop the existing edit panel and just have it in the dataset itself.

Does this mean fully removing this "Edit" blue button?
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/cbe6b31b-de62-457a-90d6-3156cae9d2fb)

**Comment by tcompa** [comment]
> Does this mean fully removing this "Edit" blue button?

If so, then we suggest that creating a dataset also redirects to the newly-created-dataset page (as we do for workflows).

**Comment by jluethi** [comment]
Yes, I think we can fully remove the blue edit button.
The functionality would then be split between the Info pane & the filter modal in the dataset itself. Modifying dataset name and (in the beginning) zarr_dir is in the info modal. And anything filter related is in the filter modal.

> If so, then we suggest that creating a dataset also redirects to the newly-created-dataset page (as we do for workflows).

I would not do this for the moment. A typical user flow is:
I create my dataset. At that moment, the dataset doesn't contain any meaningful information besides the zarr_dir & its name, which are both set during the creation modal (empty image list, no filters set unless done in creation modal).
The user then wants to create their workflow.

Being sent to a basically empty dataset page would not add value in my opinion.

In the spirit of streamlining, we may in the future expose the option to add a dataset with a given zarr_dir directly during project creation to get a default dataset. But let's hold off on that for the time being.

**Comment by zonia3000** [comment]
Dataset filters are editable from dataset page:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/b97bd19e-5bca-4f65-850a-25074e265eda)

Dataset name and Zarr dir are editable from info modal:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/9bf7f086-86f4-4da0-925e-4a5711a33492)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/b3f2fecf-c5cc-4ba8-9389-18a87d56ff25)

Edit button has been removed from the dataset list:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/2ad0e430-9138-4093-ba9e-4829eeb6208f)
