### ISSUE TITLE
Deleting image list entries should inform that now images get deleted

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#444]
It's very nice that we can edit the image list. The following dialogue is not very clear yet though:
<img width="1519" alt="Screenshot 2024-04-11 at 17 15 07" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/3d7eecc0-35d9-431a-af4a-efb12c8abe9c">

This appears as if the image data on disk would get deleted, but it's only about removing it from the database.

Suggested rewording:
In red box: "The following image is about to be removed from the Fractal image list: /path/to/image"

Below the red box:
"This does not remove the actual image data from disk, it just removes it from the Fractal database"
"Do you confirm?"

PS: We can of course discuss whether a future Fractal version would then be able to delete the actual image from disk as well. That would be non-trivial though (needs to be done as the user, not as Fractal), so let's not get into this now

**Comment by zonia3000** [comment]
This is the new modal:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/0d57ec0f-4af6-4998-bf46-55ff223ae113)

**Comment by jluethi** [comment]
Looks great!
