### ISSUE TITLE
Should we add an help message to the insert-legacy-task feature?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#451]
As of #450, this is the task-insertion modal:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/2436f1e2-2e13-439f-b5b7-a312baff6c69)

Something that I guess could happen is that a user expects to find their V1 tasks in the list, but they are not. W could add a small help message (possibly requiring a click on a "help" or "info" button/link), that says something like "Only certain legacy tasks can be run within the new Fractal (see link): if you want to add one of yours, ask an admin".

Opinions?

**Comment by jluethi** [comment]
Agreed with the addition & the wording! :)

**Comment by zonia3000** [comment]
Is this good? It uses the same icon of the workflow arguments popovers.

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/485e2be0-ab44-4e2e-acc0-e786dc930d9d)

@tcompa What link should I put in the message?

**Comment by tcompa** [comment]
> What link should I put in the message?

My bad: I was thinking about what is currently part of the v2 admin area, but this page is not visible to users. I would just remove the link.

Other than that, this looks good to me

**Comment by jluethi** [comment]
Great! Without the link and then we can merge this in!
