### ISSUE TITLE
Add import/export-dataset features

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#456]
# Export

Endpoint:
```
GET /api/v2/project/{project_id}/dataset/{dataset_id}/export/
```

Response-body model:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/ff623370-1d7f-461a-8680-f4c57b6e28c3)

# Import

Endpoint:
```
POST /api/v2/project/{project_id}/dataset/import/
```

Request-body model:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/3f1761e8-898c-46e3-aad8-ad79c874d1b8)

Response-body model: same as the standard POST/GET dataset endpoints.

**Comment by tcompa** [comment]
Refs:
* https://github.com/fractal-analytics-platform/fractal-server/pull/1407
* https://github.com/fractal-analytics-platform/fractal-server/issues/1402

**Comment by zonia3000** [comment]
Create dataset modal changes depending on a switch.

Using "Create new":

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/e0c72bb8-60cc-4b41-b799-ccc996d95daf)

Using "Import from file":

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/0d7355d8-df10-4205-995f-ee20bf76ca60)

The name field in this case is optional and it overrides the name during the import.

On the dataset page the export dataset button is located on the top right, as the last button. It uses the same icon of the export workflow button.

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/6556864a-f2f1-4616-9d10-4fda4ca6e113)

**Comment by jluethi** [comment]
This looks great!
