### ISSUE TITLE
Hide advanced options on workflow submission modal

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#458]
We have some options that are rarely used on the workflow submission modal:
The worker initialization and (optionally, when set for the user) the slurm account. Let's hide those options in an "advanced" section that is not expanded by default.

<img width="1074" alt="Screenshot 2024-04-17 at 18 31 12" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/4497ed6d-8731-40d6-9977-430f94d9b765">

Given that the dataset is now selected on the workflow page, I'd be curious whether it makes sense to also remove it from the workflow submission modal. Not 100% sure yet whether it's useful to show that again (given that it's critical information) or better to not show it again.

**Comment by zonia3000** [comment]
Advanced Options collapsed:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/c32a3211-445f-48af-800a-e8e84fe2505b)

Advanced Options expanded:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/daf5e760-33a8-44a2-bab2-20e9dc9c5543)

**Comment by jluethi** [comment]
Awesome, that looks great!
