### ISSUE TITLE
Empty workflow list

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#46]
I know that this is still in progress, but perhaps it's useful to already let @rkpasia know that https://github.com/fractal-analytics-platform/fractal-web/commit/d16ec352bbbf8235d72acc67b39b475b67f8ff8b is not yet working.

1. I create a project (say `project_id=4` and add a workflow to it (via the command-line client).
2. I browse to `http://localhost:5173/projects/4`
3. The list of datasets is correct, but the list of workflows is empty.

Notice that the API call
```
INFO:     127.0.0.1:39126 - "GET /api/v1/project/4 HTTP/1.1" 200 OK
```
correctly return a non-empty list of projects (when triggered through the command-line client).

**Comment by rkpasia** [comment]
Which version of fractal server are you using?
Do you notice any errors printed in the browser console?

**Comment by tcompa** [comment]
I was probably using some older commit. As of d16ec352bbbf8235d72acc67b39b475b67f8ff8b, it does work as expected.
