### ISSUE TITLE
IL2: As a user, I want the image list browsing to scale to many entries.

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#461]
By @jluethi:

> We want to allow the user to navigate this list of typically dozens, but potentially 10s of thousands of entries => this browsing needs to scale. In many cases, users will have 1-100 entries of that list, but some users may have 30’000 entries. => done with pagination? I haven't tested it myself yet

**Comment by jluethi** [comment]
Confirmed to be working well when I processed a 1536 well plate & then browsed the image list.
