### ISSUE TITLE
How to set default starting task when continuing a workflow execution

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#464]
Say we have a workflow task list that includes 4 tasks. Each one of them has a status which can be
* done
* failed
* submitted
* `-` (not present in the API response)

Let's go through a few scenarios, and determine what is the expected default for where the workflow should restart from. If this logic is a function of a (wftask_id, wftask_status) list, then I think this feature should be implemented directly in the frontend.

Of course it relies on what are the specification for the get-status endpoint, which easily hit edge cases when the task list is modified (see https://github.com/fractal-analytics-platform/fractal-server/issues/1083#issuecomment-2063898906). Those edge cases often propagate into the current issue.

### A

I deleted all tasks that already ran:

1 -
2 -
3 -
4 -

Proposed first task: 1
(but this likely a case where we do not offer a "continue" feature, then it's not very relevant - see #440)

### B

I only ran two tasks:

1 done
2 done
3 -
4 -

Proposed first task: 3

### C

I ran three tasks, and the third one failed:

1 done
2 done
3 failed
4 -

Proposed first task: 3

### D

By playing with the task list, the task that failed is not the last one:

1 done
2 failed
3 done
4 -

Proposed first task: 2

### E

By playing with the task list, I create a "hole":

1 done
2 -
3 done
4 -

Proposed first task: 2

### F

By playing with the task list, I create a "hole" and then a failed task:

1 done
2 -
3 failed
4 -

Proposed first task: 2

### G

1 done
2 done
3 done
4 done

Proposed first task: 4 or none?

### H

1 submitted
2 failed
3 -
4 -

Proposed first task: N/A, because we cannot re-submit while something is running.

### I

Anything else? I listed the first ones coming to mind.

---

Note that the basic logic I used, above, is that `-` and `failed` are treated in the same way. I cannot say yet whether this always holds.

---

Independently on how far we go in covering edge cases, we could also make this feature "soft" as in "if the scenario does not fall into a list of supported cases, then do not propose any specific first task but highlight the first-taks-selection element".

**Comment by jluethi** [comment]
Great overview @tcompa , fully agree!

> G: Proposed first task: 4 or none?

Agreed, not that clear. There isn't really a meaningful default here.

> Note that the basic logic I used, above, is that - and failed are treated in the same way. I cannot say yet whether this always holds.

Seems reasonable as a heuristic to me.

> Independently on how far we go in covering edge cases, we could also make this feature "soft" as in "if the scenario does not fall into a list of supported cases, then do not propose any specific first task but highlight the first-taks-selection element".

I'm a fan of that! In general, this is just about providing a default and 90% of cases where this is used should be case B or C from above. I like the other proposals as defaults. But anything that gets confusing => no default set seems reasonable.
If we can even highlight the selection part in that case, even better!

**Comment by tcompa** [comment]
The current issue concerns the "continue workflow" scenario from https://github.com/fractal-analytics-platform/fractal-web/issues/440.

Based on the current issue, we will have a default first task set - whenever we find one.
To be defined (cc @jluethi): what should we do when no default first task is found? (e.g for case number 4 above)

Options

A. The user must select a starting task, or they cannot proceed and submit
B. The user may select a starting task, but if they don't then they can submit anyway (and the backed will default to the first task in the workflow)

I'd rather go with A.

**Comment by jluethi** [comment]
Agree, I like Option A better. This makes the starting task non-optional.

It's not technically needed to make the starting task non-optional, but I agree that it makes for a better web user experience!
