### ISSUE TITLE
Continue Workflow Dialogue: Highlight First task when no default is present

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#468]
The Continue Workflow modal is currently not very obvious if there is no default first task selected. The run button is greyed out, because no first task is selected and that's required. We should highlight the missing field better (bold, red or something).

The reason no default for the First Task was chosen here is that the workflow had finished, so there wasn't an obvious default (=> makes sense!). But we should highlight it to the user where input is required.

<img width="504" alt="Screenshot 2024-04-24 at 14 56 33" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/9a501e93-1e2f-485d-8b93-23bac6835315">

Just for reference, when only a partial workflow was run, the modal correctly defaults to the next task, and then all the current behavior makes sense and we don't want to highlight the First task selection more.
<img width="1754" alt="Screenshot 2024-04-24 at 15 02 43" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/9a65f097-21c5-4368-b200-74003086bc76">

**Comment by zonia3000** [comment]
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/8b0304ca-7a20-47c9-b3e7-14a6792a02a5)

**Comment by jluethi** [comment]
That's great!
