### ISSUE TITLE
In Workflow Task page, rename titles for non-parallel & parallel

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#469]
Currently, the titles for the parameters are shown as `Args non parallel` and `Args parallel`. This is not very intuitive for users. Let's rename them to:

1. Initialisation Parameters
2. Compute Parameters

<img width="1644" alt="Screenshot 2024-04-24 at 16 12 33" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/0f87d2a4-196a-4b0a-873e-3eddaaaa07ad">

**Comment by jluethi** [comment]
I like the layout with the new titles for compound tasks. For parallel or non-parallel tasks: I don't see a reason to show those titles like `Compute Parameters`.

See:

<img width="1525" alt="Screenshot 2024-04-25 at 10 40 52" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/069facb4-33a0-4bc5-949e-7a5c7d4dfb9a">

My goal:
Compound tasks have titles Initialisation Parameters & Compute Parameters for the 2 sections. Other tasks don't have titles for sections.

**Comment by zonia3000** [comment]
What about a compound task having one of the two sections empty (like in #470)? Should we display only one section title or nothing?

**Comment by jluethi** [comment]
> What about a compound task having one of the two sections empty (like in https://github.com/fractal-analytics-platform/fractal-web/issues/470)? Should we display only one section title or nothing?

In that case, let's display nothing for that section

**Comment by zonia3000** [comment]
> In that case, let's display nothing for that section

I had already done that. But I was wondering if I have to hide the title also from the section that has parameters, since there is only one section.

For example, the following is a compound task, but only one section has parameters:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/854f7721-ed2f-45cb-9e66-58e3ced2553b)

**Comment by jluethi** [comment]
Ah, good question.

I think for the interface, it makes sense that we don't show the title for either section in that case.

That means, we just show those titles if there are actually 2 separate sections.

**Comment by zonia3000** [comment]
Ok, thanks. So it's working in that way with 0d49ca4e45d565ffacc867b2c0fac689a6a441dd.
