### ISSUE TITLE
Starting the web service triggers a `whoami` with wrong parameters

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#47]
Upon start of the web service, the server logs show:
`INFO:     127.0.0.1:63408 - "GET /auth/whoami HTTP/1.1" 401 Unauthorized`

It looks like it checks the whoami before the user logs in

Minor issue, doesn't break anything :)

This is on current main (c92e3318c429ac538629b6acff33656de47e88e4)

**Comment by rkpasia** [comment]
This should be checked by 54371df0
