### ISSUE TITLE
Include v1/v2 switcher in all admin-area pages

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#478]
As an admin, it's useful to go back and forth between v1 and v2 admin-area jobs pages (e.g. to check whether something is running). Right now, it requires several steps (going back to the home page and then to the legacy section and then to the admin area and then to the jobs page). I suggest we include the switcher in all admin-area pages.

**Comment by jluethi** [comment]
+1 on that
