### ISSUE TITLE
Expand `detail` property of 4xx response body

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#483]
When hitting an API error, how do we typically display it?

In the case below (422 response for task deletion), we are showing the full response body - although what matters is actually the `detail` property. This also means that newlines are not expanded.

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/84e3f285-df36-4a9d-99bd-9e3179ddc5e9)
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/bd8d84c3-1017-4bb0-9888-e1336390e448)

---

I'm wondering if it would be a good idea to do the following: once a 4xx response is received, check whether body has a single `detail` property and no other properties. If so, only show the value of this property, rather than `{"detail": somethings}`. Is it a reasonable suggestion? TBD

**Comment by zonia3000** [comment]
Improved error format:

![image](https://github.com/user-attachments/assets/532f1438-4606-4b07-bfc2-a38153dd933d)

**Comment by jluethi** [comment]
This is a great improvement! :)

**Comment by tcompa** [comment]
Great!
Minor detail: would it make sense replace "\n" with newlines?

**Comment by zonia3000** [comment]
Replacing the newlines it looks in the following way:
![image](https://github.com/user-attachments/assets/5b8e94ba-0e2a-48c4-9b22-df34ff5b517a)
