### ISSUE TITLE
Remove log from `handleFetch`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#487]
Long time ago I added the following log:
```
Including cookie into request to http://..., via handleFetch
```
(due to https://github.com/fractal-analytics-platform/fractal-web/issues/274, and fixed with https://github.com/fractal-analytics-platform/fractal-web/pull/275/files)

This log line is very frequent, but not very informative. Let's either place it at a "debug" logging level (if this works like in Python), or simply remove it.

**Comment by zonia3000** [comment]
Set this to `trace` level (lower than debug)
