### ISSUE TITLE
Project creation error message persists even when new project is created successfully afterwards

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#49]
If there is an error message during project creation (e.g. https://github.com/fractal-analytics-platform/fractal-web/issues/48), this error message persists. Even if the user then corrects the error (e.g. provides a unique name with an existing project directory), the old error message is still displayed.

This makes it appear as if the new operation had failed. Instead, the new operation worked.

I think this error messages should disappear when a user reruns the action

**Comment by rkpasia** [comment]
This is closed by 87a7abea901c6a524508650a1097913403bda836 with reference to b6ca50b381ff3ccb6635493c37d17c9ce16c6466 will be merged when #38 closes.
