### ISSUE TITLE
Handle 404 for job-log download

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#493]
I am on the admin/jobs page
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/1d802460-6c4a-4346-bbd7-61b4a964c3e0)
I click the download-logs button, and get a 404 on this backend endpoint
```
2024-05-23 09:33:34,183 - uvicorn.access - INFO - 172.19.0.1:58410 - "GET /admin/job/2/download/ HTTP/1.1" 404
```

I was expecting to see an error message somewhere, but nothing appears.
Web-client logs do not show anything special
```
[2024-05-23T11:33:34.182] [INFO] (hooks) - [GET] - /api/admin/job/2/download
[2024-05-23T11:33:34.182] [TRACE] (proxy) - [GET] /admin/job/2/download/
```

---

(I did not investigate why the backend is sending 404, for the moment)

**Comment by tcompa** [comment]
> (I did not investigate why the backend is sending 404, for the moment)

The endpoint is probably lacking a `v2`. It should be `/admin/v2/job/{job_id}/download/`.

**Comment by tcompa** [comment]
The original comment was with Firefox, here is how it looks in Chrome:
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/f3a58106-aed3-4518-b60f-0dcaefa3f09a)

**Comment by zonia3000** [comment]
It's not possible to intercept via JavaScript a standard download (triggered by the user clicking on a `<a href="..." download />` tag), so there is no way to display a custom error message in this situation. The browser should be responsible to handle this situation.

As in the screenshot of @tcompa comment, Chrome correctly handles it, so this can be considered a Firefox bug, indeed there is one opened about this some months ago: [Anchor (link) with download attribute: no feedback for non HTTP 200 code](https://bugzilla.mozilla.org/show_bug.cgi?id=1876043).

A possible mitigation consists in adding a `target="_blank"` attribute on the link. In that case the browser will always open a new window and a possible error will be displayed (currently in JSON format). In case of successful file download the browser will automatically close that tab at the end of the download (tested with Chrome and Firefox).
