### ISSUE TITLE
Updating workflow tasks to new version fails in Fractal legacy

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#499]
I can no longer update workflow tasks to a newer version in Fractal legacy. Can we have a look on what may have broken there?

I get errors like:
<img width="1434" alt="Screenshot 2024-05-28 at 14 34 47" src="https://github.com/fractal-analytics-platform/fractal-server/assets/18033446/701ff750-9859-48f9-8d3c-ae7a412f7cc3">

Sometimes it says Project not found, sometimes it says not allowed for project 2.

Does it maybe look in the V2 projects?

**Comment by zonia3000** [comment]
Just received another "Not allowed on project" during tests, while trying to create the second dataset in a v1 project:

![test-failed-1](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/02d93fd7-1ba1-4526-8383-4e213f27fe9e)

I had enabled the sqlalchemy logs and I see that there is a rollback just before the forbidden:

```
INFO:sqlalchemy.engine.Engine:SELECT linkuserproject.project_id AS linkuserproject_project_id, linkuserproject.user_id AS linkuserproject_user_id
FROM linkuserproject
WHERE linkuserproject.project_id = $1::INTEGER AND linkuserproject.user_id = $2::INTEGER
2024-05-29 09:18:21,544 INFO sqlalchemy.engine.Engine [cached since 37.68s ago] (11, 1)
INFO:sqlalchemy.engine.Engine:[cached since 37.68s ago] (11, 1)
2024-05-29 09:18:21,544 INFO sqlalchemy.engine.Engine ROLLBACK
INFO:sqlalchemy.engine.Engine:ROLLBACK
INFO:     127.0.0.1:36236 - "POST /api/v1/project/11/dataset/ HTTP/1.1" 403 Forbidden
```

Here the list of v1 calls in that moment:

```
INFO:     127.0.0.1:36236 - "POST /api/v1/project/ HTTP/1.1" 201 Created
INFO:     127.0.0.1:40870 - "GET /api/v1/project/11/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:36236 - "GET /api/v1/project/11/dataset/?history=false HTTP/1.1" 200 OK
INFO:     127.0.0.1:40864 - "GET /api/v1/project/11/workflow/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:40864 - "GET /api/v1/task/?args_schema=false HTTP/1.1" 200 OK
INFO:     127.0.0.1:40864 - "POST /api/v1/project/11/dataset/ HTTP/1.1" 201 Created
INFO:     127.0.0.1:40864 - "POST /api/v1/project/11/dataset/16/resource/ HTTP/1.1" 201 Created
INFO:     127.0.0.1:36236 - "POST /api/v1/project/11/dataset/ HTTP/1.1" 403 Forbidden
```

I have the complete log if needed.
