### ISSUE TITLE
Write down install&deploy HOWTO

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#5]
Once this is sufficiently stable, let's write down the steps to install&deploy the testing version of fractal-web.

Most likely it will look like
* Make sure you have the required environment (this should be described in detail)
*  `git clone` this repository
* `npm install`
* Set the server's address environment variable
* `npm run` command
* (optional) encapsulate the run command in a daemon service

**Comment by tcompa** [comment]
I cleaned up the README a bit with PR #19.
@rkpasia feel free to improve it if needed, otherwise we can close this issue for the moment.

**Comment by rkpasia** [comment]
I've updated the README. Now it should include everything to run the client starting from the source code.
