### ISSUE TITLE
Running Fractal web 1.1.0 locally in node 19 fails

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#502]
Is Node 19 meant to be supported? I have been running everything in node 19 locally so far (I don't remember why I have that version installed).

With Fractal web 1.1.0, trying to run locally via

`npm run dev`

Leads to the following error:
```
> fractal-web@1.1.0 dev
> vite dev

✘ [ERROR] Cannot start service: Host version "0.18.20" does not match binary version "0.17.17"

1 error
failed to load config from /Users/joel/Library/CloudStorage/Dropbox/Joel/BioVisionCenter/Code/fractal/fractal-web/vite.config.js
error when starting dev server:
Error: The service was stopped
    at /Users/joel/Library/CloudStorage/Dropbox/Joel/BioVisionCenter/Code/fractal/fractal-web/node_modules/esbuild/lib/main.js:1083:25
    at responseCallbacks.<computed> (/Users/joel/Library/CloudStorage/Dropbox/Joel/BioVisionCenter/Code/fractal/fractal-web/node_modules/esbuild/lib/main.js:703:9)
    at Socket.afterClose (/Users/joel/Library/CloudStorage/Dropbox/Joel/BioVisionCenter/Code/fractal/fractal-web/node_modules/esbuild/lib/main.js:693:28)
    at Socket.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by jluethi** [comment]
Hmm, maybe that is an issue with something else in my configuration though. I hit the same error with the 1.0.0 version of Fractal web and that used to work in the past

**Comment by tcompa** [comment]
In general, I think it's helpful to remove `node_modules` and `build` folder and run `npm install` again.

**Comment by tcompa** [comment]
And this line

> Cannot start service: Host version "0.18.20" does not match binary version "0.17.17"

suggest that the issue is not with node 19

**Comment by jluethi** [comment]
> In general, I think it's helpful to remove node_modules and build folder and run npm install again.

Hmm, yes, this seems to have done the trick. 

I went through:
```
npm install esbuild@latest
npm install vite@latest
npm cache clean --force
rm -rf node_modules
npm install
```
(by Chat GPT instructions ;) ).

I assume the deleting the node modules folder may have been the helpful part here
