### ISSUE TITLE
Showing tuple parameters in workflow task page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#505]
I'm not 100% sure whether this is a manifest creation or Fractal web display issue. When a Fractal task has an input that's a tuple with multiple values, it's not displayed in the Workflow task.
The manifest looks reasonable to me, so I assume that's an issue with how we than handle the schema in Fractal web.

Example task parameters:
```
@validate_arguments
def rdcnet_segmentation_2d(
    *,
    # Fractal arguments
    input_paths: Sequence[str],
    output_path: str,
    component: str,
    metadata: Dict[str, Any],
    # Task-specific arguments
    level: int,
    channel: ChannelInputModel,
    model_path: str,
    input_ROI_table: str = "FOV_ROI_table",
    output_ROI_table: Optional[str] = None,
    output_label_name: Optional[str] = None,
    use_masks: bool = False,
    relabeling: bool = True,
    # RDCNet-related arguments
    core_count: int = 4,
    # 2D RDCNet-related arguments
    patch_size: tuple[int, int, int] = [1300, 1300, 1],         <= the relevant parameter
    overwrite: bool = True,
) -> Dict[str, Any]:

```

The relevant entry in the manifest:
``` 
"patch_size": {
      "title": "Patch Size",
      "default": [
        1300,
        1300,
        1
      ],
      "type": "array",
      "minItems": 3,
      "maxItems": 3,
      "items": [
        {
          "type": "integer"
        },
        {
          "type": "integer"
        },
        {
          "type": "integer"
        }
      ],
      "description": "Size of the patch, excluding border, see RDCNet documentation."
    },
```

How it gets displayed in Fractal web:

<img width="1614" alt="Screenshot 2024-06-04 at 21 28 01" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/25afad81-44ec-49d0-a7cf-cdd6d4bde7ba">

The default values aren't shown and one can not enter actual values, just add or remove items from the list.

------

@FranziskaMoos-FMI : I looked back at how I solved this in my original version of the task: I used list[int]. It's not optimal, as a user could mistakenly use a wrong number of elements, but it is displayed. See https://github.com/fmi-basel/isit/blob/044c66490de4f727087aac3c715226ab3f581ee1/isit/fractal/rdcnet_segmentation.py#L108

**Comment by zonia3000** [comment]
I'm adding the support for this.

This is how it looks using the current logic. Since the field is optional the add and remove buttons are present, so that one could decide to remove the values in order to set this property to empty (then converted to null):

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/a7d50277-b7e6-40d0-8020-99c54cbc0466)

I find this a bit misleading, since one could be in a situation like having just one input, when 3 is the fixed size. So, I propose to handle the `minItems` and `maxItems` case in a special way, to display something like this:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/c63e0664-15eb-4f04-89c8-308c6d7d3f0e)

There is a toggle button that adds or remove the whole tuple and then the remove buttons are renamed to "clear", since they just clear the input values, without removing them.

Otherwise, if the property is required, the add/remove tuple button is not shown and we have just the clear buttons.

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/fe5a725c-2797-4248-a352-c582fd12ea40)

**Comment by zonia3000** [comment]
Another question came up with @tcompa.

We are able to support tuples with elements having different types (number, string, ...).
In that case it might be wrong to rearrange the order of the items. So, should we disable the element sorting for tuples?

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/4ba8e3bc-b420-4539-9fe3-653f1f31da0a)

**Comment by jluethi** [comment]
This looks great!
For fixed-sized arrays (= our tuples), I'm in favor of removing the reordering functionality. The type argument is a good reason for it. It also looks better without it.

Also, showing number argument, string argument, boolean argument is helpful in debugging. But not something I'd show in the real interface if possible to avoid. These types aren't something the user cares about. And if a task developer wants to describe what the different inputs are in more detail, they can use e.g. a Pydantic model with a description of each field.

**Comment by zonia3000** [comment]
> Also, showing number argument, string argument, boolean argument is helpful in debugging. But not something I'd show in the real interface if possible to avoid.

Can I remove the default text in any case or you would like to have them visible only in development mode?

**Comment by jluethi** [comment]
I'd generally remove this kind of text on typing.

**Comment by tcompa** [comment]
I'm testing #509 with this schema (combining a tuple, an Enum, and a custom model):
```json
{
  "title": "TaskFunction",
  "type": "object",
  "properties": {
    "arg_A": {
      "title": "Arg A",
      "type": "array",
      "minItems": 4,
      "maxItems": 4,
      "items": [
        {
          "type": "string"
        },
        {
          "type": "integer"
        },
        {
          "$ref": "#/definitions/ColorA"
        },
        {
          "$ref": "#/definitions/MyModel"
        }
      ],
      "description": "Description of arg_A."
    }
  },
  "required": [
    "arg_A"
  ],
  "additionalProperties": false,
  "definitions": {
    "ColorA": {
      "title": "ColorA",
      "description": "An enumeration.",
      "enum": [
        "this-is-red",
        "this-is-green"
      ]
    },
    "MyModel": {
      "title": "MyModel",
      "description": "Description of MyModel",
      "type": "object",
      "properties": {
        "x": {
          "title": "X",
          "type": "integer"
        },
        "y": {
          "title": "Y",
          "type": "integer"
        }
      },
      "required": [
        "x"
      ]
    }
  }
}
```
and all looks as expected
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/6291f315-dffc-461c-9db3-65187d0a4c15)
