### ISSUE TITLE
Add info about JSON Schema sandbox in docs

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#506]
I think this is currently missing.
Also, we should specify that when this page is accessible (e.g. the difference between `npm run dev` and `npm run build; npm run preview`).

**Comment by zonia3000** [comment]
Is this good?

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/f17cae1e-718a-4859-bc49-43c5cdb264ce)
