### ISSUE TITLE
Display Optional Arguments that are `None` in grey

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#507]
Lorenzo and I just started using the sandbox for Json schemas. @zonia3000 super useful to test things!! 🎉

One idea that came up: Can we highlight better when Optional values are unset, e.g. when they are still None? The idea we had: If an Optional field is None (e.g. empty string), it is greyed out. If the user fills it in, it becomes regular black.

One example: The Cellpose task has an Optional `Output Roi Table` parameter. If it's unset, it could be greyed out, signaling to the user that this parameter isn't currently being used.

<img width="733" alt="Screenshot 2024-06-05 at 15 31 40" src="https://github.com/fractal-analytics-platform/fractal-web/assets/18033446/519c97bf-c8cc-4766-8531-124726fbfdd4">

Can we experiment with that?

**Comment by jluethi** [comment]
cc @lorenzocerrone

**Comment by zonia3000** [comment]
Is this good? 

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/963aa05c-e5b3-4f97-8c26-3c27d88556f8)

**Comment by jluethi** [comment]
@zonia3000 yes, this looks great! Let's go with that! :) 

Just to confirm: If the user than types something into the field, it turns black, right?

**Comment by zonia3000** [comment]
> Just to confirm: If the user than types something into the field, it turns black, right?

Yes

**Comment by jluethi** [comment]
Great, then let's go with that! :)
