### ISSUE TITLE
Use `FRACTAL_RUNNER_BACKEND=local_experimental` for fractal-server backend in fractal-web CI

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#511]
Note that this backend also has the stop-job endpoint implemented.

**Comment by tcompa** [comment]
Notice that this backend can only run V2 jobs. If the CI needs to run both V1 and V2 jobs, then we should stick with `local`.

**Comment by zonia3000** [comment]
> Notice that this backend can only run V2 jobs. If the CI needs to run both V1 and V2 jobs, then we should stick with `local`.

Currently we are testing also the execution of v1 jobs.

I see 2 alternatives:

1. deleting v1 tests related to jobs execution if we think it is unlikely to break that part;
2. adding a flag to conditionally run only v1 or v2 tests and execute the tests twice in the CI (one for v1 and one for v2).

**Comment by tcompa** [comment]
Unfortunately I think that as long as V1 is maintained we should keep testing it.

If option 2 is not too complex (and if the CI time remains under control), I think I'd go with it. If not, let's just stick with `local` and keep a single CI for both V1 and V2.
