### ISSUE TITLE
Expose dropdown for Python version, in task-collection

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#524]
In the task-collection page, the two tabs "PyPI" and "Local" have a Python-version field. As of fractal-server 2.3.0, the only accepted values are strings "3.9", "3.10", "3.11", "3.12". Let's expose those four values as a dropdown menu, rather than as a free text field.

NOTE: even if those four options are all valid, a given instance may or may not have e.g. "3.12" available. This cannot be known to the web-client, for the moment, and then if the user selects "3.12" the API will respond with a 422 and an error message.

**Comment by zonia3000** [comment]
The new dropdown and the error message:

![image](https://github.com/user-attachments/assets/fdcddec1-ca32-4dfd-8b08-df34ceb20e74)
