### ISSUE TITLE
Expose `/api/settings/` endpoint in the admin pages

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#530]
This will be an endpoint restricted to superusers, which shows the settings of the current instance.

~~No action needed until we actually implement it in fractal-server.~~

Available in fractal-server 2.3.3

**Comment by zonia3000** [comment]
Is displaying the records with `***` meaningful?

![image](https://github.com/user-attachments/assets/9341c2f2-928f-46d3-8c78-60345700fc64)

**Comment by tcompa** [comment]
> Is displaying the records with *** meaningful?

It's useful to know they exist (because it may remind the admin that maybe they got one wrong..), but displaying them in this kind of table creates a lot of unnecessary noise.

I would remove those fields from the table, and maybe add a sentence on top of the table (e.g. "obfuscated settings are not shown"). If we want to go even further, we can have a switch "hide/show obfuscated fields", but only if it takes very little effort.

**Comment by zonia3000** [comment]
I've added a switch

![image](https://github.com/user-attachments/assets/aeae4e2f-a768-493a-91e1-a505a0fdcb74)
