### ISSUE TITLE
Tasks should not loose `input filters` upon updating them

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#536]
Reported by @nrepina :

> I noticed when I update task versions on fractal web, the arguments and metadata update nicely, but the ‘input filters’ are cleared, so I need to re-specify them again for all tasks that are updated (e.g. is_3D=True). It’s a little annoying, so if the default can be to keep the type filters from the previous version, what would be great

That's a bug in task updating we should fix. The user expectation should be that those filters are not affected by the update.

**Comment by tcompa** [comment]
We can reproduce this, while `meta` is preserved during the version update.
