### ISSUE TITLE
New feature: optional banner for external-resource downtime

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#552]
There are cases where we want both fractal-server and fractal-web to remain up and accessible, but we know that some operations will fail (typically because some component of the HPC cluster is down).

The required outcome is that in this situation the webclient has a (configurable) informative banner.

### Automated checks in the backend

For the moment, we'd rather not keep any state about this in the backend, since it would be cumbersome to update automatically (we would need to define a `check_cluster_status` internal task that runs regularly, most likely via https://fastapi-utils.davidmontague.xyz/user-guide/repeated-tasks/, and it would run for all the different gunicorn workers).

### Automated checks in the webclient

It makes no sense to replicate the whole backend logic e.g. for SSH connection into the webclient.

### Manual checks and backend action

* An admin performs some check (e.g. `ssh`-ing into the cluster)
* If appropriate, the admin performs some action (e.g. setting some variable to True, and possibly restarting some fractal-web)
* When appropriate, the admin reverts the action

It doesn't sound right that the action takes place in the backend, since the outcome is specific to the webclient (i.e. showing a banner).

## Suggested option: manual checks and webclient action

* An admin performs some check (e.g. `ssh`-ing into the cluster)
* If appropriate, the admin performs some action (e.g. creating a txt file and adding an env variable to fractal-web, and possibly restarting some fractal-web)
* When appropriate, the admin reverts the action

Note that the action may or may not require a fractal-web restart, depending on whether we want to add some additional state variable to the fractal-web application.

**Comment by zonia3000** [comment]
I propose to keep this quite generic, e.g. using an environment variable named `WARNING_BANNER_PATH`, to indicate that the banner can be used to display any kind of warning message we would temporarily show to the users.

**Comment by zonia3000** [comment]
Warning banner example:

![image](https://github.com/user-attachments/assets/14c71cb4-b848-48ce-b5bb-6857d1b6aa21)

Doc:

> `WARNING_BANNER_PATH`: specifies the path to a text file containing the warning banner message displayed on the site; the banner is used to inform users about important issues, such as external resources downtime or maintenance alerts; if the variable is empty or unset no banner is displayed.

**Comment by jluethi** [comment]
That would be great!
Will this banner be shown on all Fractal web pages or just the landing page? I think it would be good that we can show alerts like this broadly, but open to other opinions here

**Comment by zonia3000** [comment]
> That would be great! Will this banner be shown on all Fractal web pages or just the landing page? I think it would be good that we can show alerts like this broadly, but open to other opinions here

Currently it appears on all the pages

**Comment by tcompa** [comment]
To document how #557 is working:
* If I set `WARNING_BANNER_PATH=banner.txt` but that file doesn't exist, the application starts up correctly but no banner is displayed and the logs include this error message
```
2024-09-16 11:46:45,294 - (page layout) - ERROR - An error happened reading warning banner file banner.txt [Error: ENOENT: no such file or directory, open 'banner.txt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'banner.txt'
}
```
* If I then write something into `banner.txt` and refresh the page in the browser, the warning message is displayed (with no need of restarting the webclient).
* I remove `banner.txt` from disk, I am back to the original situation (webclient works, but no banner is displayed).
