### ISSUE TITLE
Show link to plate viewer on dataset page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#553]
The vizarr viewer links on the dataset page are very useful!

Currently, we only link to the individual images, e.g. the full zarr url. For example: 
https://fractal.mls.uzh.ch/vizarr/?source=https://fractal.mls.uzh.ch/vizarr/data/data/active/jluethi/Fractal/20240723_23well_benchmark/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/0
<img width="1336" alt="Bildschirmfoto 2024-09-13 um 16 28 45" src="https://github.com/user-attachments/assets/0fdeddef-281a-4b85-b032-a8dc66948619">

A thing that is also super useful is linking to the plate view. By going to this url: 
https://fractal.mls.uzh.ch/vizarr/?source=https://fractal.mls.uzh.ch/vizarr/data/data/active/jluethi/Fractal/20240723_23well_benchmark/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr
(just removing the sub path to row, col & image)
We see:
<img width="1336" alt="Bildschirmfoto 2024-09-13 um 16 29 22" src="https://github.com/user-attachments/assets/a24df67f-334d-4cc6-a646-3b074b9d52c6">

We have metadata about whether a dataset has plates and what plates are available in the image list:

<img width="195" alt="Bildschirmfoto 2024-09-13 um 16 29 35" src="https://github.com/user-attachments/assets/80d67878-8324-417f-b24c-1e85b23151f4">

The goal would be that:
If there are plates in the image list
Show selector for which plate to load. And show a button for "view plate" that send the user to the link above.

This should be displayed above the image list for the moment. I may have additional ideas of where we expose this in the future :)

----

How do we get the plate url? I'd say we take the first zarr_url with the plate attribute. Given its zarr_url, we reconstruct the plate url. I see 2 ways:
1. We already extract the base path to avoid displaying it. We can just to base path + plate name
2. We could also look at the full zarr_url, find the plate name in the url & drop everything after that from the url

**Comment by tcompa** [comment]
Example of image list
```
zarr_url, plate
/some/plate1.zarr/B/03/0, "plate1"
/some/plate1.zarr/B/04/0, "plate1"
/some/plate2.zarr/A/03/0, "plate2"
```

1. Check If "plate" is one of the images attributes, otherwise stop.
2. Write component on top of image list, with message "Detected 2 plates, choose one to view it (dropdown showing "plate1" or "plate2")
3. User clicks "plate1"
    * If no image with plate1 is currently available, make an API call filtering for plate=plate1 and asking for page-size =1
    * GIven the zarr_url of one plate1 image, remote the last three levels
    * Create vizarr link, and display a "View" button (next to the dropdown, not in the image list)

**Comment by zonia3000** [comment]
Example of View plate button (notice the URL previewed in the bottom of the screenshot):

![image](https://github.com/user-attachments/assets/8b1cf4ad-9de0-4802-9724-ce9ba28da1a4)

If the zarr URL is not valid (it has less than 3 elements) an error is displayed:

![image](https://github.com/user-attachments/assets/5d0a3f8a-37f7-4db6-a9ca-dad1e641b5df)

**Comment by jluethi** [comment]
This looks like a great start for this feature! 👏🏻

Minor wording suggestion:
"This dataset contains 3 plates. Select which plate you want to view"

**Comment by tcompa** [comment]
I tested #562, and it works as expected.

I imported this dataset
```json
{
  "name": "test-2",
  "zarr_dir": "/tmp/some/path/",
  "images": [
    { "zarr_url": "/tmp/some/path/plate1/we/ll/a", "origin": null, "attributes": { "plate": "plate1" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate1/we/ll/b", "origin": null, "attributes": { "plate": "plate1" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate1/we/ll/c", "origin": null, "attributes": { "plate": "plate1" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate1/we/ll/d", "origin": null, "attributes": { "plate": "plate1" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate1/we/ll/e", "origin": null, "attributes": { "plate": "plate1" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate1/we/ll/f", "origin": null, "attributes": { "plate": "plate1" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate1/we/ll/g", "origin": null, "attributes": { "plate": "plate1" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate1/we/ll/h", "origin": null, "attributes": { "plate": "plate1" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate2/we/ll/a", "origin": null, "attributes": { "plate": "plate2" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate2/we/ll/b", "origin": null, "attributes": { "plate": "plate2" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate2/we/ll/c", "origin": null, "attributes": { "plate": "plate2" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate2/we/ll/d", "origin": null, "attributes": { "plate": "plate2" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate2/we/ll/e", "origin": null, "attributes": { "plate": "plate2" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate2/we/ll/f", "origin": null, "attributes": { "plate": "plate2" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate2/we/ll/g", "origin": null, "attributes": { "plate": "plate2" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate2/we/ll/h", "origin": null, "attributes": { "plate": "plate2" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate3/we/ll/a", "origin": null, "attributes": { "plate": "plate3" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate3/we/ll/b", "origin": null, "attributes": { "plate": "plate3" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate3/we/ll/c", "origin": null, "attributes": { "plate": "plate3" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate3/we/ll/d", "origin": null, "attributes": { "plate": "plate3" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate3/we/ll/e", "origin": null, "attributes": { "plate": "plate3" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate3/we/ll/f", "origin": null, "attributes": { "plate": "plate3" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate3/we/ll/g", "origin": null, "attributes": { "plate": "plate3" }, "types": {} },
    { "zarr_url": "/tmp/some/path/plate3/we/ll/h", "origin": null, "attributes": { "plate": "plate3" }, "types": {} }
  ],
  "filters": {
    "attributes": {},
    "types": {}
  }
}
```
and got this page
![image](https://github.com/user-attachments/assets/ff4adb18-002f-4b2d-beb7-7e33199a25bf)

----

The "View" button of the first image points to http://localhost:3000/?source=http://localhost:3000/data/tmp/some/path/plate1/we/ll/a.

---

I selected "plate2", and got
![image](https://github.com/user-attachments/assets/cb421ace-89ae-49e8-97ab-e08806d1e6ed)
where the "View" button points to http://localhost:3000/?source=http://localhost:3000/data/tmp/some/path/plate2
