### ISSUE TITLE
Display additional user information about oauth accounts

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#555]
Starting from fractal-server `2.5.0a1` (upcoming), user-related endpoints will also returns some information about their associated OAuth accounts (if any). This includes a new property `oauth_accounts`, where each element includes properties: `id`, `account_email` and `oauth_name` (e.g. `github` or whatever we used in the fractal-server OAuth configuration).
If there is no oauth account linked to a given user, then `oauth_accounts=[]`.

We should include this information in the user profile and in the user information in the admin-area page.

**Comment by tcompa** [comment]
`2.5.0a1` now released

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/9ca159e1-8a77-414a-b8f3-ff47efd4e1de)
