### ISSUE TITLE
Support `FRACTAL_API_V1_MODE="include_read_only"`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#556]
Starting from v2.3.8, `fractal-server` supports three values for the `FRACTAL_API_V1_MODE` configuration variable:
* "include" -> full support of V1 API
* "include_read_only" -> V1 API is still in place, but non-GET endpoints in `/api/v1` always respond with a 422 and an error message
* "exclude" -> V1 API endpoints are not in place

We already support include and exclude in fractal-web. We should probably also support `include_read_only` in some way. To minimize the required effort, I think it'd be enough to show a "Warning: legacy API is in read-only mode" banner on all v1 pages, rather than modifying all pages to disable the actions that would lead to some POST/PATCH/DELETE API call.

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/8a5d1bb2-80f6-46af-892e-b56f788417d6)

**Comment by tcompa** [comment]
Great, thanks.

For the record, this is the error that one would still get when trying to write something:
![image](https://github.com/user-attachments/assets/2865e0d6-8131-440c-ab06-d86b7df49fd0)
