### ISSUE TITLE
"owner" dropdown list has duplicated entries

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#559]
Observation: In the `v2/admin/tasks` page, the dropdown menu listing all possible "owner" values has repeated entries.

Expected behavior: the list only has unique entries.

(I haven't checked yet whether this list is prepared in the backend or created in the webclient)

**Comment by zonia3000** [comment]
This happened when two users had the same `slurm_user` value. Fixed in #562.
