### ISSUE TITLE
Allow sending `cache_dir=null` in PATCH request-body

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#568]
In user's settings, we should also enable the possibility of setting `cache_dir=null`. Right now, if I try to set it to an empty string then the webclient sets `cache_dir=""` in the request body, which is then rejected from the backend.

![image](https://github.com/user-attachments/assets/be80d4e1-92b0-4b97-a24d-e2a0b1cdc8d8)
![image](https://github.com/user-attachments/assets/2c9bf519-a707-4423-921d-c811fa9ca15d)

---

This is a specific case, but it most likely applies to several other forms. Let's find a solution which would also work for all of them.

**Comment by zonia3000** [comment]
We already have a function `nullifyEmptyStrings` that we use in similar cases. In most of the cases we are using `stripNullAndEmptyObjectsAndArrays`, so the empty string are removed from the payload.

However, in this particular case if I send null to the endpoint I receive another validation error:

![image](https://github.com/user-attachments/assets/7006c9cc-3a17-435f-bcdd-49d16728a324)

```json
{"detail":[{"loc":["body","cache_dir"],"msg":"command=None is not a string.","type":"value_error"}]}
```

Is this expected?

**Comment by tcompa** [comment]
> However, in this particular case if I send null to the endpoint I receive another validation error:
> ...
> {"detail":[{"loc":["body","cache_dir"],"msg":"command=None is not a string.","type":"value_error"}]}
> Is this expected?

No, it's not expected - and it's to be fixed on the backend side. Thanks!
