### ISSUE TITLE
Expose new UserGroup attribute in admin-area POST/PATCH/GET endpoints

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#569]
Requires:
* https://github.com/fractal-analytics-platform/fractal-server/issues/1809

The fractal-server changes are
* The UserGroup model and schemas will have a new `viewer_paths` string-array non-nullable attribute.
* This new attribute can be optionally included in `POST /auth/groups/` request body
* This new attribute can be optionally included in `PATCH /auth/groups/{group_id}/` request body
* This new attribute will always be part of response bodies for `GET /auth/groups/`, `GET /auth/groups/{group_id}/`, `PATCH /auth/group/{user_id}/`

The necessary fractal-web changes reflect the ones above:
* Display the number of `viewer_paths` for each group in the all-groups page (`.../v2/admin/groups`)
* Display this new attribute in the single-group page (`.../v2/admin/groups/{group_id}`)
* Include this new attribute in the edit-page (`.../v2/admin/groups/{group_id}/edit`)

**Comment by tcompa** [comment]
Available as of fractal-server 2.6.3.

We also included an endpoint for a standard users to learn about their `viewer_paths` (`GET /auth/current-user/viewer-paths/`, returning a list of paths), and this information could be perhaps be displayed somewhere in the current-user's pages

I'd start simple, by just listing the relevant user pages:

1. profile (always)
2. settings (if `FRACTAL_RUNNER_BACKEND` is `slurm` or `slurm_ssh`)
3. viewer paths (if `PUBLIC_FRACTAL_VIZARR_VIEWER_URL` is set)

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/e11a8f64-36d4-4624-95da-d26ba2f54c46)

![image](https://github.com/user-attachments/assets/7c01df3a-2988-43ca-884e-7231e81f2105)

![image](https://github.com/user-attachments/assets/6d905e4a-0b3d-48b5-8135-a9936a0ed0d7)

![image](https://github.com/user-attachments/assets/b8cb1128-d1b9-4564-b91d-16177bb713ed)
