### ISSUE TITLE
Update POST for tasks

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#576]

**Comment by tcompa** [comment]
All endpoints that create tasks also expose "ownership" information, and we should adapt the forms.
POST single task
POST task collection / local wheel file
POST task collection / pypi package
POST task collection custom

Context:
* Every TaskGroupV2 is always associated to a single user who create it (FK `user_id`) - this user has full read/write/delete access
* **Optionally**, a TaskGroupV2 may be associated to a single user group (FK `user_group_id`) - users of this group have "read&use" access

All four endpoints will have two new query parameters:
* `user_group_id=123` -> to use a specific user group
* `private: bool = False`  -> to not user any specific user group (set it to null)

Options:
1. No query parameter -> group "All" by default
2. Both user_group_id=something and private=True -> 422
3. private=True -> set user_group_id=null
4. user_group_id=123 (possibly also with private=False) -> this is used 


---

UI
* Radio button to separate "Private task" from "Shared task" (default -> shared)
* Within "private", no additional info is needed
* Within "shared", dropdown with user groups - with "All" preselected
* A single group can be selected, not more
* Order of user groups is the same as coming from the backend

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/a46f243c-c117-4234-8b54-82fbfa126d69)

![image](https://github.com/user-attachments/assets/afffc600-fb50-43b3-ad51-67367bcdc506)
