### ISSUE TITLE
Update GET for tasks (for task insertion in workflow)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#577]

**Comment by tcompa** [comment]
First option (we can improve later..)

Start with data from `GET /api/v2/task-group/`
Build map of all `task_list`s into a single array, after enriching each `task_list` item with new `pkg_name` and `version` attributes.
Proceed as in the current version

Let's start with sorting the list by `pkg_name` (as we are doing now).

---

Note that this does not include further filtering, based e.g. on `category`, `modality`, `authors`, `tags`. This will be addressed elsewhere.

**Comment by zonia3000** [comment]
First version of the new workflow task modal:

![image](https://github.com/user-attachments/assets/e853eb5e-404d-4c8a-8f78-136b3615720b)

**Comment by jluethi** [comment]
Can we as a second iteration just include a column that lists all the content of the following metadata: category, modality, authors, tags? We can later iterate towards versions like these with filters & adjustable ordering:
![Screenshot 2024-10-09 at 15 24 49](https://github.com/user-attachments/assets/f6221cc2-ae6a-4ccc-9372-cfa4bc6a0429)

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/3e024590-370c-4490-8d7e-384bf076d1ae)
