### ISSUE TITLE
Display warnings in workflow page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#578]
As of fractal-server 2.7.0, the response of `GET /api/v2/project/{id}/workflow/{id}/` includes additional information.

Now each item in `response.task_list` has an optional string property `warning`, which is pre-populated server-side and typically may be one of these:
* "Task is not active."
* "Current user has no access to this task."

When this `warning` property is set, we should display it in the task list in the workflow page.
Note that these warnings are blocking: if we try to submit a job which include one these tasks, submission will fail with a 422. If we display the information in advance, it will be more clear for the user.

**Comment by zonia3000** [comment]
I noticed that the endpoint `PATCH /api/v2/project/{id}/workflow/{id}/` doesn't return the warning property. Is this expected? Could it be possible to add this property also on that endpoint?

Currently, when the PATCH is called to change the tasks order, the code replaces the displayed tasks list with the patched one and the warning would disappear.

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/41a733f6-2d58-4396-9b11-8f58c40fef45)

**Comment by jluethi** [comment]
+1 on using such warnings. Let's make sure we have the "this task has an update" logic be different. I think the yellow exclamation mark fits well for these warnings. Updates can be e.g. an up-arrow in grey or something else that looks less like the warning

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/8316f53a-26dd-455d-bff6-e3f1a8e07fdb)

**Comment by jluethi** [comment]
Looks great, thanks!
