### ISSUE TITLE
Disambiguate identical task groups

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#582]

**Comment by tcompa** [comment]
This is a preliminary filter to be applied to the task-group list obtained from `GET /api/v2/task-group/`, _before_ using it in the http://localhost:5173/v2/tasks page or in the modal for adding a task into a workflow. 

The basic logic is described in https://github.com/fractal-analytics-platform/fractal-server/issues/1831#issuecomment-2390766546.

The high-level goal is that after the filtering operation we have a list where there cannot be any two items with the same `pkg_name` and `version`.

Given N task groups with the same `pkg_name` and `version`, we should select a single one based on the following logic:
1. If there is a task group such that `task_group.user_id` matches with the current-user ID, this is the one to be included and the others should be discarded.
2. If not, we sort the remaining task group based on their `user_group_id`, and as a sorting rule we use the order of group names as obtained in https://github.com/fractal-analytics-platform/fractal-web/issues/575 (that is, "All" group first and other groups next based on their "age").

**Comment by tcompa** [comment]
Additional note: `version=null` should be treated as a distinct value, the same as if it were `version="null"`

**Comment by tcompa** [comment]
Here is a concrete example


* I am user with `id=1`.

* The response from `GET /auth/current-user/?group_names_ids=true` includes these `group_names_ids`:
```json
[
  ["All", 11],
  ["older team", 22],
  ["recent team", 33]
]
```


The response from `GET /api/v2/task-group/` reads something like

```json
[
 {"pkg_name": "mypkg", "version": "1.1.1", "user_id": 1, "user_group_id": null, task_list=[]},
 {"pkg_name": "mypkg", "version": "1.1.1", "user_id": 2, "user_group_id": 11, task_list=[]},
 {"pkg_name": "mypkg", "version": "1.1.1", "user_id": 2, "user_group_id": 22, task_list=[]},
 {"pkg_name": "mypkg", "version": "1.1.1", "user_id": 2, "user_group_id": 33, task_list=[]},
 {"pkg_name": "mypkg", "version": "2.2.2", "user_id": 2, "user_group_id": 11, task_list=[]},
 {"pkg_name": "mypkg", "version": "2.2.2", "user_id": 2, "user_group_id": 22, task_list=[]},
 {"pkg_name": "mypkg", "version": "2.2.2", "user_id": 2, "user_group_id": 33, task_list=[]},
 {"pkg_name": "mypkg", "version": "3.3.3", "user_id": 2, "user_group_id": 33, task_list=[]},
 {"pkg_name": "mypkg", "version": "3.3.3", "user_id": 2, "user_group_id": 22, task_list=[]},
 {"pkg_name": "mypkg", "version": null, "user_id": 1, "user_group_id": 11, task_list=[]},
 {"pkg_name": "mypkg", "version": null, "user_id": 2, "user_group_id": 11, task_list=[]}
]
```
the filtered list should look like
```json
[
 {"pkg_name": "mypkg", "version": "1.1.1", "user_id": 1, "user_group_id": null, task_list=[]},
 {"pkg_name": "mypkg", "version": "2.2.2", "user_id": 2, "user_group_id": 11, task_list=[]},
 {"pkg_name": "mypkg", "version": "3.3.3", "user_id": 2, "user_group_id": 22, task_list=[]},
 {"pkg_name": "mypkg", "version": null, "user_id": 1, "user_group_id": null, task_list=[]}

]
```

**Comment by tcompa** [comment]
Here is a first test.

I have three users (please ignore the fourth):
![image](https://github.com/user-attachments/assets/7eda4aef-7763-4221-85ff-22473e4fc192)
and they all belong to three groups ("All", "Old Group" and "New Group").

For each user, I create a task and task-group named `a` and with `version=null`
![image](https://github.com/user-attachments/assets/af1b7f57-3474-4354-a528-1f0dfa4332ee)

If I log in as any of the three users, I only see one task group (the one owned by me). This is visible in these three screenshots, where each view points to a different user group 
![image](https://github.com/user-attachments/assets/c467f655-88aa-4868-b842-79924dbcbab1)
![image](https://github.com/user-attachments/assets/57238a83-4e64-4fcf-852e-f55b994e2832)
![image](https://github.com/user-attachments/assets/d7dd0648-9e6f-4dbc-9d0a-29f646108c08)


Now, as user admin@fractal.xy, I remove the task group I created. Therefore I see one of the other users' ones, and precisely the one of the `Old Group` usergroup (to which I was associated first):
![image](https://github.com/user-attachments/assets/809dbab9-8f97-4c99-9c78-ce91649b1311)

**Comment by tcompa** [comment]
Current discussion with @zonia3000:
* For the moment we are _not_ adding an option to disable the disambiguation for standard users.
* We will improve the admin pages (notably http://localhost:5173/v2/admin/tasks, and maybe another one for task-groups) - which would be very useful for debugging cases like "I don't know any more which task I am using".

**Comment by jluethi** [comment]
> - For the moment we are not adding an option to disable the disambiguation for standard users.
> - We will improve the admin pages (notably http://localhost:5173/v2/admin/tasks, and maybe another one for task-groups) - which would be very useful for debugging cases like "I don't know any more which task I am using".
> - We may enable a "show all copies of tasks" feature for standard users as well, if we find out that it could be useful (e.g. to override the priority heuristics and select a specific task). TBD

Sounds like a good plan. I don't expect many users to even hit this disambiguation scenario, but good to know what our next steps can be here :)
