### ISSUE TITLE
Review updates to task-version-update feature

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#584]

**Comment by tcompa** [comment]
I create a task with an old version, and fill its properties
![image](https://github.com/user-attachments/assets/804b2191-9adc-42a1-ad10-8fd72dc1eb2b)
![image](https://github.com/user-attachments/assets/dbd78ecf-b781-4f85-a41f-f0ca68fbce77)
![image](https://github.com/user-attachments/assets/bf48bf1d-d7ab-4659-993e-bf9aa8a81c9c)

Then I update it
![image](https://github.com/user-attachments/assets/050ed053-db40-4e1f-acde-cd70e0e0c6db)

And properties are still there
![image](https://github.com/user-attachments/assets/b580baae-8472-4564-a5f8-612a1acea3ca)
![image](https://github.com/user-attachments/assets/e72bc0fd-f968-40b6-9e34-77db69a36fef)
![image](https://github.com/user-attachments/assets/5c7d5602-46a3-43a5-a9ae-8ad2913ab49d)


---

All as expected.

**Comment by tcompa** [comment]
Quick check: @zonia3000, could you please remind me how/where we define the logic for matching an "old" tasks to a set of "new" ones? We should review whether this changes with fractal-server v2.7.0

**Comment by zonia3000** [comment]
For each task having a schema and a version we build the list of its update candidates looking for tasks having:

* a defined schema and version
* the same name and type of the target task
* a version greater than the one of the target task

Logic is here: https://github.com/fractal-analytics-platform/fractal-web/blob/3d39133b7a1b3a6fec53a248b854f5d110374935/src/lib/components/v2/workflow/version-checker.js#L31

**Comment by tcompa** [comment]
Thanks!
I think the current logic works most of the time, but we could tighten it a bit.

The high-level goal would be to also require that the task-group `pkg_name`s match.

Here is one possible way of making it work

Instead of fetching `/api/v2/task` we fetch `/api/v2/task-group`, and on top of that we also fetch the specific task group of the current task.
Now we can filter task groups first, similar to
```
(
	task_group.version !== null &&
	task_group.pkg_name === current_task_pkg_name &&
       ...
)
```
where `...` include some indirect checks, namely that the `task_group.task_list` includes one task such that
*  `name` is the given one
* `type` is the given one
* current checks about args_schema are valid

In this way, if two different task groups (`pkgA` version `1.2.3` and `pkgB` version `2.3.4`) both include a task named `test`, we won't expose this is a valid version update.

---

Side remark: it's true that the filtering becomes quite more complex, but in principle the check on `pkg_name` matching should reduce the number of actual checks to a handful.

Also: when fetching `/api/v2/task-group`, I would also include `only_active=True` (which possibly makes the list even shorter).

**Comment by zonia3000** [comment]
I've added this check in PR #616
