### ISSUE TITLE
Workflow page

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#59]
PATH `/project/<project_id>/workflow/<workflow_id>`

Relevant workflow properties: `id`; `name`; `projectId`;

Format the page heading as follows: #60

- [x] #62
- [x] #61
- [x] #63
- [x] #64
- [x] #65
- [x] #66

**Comment by tcompa** [comment]
- On the "left" of the page we show the current list of WorkflowTasks.
- The user can select (via a click?) a certain WorkflowTask that is "active"; a context variable then encodes the task to show/modify on the "right"
- After selecting a task, I can also delete it (or this could be an option from the table)
- For the creation of task, let's make sure that "order" is exposed

**Comment by tcompa** [comment]
More details on the typical user flow:

I create a new workflow
I enter the wf page
I click "Insert new WorkflowTask"; I choose one out of the list, and I set "order".
The task is added to the workflow task list.
From the main workflow page, I can edit that task (include new arguments, specify values of some arguments, ... and eventually "save") from a panel in the same page.

If I need to add four tasks, I will do so one by one.
