### ISSUE TITLE
Review reordering of tasks in workflow

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#591]
I'd say we can drop the second option of inserting at an integer-specified order position. Instead, I'd say we can improve the reordering front-end side (e.g. by offering a drag & drop reorder version instead of the current arrow-based approach once the reorder menu is started).

_Originally posted by @jluethi in https://github.com/fractal-analytics-platform/fractal-server/issues/1901#issuecomment-2407279830_

**Comment by zonia3000** [comment]
This is the new modal where the tasks can be dragged:

![image](https://github.com/user-attachments/assets/47c3755c-25e6-4d1f-b41a-561804ba2cd7)

**Comment by jluethi** [comment]
Oh, that's awesome!

@zonia3000 a very minor feature wish (only reopening so it doesn't get lost, you did fix the core part already of course): Let's remove the task ID after the task name (e.g. `#31` in the screenshot above).

**Comment by zonia3000** [comment]
@jluethi Done in #620

Notice however that in this way, if the user selects the same task twice, it is not possible to understand which one they are reordering.

**Comment by jluethi** [comment]
Thanks!
That's a fair concern. I don't think the ID helps much, as we don't show it in the regular workflow list. But it's a design limitation we may want to address in the future.
