### ISSUE TITLE
Improve oauth login wording & login page layout

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#603]
With the broader adoption of oauth logins across our deployments, we should polish how the oauth login appears to users.

It currently looks like this:

<img width="1412" alt="Screenshot 2024-10-17 at 09 05 51" src="https://github.com/user-attachments/assets/2f2ba1c6-02bb-4c67-a44d-4fcb9819a8b8">

Let's make the following changes:
### Oauth
1. Show oauth login first
2. Let's change the title to: `Institutional login`
3. Let's change the button description: "Log in with institutional account" (with log in with space)

### Local account
4. Let's rename the local version to: "Log in with username & password" (with log in with space)
5. Let's remove the "The email you provided to the IT manager" text. Instead, let's add a text field above the email field saying: "Log in with Fractal specific email & password provided to you by the Fractal admin"
6. Can we change the button text from Submit to Login?

### Page layout
7. I think we want to encourage people to use that login whenever it's available. Can we make the "Log in with username & password" something that needs to be expanded, e.g. the user needs to click on it to show the entry fields & login button? That may help steering people to use the oauth login.

**Comment by zonia3000** [comment]
The page when `PUBLIC_OAUTH_CLIENT_NAME` is set:

![image](https://github.com/user-attachments/assets/dc7e3d58-d3b5-4146-bbcb-5682d55c8a43)

Local login panel expanded:

![image](https://github.com/user-attachments/assets/05848d4e-11e1-4691-a71b-a99124cb1392)

---

The page when `PUBLIC_OAUTH_CLIENT_NAME` is not set:

![image](https://github.com/user-attachments/assets/f1b247ac-4a23-4d10-b5cb-ed5e99feb29d)

**Comment by jluethi** [comment]
This looks great! Very minor nitpick @zonia3000 : Can we change the button label on the username & password (in both settings) to "Log in" instead of "Login"? Just for consistency :)
