### ISSUE TITLE
Non-clickable dropdown-menu items

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#609]
When I open this page
![image](https://github.com/user-attachments/assets/f925f17e-95ec-4c15-a720-033f13130b7d)
I can click on the dropdown menu, see two different versions, and select any of the two. This was done on firefox.

@jluethi is able to open the dropdown menu, but it seems that he cannot click on the non-selected option.
Joel, could you add any relevant detail? E.g.

- What browser are you using?
- Do browser developer tools show anything special?
- Can you reproduce on a different browser?

**Comment by jluethi** [comment]
I'm using Chrome Version 129.0.6668.101 (Official Build) (arm64)

The issue remains: I can open the dropdown, but when selecting another entry, the selection isn't applied (interface doesn't update and infos till shows newer version, not older version).

I also tried with safari (Version 17.6 (19618.3.11.11.5)) and hit the same issue there.

**Comment by jluethi** [comment]
Nothing is shown in the console, but I didn't check logs on the backend

**Comment by jluethi** [comment]
Also, the same modal works for me in the "add a workflow task" dialogue box. Just not on the tasks page

<img width="1438" alt="Screenshot 2024-10-21 at 14 16 03" src="https://github.com/user-attachments/assets/7511fa71-5656-4eec-84b9-882b1d3a19a1">
