### ISSUE TITLE
Improve duplicate save button in user-edit page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#614]
In the edit-user page, the two "Save" button are sometimes confusing (I edit a field in the "settings" and click the wrong "save" button, but I don't get any feedback about that):

![image](https://github.com/user-attachments/assets/fbb45aad-1d92-4f75-8b9e-fed0a2e3aa90)

Some ideas of how to improve this:
1. Rather than "Settings successfully updated", we print "Warning: there was no change to save".
2. We check unsaved edits, as in
![image](https://github.com/user-attachments/assets/8515695f-5b3c-4419-8f97-4288ff95ba82)

Thanks @apasto!

**Comment by zonia3000** [comment]
Another possibility is to have only one Save button that saves one or both the sections as needed.

**Comment by tcompa** [comment]
> Another possibility is to have only one Save button that saves one or both the sections as needed.

Agreed, that's also perfectly valid.
