### ISSUE TITLE
Admin page for task groups

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#619]
In the admin area, I propose that we build a new task-groups page rather than just updating the tasks one. We can later decide whether it's worth merging them together or keeping them separate.

The new page would have a structure similar to the current standard-user task list (in `v2/tasks`), with a few differences:

1. The relevant endpoint would be `GET /admin/v2/task-group/`
2. We should have additional UI for optionally adding query parameters to this API call: 
    * `user_id`
    * `user_group_id`
    * `private`
    * `active`
    * `origin` (one of "pypi", "wheel-file" or "other" - but this first requires https://github.com/fractal-analytics-platform/fractal-server/issues/1973).
    * `pkg_name` - requires https://github.com/fractal-analytics-platform/fractal-server/issues/1973
3. We should not apply disambiguation to the response data.
4. The previous point means that we'll need a different aggregation logic, because there _will_ be multiple copies of the same task group. We can start with "no aggregation at all" (that is, one item per task group), and then iterate on this.
5. We should display additional ownership information, namely which user owns the task-group (as defined in the `user_id` foreign-key).
6. We should display the same action buttons as in the standard user page (info/edit/delete), but in order to actually use the edit/delete we first need https://github.com/fractal-analytics-platform/fractal-server/issues/1974.

I would start with this skeleton, and then we can decide whether we want to add pagination or fancier aggregation or other improvements - if needed.

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/abf753a8-a068-40c1-998c-a09a6de633f7)
