### ISSUE TITLE
Make zarr_dir optional when creating dataset

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#630]
* Starting from fractal-server 2.8.0, `zarr_dir` becomes optional in the dataset POST.
* If user has no project_dir in their settings, zarr_dir becomes required (backend-side).
* In the dataset-creation modal, let's add a description like "The main folder for OME-Zarrs of this dataset. If not set, a default subfolder of `{user_settings.project_dir}` will be used."
* Upon successful dataset creation, display a temporary message showing the value of `response.zarr_dir`.

**Comment by jluethi** [comment]
This sounds great.

Once we validate that those defaults are working well in practice, I'd like to make it a stronger default for the regular user flow: e.g. a user that has `{user_settings.project_dir}` set sees `Dataset name` & `Advanced options`. They'd have to expand `Advanced options` to set the optional zarr_dir to something else.
