### ISSUE TITLE
Also include `project_dir` in the `viewer_path` page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#635]
TBD

**Comment by jluethi** [comment]
I'd keep it in settings (we use it as a setting in multiple places). We can eventually also just show this variable in viewer_path page

**Comment by zonia3000** [comment]
Is this ok?

![image](https://github.com/user-attachments/assets/9d683965-ba63-48a5-9209-4c7aaf2c246f)

When `project_dir` is not set and viewer paths list is empty I would display a different message:

![image](https://github.com/user-attachments/assets/0da57ded-a81f-445d-a814-27835534f327)
