### ISSUE TITLE
Update dataset-creation modal

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#639]
1. If the user has a `project_dir` in their settings -> `zarr_dir` is optional, and the corresponding text field is not visible by default (e.g. it's hidden in an "Advanced options" block)
2. If the user has no `project_dir` in their settings -> `zarr_dir` is required and the corresponding text field is visible

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/f60fcf1b-a071-49e9-a9cd-b2b8fd2e8ac6)

![image](https://github.com/user-attachments/assets/20834bdd-4469-4cdf-931b-e1aac43e32ec)

![image](https://github.com/user-attachments/assets/7619f44f-9e02-4985-a925-c85a57aaceed)

**Comment by jluethi** [comment]
That's great! 🎉
