### ISSUE TITLE
Add query parameters to `GET /admin/v2/task-group/`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#646]
In `GET /admin/v2/task-group/`, we are adding two query parameters `timestamp_last_used_min` and `timestamp_last_used_max` (both are optional, and both are timezone-aware timestamps).

This will be available as of
* https://github.com/fractal-analytics-platform/fractal-server/pull/2061

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/e57cd38d-014e-44f2-899e-6b7d52284c6e)
