### ISSUE TITLE
[placeholder] Export a token or a cookie

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#647]
High-level: sooner or later, we may want to access data served through `fractal-vizarr-viewer` from a command-line application.
Fractal-web would be the right place to export the required piece of information required for authentication.

This is related to:
* https://github.com/fractal-analytics-platform/fractal-vizarr-viewer/issues/18
* https://github.com/fractal-analytics-platform/ngio/issues/9

---

We should review what's the best approach among:
1. Expose a simple way to download the key/value pair of the `fastapiusersauth` cookie, from an authenticated fractal-web session. The current way is to open the browser developer tools and copy the cookie string, but we may want to simply expose it in the top-right user options.
2. Switch from cookie to tokens? Does it make sense? We would need to support them in fractal-vizarr-viewer. I've not thought carefully about this yet - TBD

**Comment by zonia3000** [comment]
After discussion with @tcompa: in fractal-vizarr-viewer backend we can support both the token and the cookie, so that vizarr can work with the cookies handled automatically by the browser and fractal-web can expose a "download token" button, which provides a token file that can be used from command line.

**Comment by zonia3000** [comment]
Where should we put this? On the user menu on the right?

![image](https://github.com/user-attachments/assets/10ca731c-8da0-41d4-9a69-dafff97b0cf5)

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/fe5606b6-c1b1-43bb-8d72-a06d4d6446f7)

**Comment by jluethi** [comment]
Coming to this delayed. Great that the token part is working out. We can have it on the "My profile" page for now. If we start to use it more regularly, I did like @zonia3000 initial suggestion of putting it into the user menu directly. But let's first see where this gets used :)
