### ISSUE TITLE
Simplify settings setup for new users

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#648]
E.g.

> It would be great to be able to say: Use the same user settings as User X

or something similar. This could be done e.g. with fractal-web calling two endpoints one after the other: the standard POST, and a new copy-settings-from-another-user PATCH endpoint.

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/c2c598a8-c9c9-4e9d-bbff-338854328de1)

![image](https://github.com/user-attachments/assets/514e53b4-187b-456d-ad9f-00ddc25e0445)

![image](https://github.com/user-attachments/assets/7db83f88-a4ef-43ff-a9aa-7088e88e27cc)

**Comment by jluethi** [comment]
The interface to this looks great!

One question: Will this also include copying over `SSH host`, `SSH username`, `SSH Private Key Path`, `SSH Tasks Dir` & `SSH Jobs Dir` in an SSH deployment? Those are the ones where this feature will be most useful for :)

**Comment by zonia3000** [comment]
> One question: Will this also include copying over `SSH host`, `SSH username`, `SSH Private Key Path`, `SSH Tasks Dir` & `SSH Jobs Dir` in an SSH deployment? Those are the ones where this feature will be most useful for :)

Yes!
