### ISSUE TITLE
The user shall be able to edit a WorkflowTask

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#65]

**Comment by tcompa** [comment]
The logic will be as in https://github.com/fractal-analytics-platform/fractal-web/issues/63

**Comment by jluethi** [comment]
Cool first version! :) 

Has there been a decision against a 2-column approach with tasks names to the left and their detail page to the right (similar to the layout of the dataset page)? Or is this just the first implementation of adding tasks?

We can of course have layout discussions & optimizations later. Very nice to see that the functionality is coming together.

**Comment by rkpasia** [comment]
[Video reference of updating process](https://www.loom.com/share/2405abba514e444083f945fd6c93ac85)

**Comment by tcompa** [comment]
Suggestion by @gusqgm:
For "object" arguments of a WorkflowTask, let's also make that list collapsable (accordion-like).

**Comment by rkpasia** [comment]
Currently, in #74 this issue has been taken care of, partly.

The status we reached is the following:

- A user can add an argument to a workflow task.
- The argument can be specified as a `string` / `number` / `boolean` / `object`.
- All three kinds of arguments currently supported can be managed by the user.
- An argument **can not** be deleted.
- An user can delete an object argument sub-properties.
- The object argument is displayed as a collapsable element to prevent cluttering of UI.

The road ahead requires to introduce the support for another kind of argument, which is `list`.
It should be established if the kind of elements within the list will always be objects or if the client could expect to find either `string`/`number`/`boolean` as list elements.

At the moment this will be closed, new issues will originate from this to track further work.

**Comment by jluethi** [comment]
Ok, `object` > `object` nesting will be required. Let's open a new issue for object > object and the list nesting. 

I opened it here: https://github.com/fractal-analytics-platform/fractal-web/issues/78
