### ISSUE TITLE
Split standard-user tasks page into "tasks page" vs "tasks management page"

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#657]
The management page would look like the current one.

The tasks page would look very much like the discussion in https://github.com/fractal-analytics-platform/fractal-web/issues/654.

**Comment by jluethi** [comment]
> At some point in the future we may want to review this, and move the "Edit single task" button to the tasks list page. But I don't have a strong opinion here, and I would wait for some additional feedback (even after the merge&release).

I think it's well placed where it is. Editing tasks would be a task management operation. And it's good if the task management page has a simple overview of the task packages, while the main task page has our new fancy view on it :)
