### ISSUE TITLE
Include user-email in `v2/admin/task-groups/activities`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#659]
Right now this column is not there:

![image](https://github.com/user-attachments/assets/40374bc7-4f55-494f-9a71-b2ac5da0e49c)

If it's possible with the current API-provided information, we should add a "User" column the same way as in `v2/admin/task-groups`.

**Comment by zonia3000** [comment]
![image](https://github.com/user-attachments/assets/3c8a41c4-bddc-4f4c-a55a-49ef1d0b10c2)
