### ISSUE TITLE
[placeholder] Review what goes in "tasks" vs "manage tasks" pages

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#664]
We should review what we currently have in each one of the two task lists, and decide which parts are duplicated and which parts are defined only in one of the two pages (and which one).

---

Based e.g. on https://github.com/fractal-analytics-platform/fractal-web/issues/657#issuecomment-2514215837:

Side comment (no action needed): where should the following feature live?

![image](https://github.com/user-attachments/assets/6883f659-ddbe-4a6e-a9ac-06c188fd5b0f)

As part of #658, this is within the tasks-management page, which makes sense because that's the kind of separation we introduced (a read-only page that shows all available tasks, and one for the actual operations).

At some point in the future we may want to review this, and move the "Edit single task" button to the tasks list page. But I don't have a strong opinion here, and I would wait for some additional feedback (even after the merge&release).

In general I think that editing tasks should be quite rare, for the use flows that we typically have in mind.

**Comment by jluethi** [comment]
> At some point in the future we may want to review this, and move the "Edit single task" button to the tasks list page. But I don't have a strong opinion here, and I would wait for some additional feedback (even after the merge&release).

I think it's well placed where it is. Editing tasks would be a task management operation. And it's good if the task management page has a simple overview of the task packages, while the main task page has our new fancy view on it :)

**Comment by jluethi** [comment]
> Is it OK this way, or should we add some more info into the modal of the new tasks page?

That's a good question. For the moment, the separation works well for me. The core thing users care about is the task description. If we had more relevant `Docs Link`, they may also care about them. And some potential future content like longer description or images.

But all the other content like command, args schema version, meta, arg schemas etc. are correctly placed on the task management page, as they shouldn't be user-relevant
