### ISSUE TITLE
Improve horizontal alignment of tasks with different versions

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#665]
The current task-list table layout is suboptimal when we have tasks with
* N>1 versions
* 1 version
* no version

I guess we should force an alignment scheme that covers all three cases (naive idea: we always display the box around the version, independently on whether there are 0, 1, or N versions).

![image](https://github.com/user-attachments/assets/bb28d857-df7e-4f20-af6b-56229e1f5c58)

**Comment by zonia3000** [comment]
I put the info buttons in a separated column:

![image](https://github.com/user-attachments/assets/f551f443-51a5-4f02-9d0d-b4c7b8ed0548)

![image](https://github.com/user-attachments/assets/9ff5e0fd-e73f-4b87-bb26-b20e96e967cd)

**Comment by jluethi** [comment]
That looks like a good solution to me
