### ISSUE TITLE
When task collection fails, show the appropriate log

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#67]
If task collection fail, then the response of a GET call to the check-collection endpoint looks like:
```JSON
{
    "data": {
        "status": "fail",
        "info": "this is the log of what went wrong: asdasdada",
    }
}
```
The relevant field that should be shown when we click on the "info" button is indeed the `response["data"]["info"]` attribute, but I think that at the moment we are displaying something else (I may be wrong).

**Comment by rkpasia** [comment]
Currently the client displays the `log` property of the server response. 

https://github.com/fractal-analytics-platform/fractal-web/blob/b4974439d0020999f3f7460d17b370ad37b13d4f/src/lib/components/tasks/TaskCollectionLogsModal.svelte#L8-L18

Should we display `info` instead then?

**Comment by tcompa** [comment]
You're right, there is a bit of confusion here (coming from our side), because task collection can fail in different ways and the relevant information is sometimes in `info` and sometimes in `log`.

I'll open an issue upstream to make sure we have this under control in fractal-server.

**Comment by tcompa** [comment]
We are fixing this in fractal-server (ref https://github.com/fractal-analytics-platform/fractal-server/pull/559), and the `log` field should be the one where all relevant information are. This means that the current handling of this information in fractal-web is correct.
