### ISSUE TITLE
Change wording of help message

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#672]
In the `v2/admin/users/{id}/edit` page, username description should read only "Optional property" instead of the following

![image](https://github.com/user-attachments/assets/1369e698-501b-400c-88cd-34bd5a8519a4)

**Comment by jluethi** [comment]
What are we using username for nowadays? Can we list that there instead?

**Comment by jluethi** [comment]
Will also be relevant for project sharing. A display name would be useful, but uniqueness gets tricky

**Comment by jluethi** [comment]
Conclusion: Let's not remove it for now, but also not do anything more until we know the longer-term scope
