### ISSUE TITLE
Display "how to install" button on tasks table

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#674]
Ref
* https://github.com/fractal-analytics-platform/fractal-analytics-platform.github.io/issues/9

The task objects may include an additional (optional) property called `install_instructions`, with a value which is a markdown-formatted block of text.

If the `install_instructions` field is present, we should display a new button next to the "info" button. An option would be to have it look like a "+" (as in "How to add this task").

When clicked, this button should open a modal which displays the mardown-formatted `install_instructions` value.

This feature is needed for the public-page tasks list only, which means we would be introducing a slightly incorrect type for task objects (as we would be adding an optional property which will never be present when the task is generated by the backend). I'd say it's acceptable, but we can review this if relevant.

## Side note

If it is useful, we could define a new config variable for the `tasks-list` component (e.g. "display_type"), with values "fractal-web-modal", "fractal-web-single-page", "public-page". This config would determine what is included when.

If we can avoid it, all the better.

In this specific case, it is not strictly needed - since the `install_instructions` property would never be present in the API-provided JSON.

**Comment by jluethi** [comment]
This is a great start! :)

Can we use a slightly smaller header (for Fractal installation & Python installation)? Given that it's a long title & it's sometimes longer than the text below, having it a bit smaller would probably look better

**Comment by jluethi** [comment]
That's great!
