### ISSUE TITLE
Tasks page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#7]
This is one of the two pages that will be implemented first, and showed right after the user login.

### Basic features

* In the task page, the user can see a list of currently available tasks.
* In the task page, the user can trigger the collection of an additional task package.
* After a task collection is triggered, the user can monitor its progress.

(this is the basic plan, let's discuss further about details)

**Comment by tcompa** [comment]
(note that this should also go inside `me`, like the current projects page)

**Comment by tcompa** [comment]
When showing the list of tasks, the main table should include `name` and `source`.
The whole set of task attributes should then be available through a "Show" button.

**Comment by rkpasia** [comment]
With reference to basic feature requests:

> ### Basic features
> * ~~In the task page, the user can see a list of currently available tasks.~~
> * In the task page, the user can trigger the collection of an additional task package.
> * After a task collection is triggered, the user can monitor its progress.

I will considered this issue generally closed.

The others features will be tracked in a dedicated, more specific, issue — just related to task collection server process.
