### ISSUE TITLE
Also show the logs for successful task collection

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#70]
Ref #67

A GET call to  `/api/v1/task/collect/{state_id}?verbose=True` returns a response which always has the `.data.log` field, while if we set `verbose=False` (which is also the default) then the logs are only included for failed task collections.

I think we should always set `verbose=True` (for task-collection statuses: ongoing, successful, failed, ..), and always include the button to show the logs. That is: the user shall be able to view the log of any task collection in the list.

**Comment by rkpasia** [comment]
The query `?verbose=True` is relevant just for succeeded task collections.
