### ISSUE TITLE
Re-order list of `WorkflowTask`s

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#75]
Placeholder issue.

Refs:
* https://github.com/fractal-analytics-platform/fractal-web/issues/65
* https://github.com/fractal-analytics-platform/fractal-web/issues/61
* https://github.com/fractal-analytics-platform/fractal-web/issues/59

**Comment by tcompa** [comment]
See https://github.com/fractal-analytics-platform/fractal-server/issues/584#issuecomment-1479030867:

> Thinking about fractal-web, we could imagine that a certain "reorder tasks" button opens a new modal where the user can rearrange task order (with up/down arrows), and create an appropriate payload. In the end they would click "save", and modify the whole workflow.

**Comment by rkpasia** [comment]
I agree with the proposed dynamic of #584. 
The client will request a desired ordered list of workflow tasks and receive a success response if the same status is updated also in the server.

**Comment by tcompa** [comment]
As soon as https://github.com/fractal-analytics-platform/fractal-server/pull/585 by @ychiucco is merged and then released, we'll be able to include a `reordered_workflowtask_ids` attribute (a list of integers) in workflow-edit PATCH endpoint, you may include .

The way I expect this to work in the web client is the following:

* The user opens the "reorder workflow tasks" component (e.g. a modal), and sees the WorkflowTask list of the current workflow (known from context).
* Each WorkflowTask in the list has an `id` attribute (it doesn't matter whether the user sees it or not).
* Upon starting the component, the web client stores a variable with the current list of WorkflowTask IDs; this could look like `current_workflowtask_ids=[1,92,3]`.
* Next to each WorfklowTask in the list, there are two "move up" and "move down" buttons.
* When the user selects for instance the "move up" button for a given WorkflowTask, the corresponding ID in `current_workflowtask_ids` is swapped with the previous one. Meanwhile, the two WorkflowTasks are also swapped in the list which is displayed in the web page.
* Once the reordering is complete, the user clicks a button like "save" (or "update list", or something similar), which calls the workflow-edit API endpoint with payload `{"reordered_workflowtask_ids": [92, 1, 3]}`. The endpoint responds with the new Workflow object.

**Comment by tcompa** [comment]
Now available for testing in `fractal-server=1.1.1`

**Comment by tcompa** [comment]
It doesn't seem to work for me.
* I open the re-order modal.
* I click the down arrow for a given task, and I see that it moves down in the list.
* I click "save", and the modal is closed.
* The list still shows the previous order.
* I refresh the page.
* The list still shows the previous order.


(I am at e513914)

**Comment by tcompa** [comment]
> It doesn't seem to work for me.
> 
>     * I open the re-order modal.
> 
>     * I click the down arrow for a given task, and I see that it moves down in the list.
> 
>     * I click "save", and the modal is closed.
> 
>     * The list still shows the previous order.
> 
>     * I refresh the page.
> 
>     * The list still shows the previous order.
> 
> 
> (I am at [e513914](https://github.com/fractal-analytics-platform/fractal-web/commit/e513914ad87c0a3e06f5b7c730a8e723e8fe2452))

This was 100% my bad (I had not updated to fractal-server 1.1.1 yet).
It does work as intended.
