### ISSUE TITLE
Import realistic workflow

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#76]
## New additions
1. A fake `fractal-tasks-core=0.9.0` package, which has the right tasks (as placeholders), but almost no dependency - so that tasks collection is very fast. Path: `fractal-web/tests/data/fractal-tasks-core/dist/fractal_tasks_core-0.9.0-py3-none-any.whl`.
2. The JSON file of a realistic workflow, based on the fake `fractal-tasks-core=0.9.0` package. Path: `fractal-web/tests/data/my-workflows/cardiac-tiny.json`.

## Steps to reproduce bug
* Install the fake tasks package.
* Create new project.
* Import the workflow -> receive success message.
* Open the workflow page.
* Nothing shows up, and I see no special logs in the terminal running svelte.

## Expected behavior
I should see the imported workflow, with its (possibly complex/nested) arguments , or at least an error message.

**Comment by tcompa** [comment]
(I added these changes in `main`)

**Comment by rkpasia** [comment]
I think that the client already handles the import of a complex workflow by #42.

Moreover, I tried to reproduce the bug but the client actually imports the workflow.

Maybe the visualization of the parameters is not completely ok right now. 
With this issue shall we track the visualization of arguments/parameters or the fact that an import functionality is available or not?

**Comment by jluethi** [comment]
I can confirm, this is working now with the new parameter handling. See e.g. this video: https://drive.google.com/file/d/1fi4DIY1_3x8EhIYeLe9XSaysd-VstZkA/view?usp=sharing

It wasn't working with in the first iteration with nested dictionaries. Now, it displays them as containing "Objects". Let's use issue https://github.com/fractal-analytics-platform/fractal-web/issues/78 to track improvements to how the parameters are shown.

But given that import now works, I'm closing this
