### ISSUE TITLE
Frozen session during task reordering

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#84]
Reordering tasks in the example workflow sometimes leads to frozen session.

![Screenshot from 2023-04-04 15-20-18](https://user-images.githubusercontent.com/3862206/229805503-dc1d039d-0530-43e9-8156-3e1b0ee4a6b2.png)

**Comment by rkpasia** [comment]
[bc90d8f](https://github.com/fractal-analytics-platform/fractal-web/commit/bc90d8fe83e9ec7ad83b2dd6c3056b60004c9031) should prevent this issue.
