### ISSUE TITLE
Jobs table page (per project)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#85]
By calling the get-jobs (per project) endpoint, I receive a list of jobs, like:
```JSON
[
  {
    "project_id": 0,
    "input_dataset_id": 0,
    "output_dataset_id": 0,
    "workflow_id": 0,
    "overwrite_input": false,
    "worker_init": "string",
    "id": 0,
    "start_timestamp": "2023-04-05T12:54:39.657Z",
    "status": "string",
    "log": "string",
    "history": [
      "string"
    ],
    "working_dir": "string",
    "working_dir_user": "string"
  }
]
```

All columns are available in the "info" option.
Columns that are shown in the table are:
* job ID
* start timestamp
* workflow name (via workflow GET endpoint - ref #87)
* I/O dataset names
* status

Options should include:
* info
* logs

For each column, I can:
1. filter by value
2. sort

Possibly, we have a way to pre-fill filters or sorting by URL (via query parameters). Something like `http:/..../?filter_workflow_name=my_workflow&sort_by:workflow_name`

**Comment by tcompa** [comment]
> Possibly, we have a way to pre-fill filters or sorting by URL (via query parameters). Something like http:/..../?filter_workflow_name=my_workflow&sort_by:workflow_name

This should then be available (via a link) from a workflow page ("show me the latest job for this WF"), or from a dataset page,...

**Comment by tcompa** [comment]
Refs we are looking at:
* https://vincjo.fr/datatables/home, simpler and svelte native
* https://github.com/olifolkerd/tabulator, more powerful/flexible

As per `datatables`, an idea of how to pre-fill parameters from the URL appears to be the following. In https://vincjo.fr/datatables/api#filter, there is currently
```html
<script lang="ts">
    import type { DataHandler } from '@vincjo/datatables'
    export let handler: DataHandler
    
    let value1 = ''
    let value2 = ''

    const clear = () => {
        handler.clearFilters()
        value1 = ''
        value2 = ''
    }
</script>
```
which we could replace with something like
```html
<script lang="ts">
    import type { DataHandler } from '@vincjo/datatables'
    export let handler: DataHandler
    
    let value1 = PREFILLEDVALUE1
    let value2 = PREFILLEDVALUE2

    const clear = () => {
        handler.clearFilters()
        value1 = PREFILLEDVALUE1
        value2 = PREFILLEDVALUE2
    }
</script>
```
after getting the PREFILLEDVALUE1 and PREFILLEDVALUE2 variables from the URL.

**Comment by tcompa** [comment]
Broader list of examples: https://madewithsvelte.com/datatable

**Comment by tcompa** [comment]
We discussed a bit with @rkpasia and @mfranzon, and the first implementation will be through https://tanstack.com/table/v8 / https://github.com/TanStack/table.

**Comment by rkpasia** [comment]
Just a quick bullet point list to follow the work in progress in branch jobs-page:

- [ ] The selection of a support library for sorting/filtering
- [ ] Inclusion of the selected library within the project
- [ ] Setup of table
- [ ] Configuration of sorting
- [ ] Configuration of filtering
- [ ] Fetching of every information required within the table

**Comment by tcompa** [comment]
(I added one more item)
