### ISSUE TITLE
Users CRUD

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#9]
When logged in a superuser, the admin should be allowed to perform additional actions. These will eventually also include user management (registering a user, or editing their credentials/parameters), but at the beginning they would rather be some standard actions (e.g. removing objects from the database which are owned by other users).

This is a placeholder issue, since the access-control rules are not even fully defined on the fractal-server side

**Comment by tcompa** [comment]
First aspect of this issue would be to display a page for users' CRUD operations.

Basic features:
* Fetch and display users list as a table (`GET /auth/userlist`)
* Allow registration of a new user (`POST /auth/register`)
* Allow edit of an existing user (`PATCH /auth/users/{user_id}`)
* Allow deleting a user (`DELETE /auth/users/{user_id}`)

More advanced features:
* Display user's project list (`user.project_list`), with links to the corresponding project pages
* Modify a user's project list (e.g. to associate a user to an existing project) -> not yet exposed in fractal-server
* Display user-related jobs
* ...

**Comment by jluethi** [comment]
I'd be in favor of adding an "All Jobs" page for admins (see https://github.com/fractal-analytics-platform/fractal-web/issues/301#issuecomment-1786955077 for suggestion) as part of this first implementation, but leaving the more advanced admin features like displaying user projects, changing project association etc. for a bit later

**Comment by zonia3000** [comment]
I think I've found a small bug on the backend: it is not possible to set the `is_verified` flag during user creation:

Request:

```
POST /auth/register
{
  "email": "test@example.com",
  "is_active": true,
  "is_superuser": false,
  "is_verified": true,
  "username": "test",
  "password": "test"
}
```

Response:

```
{
  "id": 3,
  "email": "test@example.com",
  "is_active": true,
  "is_superuser": false,
  "is_verified": false,
  "slurm_user": null,
  "cache_dir": null,
  "username": "test"
}
```

I see that `is_verified` is a valid property of `UserCreate` type, so I assume that an admin should be able to create already verified users.

The flag can be changed correctly when using `PATCH`.

**Comment by tcompa** [comment]
> I see that is_verified is a valid property of UserCreate type, so I assume that an admin should be able to create already verified users.

Agreed, it's a bug in fractal-server.

I opened a specific issue here: https://github.com/fractal-analytics-platform/fractal-server/issues/963.

**Comment by tcompa** [comment]
> > I see that is_verified is a valid property of UserCreate type, so I assume that an admin should be able to create already verified users.
> 
> Agreed, it's a bug in fractal-server.

As in https://github.com/fractal-analytics-platform/fractal-server/issues/963#issuecomment-1816114097, for the moment we'll consider it a feature and not a bug. Therefore let's also remove the three `is_active,is_superuser,is_verified` properties from the register-user form in fractal-web.

**Comment by tcompa** [comment]
Also: we are currently disabling the delete-user endpoint (https://github.com/fractal-analytics-platform/fractal-server/issues/979), since it's not fully implemented in fractal-server. Therefore let's not include the "Delete" option.

An "Info" option, on the contrary, would be useful - as already discussed in our call this morning.
