### ISSUE TITLE
Job-table options column

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#98]
1. "info" -> just shows all attributes of a given job
2. "logs" should be available for jobs with status "done" or "failed" (EDIT: "running" is not relevant, for the moment)
3. "download logs"

**Comment by rkpasia** [comment]
What do we actually expect when the user will press a "download" button?

**Comment by jluethi** [comment]
> What do we actually expect when the user will press a "download" button?

On a higher level: The user would expect to get a zipped folder containing the logs for the relevant job

**Comment by rkpasia** [comment]
- ~"info" -> just shows all attributes of a given job~
- ~"logs" should be available for jobs with status "done" or "failed" (EDIT: "running" is not relevant, for the moment)~
- "download logs"

I think we should track the last point in a dedicated issue.

**Comment by jluethi** [comment]
Super cool! Being able to see the error log when a job failed enables a very important usability loop in the web frontend now, making it easy to see where a workflow failed, correct the parameters and then try again :)

**Comment by tcompa** [comment]
For the record, I ran a "wrong" workflow (I provided an array argument where an integer was expected), I saw it "failed" on the job-table page, I clicked the "Logs" button in "Options", and I saw
```
Workflow Job logs

TASK ERROR:Task id: 4 (prepare_metadata), e.workflow_task_order=0
TRACEBACK:
Traceback (most recent call last):
  File "/tmp/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_stresstest1.0.0/venv/lib/python3.10/site-packages/fractal_tasks_stresstest/prepare_metadata.py", line 37, in <module>
    run_fractal_task(
  File "/tmp/FRACTAL_TASKS_DIR/.fractal/fractal_tasks_stresstest1.0.0/venv/lib/python3.10/site-packages/fractal_tasks_stresstest/_utils.py", line 86, in run_fractal_task
    task_args = TaskArgsModel(**pars)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TaskArguments
num_components
  value is not a valid integer (type=type_error.integer)
```


This is perfectly aligned with the expected behavior, thanks @rkpasia

**Comment by tcompa** [comment]
(this was all in branch `v0.3`)
