### ISSUE TITLE
Can we use different filtering functions in job table?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#99]
This would be very useful for selecting a single job, or a single workflow.

**Comment by tcompa** [comment]
Note (with @rkpasia):
The problem of selecting a single job does not exist when this is the latest job (as is always the case in the submit-job-modal redirect), because IDs are always increasing.

The issue remains for when we want to show jobs of a single workflow (or show a single job, but not the latest one), but it is a bit less urgent.

Let's track progress in this issue, and also open an issue at datatables.

**Comment by tcompa** [comment]
Now available in datatables 1.6.0

**Comment by rkpasia** [comment]
Thanks to release `1.6.0` of [datatables](https://github.com/vincjo/datatables) we will be able to filter the resources in Jobs Workflow page through exact matching by IDs.
